### ISSUE TITLE
psycopg2.ProgrammingError: syntax error at or near "system_time"

### ISSUE THREAD

**Issue by marcerousseau** [biolab/orange3#1021]
Hi,

I am getting the following issue while using Orange. 

Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 680, in process_signals_for_widget
    handler(*args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 236, in set_data
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 680, in process_signals_for_widget
    handler(*args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owboxplot.py", line 237, in set_data
    self.attr_changed()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owboxplot.py", line 248, in attr_changed
    self.compute_box_data()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owboxplot.py", line 281, in compute_box_data
    dataset, distribution.get_distribution, (dataset, attr_ind))
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/utils/datacaching.py", line 17, in getCached
    info[funct] = res = funct(*params, **kwparams)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 680, in process_signals_for_widget
    handler(*args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 236, in set_data
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 294, in get_distribution
    return Discrete(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 39, in __new__
    return cls.from_data(dat, variable)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 63, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 294, in get_distribution
    return Discrete(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 39, in __new__
    return cls.from_data(dat, variable)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 63, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

--------------------------------------------------------------------------------
ProgrammingError                              Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 540, in _on_variable_idx_changed
    self._setup()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owdistributions.py", line 294, in _setup
    distribution.get_distribution(data, self.var)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 296, in get_distribution
    return Continuous(dat, variable, unknowns)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 194, in __new__
    return cls.from_data(variable, dat)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/statistics/distribution.py", line 213, in from_data
    dist, unknowns = data._compute_distributions([variable])[0]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 430, in _compute_distributions
    self = self.sample_time(DEFAULT_SAMPLE_TIME)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 663, in sample_time
    no_cache=no_cache)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 693, in _sample
    param=parameter)):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/data/sql/table.py", line 711, in _execute_sql_query
    cur.execute(query, param)
psycopg2.ProgrammingError: syntax error at or near "system_time"
LINE 1: ..._time_1000" AS SELECT * FROM "orders" TABLESAMPLE system_tim...
                                                             ^

**Comment by lanzagar** [comment]
It looks like the `tsm_system_time` extension is missing on the database server (Orange uses it for sampling).
If you set up Orange and the database manually, make sure these 2 extensions are available on the server:
https://github.com/biolab/orange3/wiki/Installation-of-PostgreSQL-extensions
Or you could install both the latest PostgreSQL database and Orange with the 2UDA installer:
http://2ndquadrant.com/2uda
and everything should be working out of the box.

If the extension is already installed, but you have created a new database, you might just need to enable the extension in it as well:
`CREATE EXTENSION tsm_system_time;`

**Comment by marcerousseau** [comment]
Thanks, it does work indeed.
Cheers

      De : Lan Zagar <notifications@github.com>
 À : biolab/orange3 <orange3@noreply.github.com> 
Cc : marcerousseau <rousseaumarc@ymail.com>
 Envoyé le : Lundi 15 février 2016 16h29
 Objet : Re: [orange3] psycopg2.ProgrammingError: syntax error at or near "system_time" (#1021)
   
It looks like the tsm_system_time extension is missing on the database server (Orange uses it for sampling).
If you set up Orange and the database manually, make sure these 2 extensions are available on the server:
https://github.com/biolab/orange3/wiki/Installation-of-PostgreSQL-extensions
Or you could install both the latest PostgreSQL database and Orange with the 2UDA installer:
http://2ndquadrant.com/2uda
and everything should be working out of the box.If the extension is already installed, but you have created a new database, you might just need to enable the extension in it as well:
CREATE EXTENSION tsm_system_time;—

**Comment by lanzagar** [comment]
Glad it works.
Closing the issue.
