### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'insertRow'

### ISSUE THREAD

**Issue by rahulroxx** [biolab/orange3#1043]
```
An exception occurred while loading entry point 'Orange Widgets = Orange.widgets'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/discovery.py", line 89, in run
    point = entry_point.load()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.2-py3.4.egg/pkg_resources/__init__.py", line 2379, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.2-py3.4.egg/pkg_resources/__init__.py", line 2396, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.2-py3.4.egg/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (chardet 2.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('chardet>=2.3.0'))
An exception occurred while loading entry point 'Text Mining = orangecontrib.text.widgets'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/discovery.py", line 89, in run
    point = entry_point.load()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.2-py3.4.egg/pkg_resources/__init__.py", line 2379, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.2-py3.4.egg/pkg_resources/__init__.py", line 2396, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.4/dist-packages/setuptools-19.2-py3.4.egg/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.2.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests==2.8.1'), {'smart-open'})
rahul@ubuntu:~/Desktop/orange3env/bin$ source activate
(orange3env)rahul@ubuntu:~/Desktop/orange3env/bin$ python3 -m Orange.canvas
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 194, in register_category
    self._insert_category(desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 178, in _insert_category
    cat_item = self._cat_desc_to_std_item(desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 215, in _cat_desc_to_std_item
    icon = icon_loader.from_description(desc).get(icon)
  File "/home/rahul/Desktop/orange3/Orange/canvas/resources.py", line 92, in from_description
    paths = search_paths_from_description(desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/resources.py", line 73, in search_paths_from_description
    dirname = package_dirname(package(desc.qualified_name))
  File "/home/rahul/Desktop/orange3/Orange/canvas/resources.py", line 18, in package_dirname
    filename = package.__file__
AttributeError: 'module' object has no attribute '__file__'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 197, in _insert_widget
    widget_item = self._widget_desc_to_std_item(desc, category)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 247, in _widget_desc_to_std_item
    icon = icon_loader.from_description(desc).get(icon)
  File "/home/rahul/Desktop/orange3/Orange/canvas/resources.py", line 92, in from_description
    paths = search_paths_from_description(desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/resources.py", line 70, in search_paths_from_description
    dirname = package_dirname(desc.package)
  File "/home/rahul/Desktop/orange3/Orange/canvas/resources.py", line 18, in package_dirname
    filename = package.__file__
AttributeError: 'module' object has no attribute '__file__'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
Traceback (most recent call last):
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/base.py", line 171, in register_widget
    self._insert_widget(cat_desc, desc)
  File "/home/rahul/Desktop/orange3/Orange/canvas/registry/qt.py", line 199, in _insert_widget
    cat_item.insertRow(insertion_i, widget_item)
AttributeError: 'NoneType' object has no attribute 'insertRow'
```

**Comment by rahulroxx** [comment]
i packaged **orangedemo** as described in the documentation  , i then installed the egg successfully but the data sample adapter doesn't show up in Orange.canvas and this error is raised.

**Comment by ales-erjavec** [comment]
Was the package by any chance installed as a zipped egg? Try installing with `pip install -e .`

**Comment by rahulroxx** [comment]
@ales-erjavec  yup  !  actually  i realized that i played around a bit with setuptools and i did 

`pip setup.py sdist`
have i ruined my workspace because everytime i run canvas i shows that same error 

How to revert ?

**Comment by rahulroxx** [comment]
@ales-erjavec  Thanks !
