### ISSUE TITLE
OWHeatMap crashes while launching

### ISSUE THREAD

**Issue by s-alexey** [biolab/orange3#1493]
Current [dev f370866638](https://github.com/biolab/orange3/tree/f370866638a603405dcd244401a52c2d7b9c6fa7) version

```
TypeError                                     Traceback (most recent call last):
  File "orange3/Orange/canvas/application/canvasmain.py", line 1758, in closeEvent
    if document.isModifiedStrict() and \
  File "orange3/Orange/canvas/document/schemeedit.py", line 513, in isModifiedStrict
    node_properties(self.__scheme)
  File "orange3/Orange/canvas/document/schemeedit.py", line 1663, in node_properties
    scheme.sync_node_properties()
  File "orange3/Orange/canvas/scheme/widgetsscheme.py", line 83, in sync_node_properties
    widget = self.widget_for_node(node)
  File "orange3/Orange/canvas/scheme/widgetsscheme.py", line 66, in widget_for_node
    return self.widget_manager.widget_for_node(node)
  File "orange3/Orange/canvas/scheme/widgetsscheme.py", line 194, in widget_for_node
    state = self.__materialize(state)
  File "orange3/Orange/canvas/scheme/widgetsscheme.py", line 232, in __materialize
    widget = self.create_widget_instance(node)
  File "orange3/Orange/canvas/scheme/widgetsscheme.py", line 328, in create_widget_instance
    env=self.scheme().runtime_env()
  File "orange3/Orange/widgets/widget.py", line 165, in __new__
    WidgetMessagesMixin.__init__(self)
  File "orange3/Orange/widgets/utils/messages.py", line 305, in __init__
    super().__init__()
  File "orange3/Orange/widgets/utils/messages.py", line 266, in __init__
    group_class = getattr(self, name)
  File "orange3/Orange/widgets/visualize/owheatmap.py", line 428, in sort_columns
    return self.ColumnOrdering[self.sort_columns_idx][0]
TypeError: list indices must be integers, not Setting
```

**Comment by kernc** [comment]
Resolved in https://github.com/biolab/orange3/pull/1497 and https://github.com/biolab/orange3/pull/1498.
