### ISSUE TITLE
[pandas] Data Table crash (test needed)

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#1518]
Select visualize continuous values in Data Table. It crashes.

```
--------------------------------------------------------------------------------
AttributeError                                Traceback (most recent call last):
  File "/Users/anze/dev/orange3/Orange/widgets/utils/itemmodels.py", line 1040, in data
    return instance.get_class()
  File "/Users/anze/miniconda3/envs/o3/lib/python3.5/site-packages/pandas/core/generic.py", line 2743, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'TableSeries' object has no attribute 'get_class'
--------------------------------------------------------------------------------
AttributeError                                Traceback (most recent call last):
  File "/Users/anze/dev/orange3/Orange/widgets/gui.py", line 2779, in paint
    if class_.variable.is_discrete and \
AttributeError: 'NoneType' object has no attribute 'variable'
--------------------------------------------------------------------------------
```

**Comment by kernc** [comment]
Blocks https://github.com/biolab/orange3/pull/1347.
