### ISSUE TITLE
ImportError: No module named 'PyQt4.QtWebKit'

### ISSUE THREAD

**Issue by rornor** [biolab/orange3#1683]
Unlike Ubuntu 16.04, in Ubuntu 16.10 `python3-pyqt` package does not provide QtWebKit: http://askubuntu.com/questions/840318/importerror-no-module-named-pyqt4-qtwebkit

QtWebKit is provided in `python3-pyside.qtwebkit`, but just renaming the import does not solve the problem (at least it fails on `QKeySequence.Quit` in main canvas)

**Comment by kernc** [comment]
Try running with `QT_API=pyqt5 orange-canvas` (if you have python3-pyqt5 installed) or with `OT_API=pyside orange-canvas`. Basically, export `QT_API` as one of those two options before running orange. Does it work?

**Comment by rornor** [comment]
Unfortuantelly no. 
In orange virtualenv, either this:

`QT_API=pyqt5 orange-canvas`

or, this:

`QT_API=pyside orange-canvas`

show same error:

> ImportError: No module named 'PyQt4.QtWebKit'

and I have installed bot pyside and pyqt5 with qtwebkit

**Comment by kernc** [comment]
Sorry, can you try that again with the latest source? The change of interest (https://github.com/biolab/orange3/pull/1171) was merged on Friday.

**Comment by rornor** [comment]
I pulled changes and installed AnyQt:

1. for PyQt5:
```
$ QT_API=pyqt5 orange-canvas                                                                                                                
Traceback (most recent call last):
  File "/home/ror/orange3/bin/orange-canvas", line 11, in <module>
    load_entry_point('Orange3', 'gui_scripts', 'orange-canvas')()
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ror/orange3/Orange/canvas/__main__.py", line 32, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/home/ror/orange3/Orange/canvas/application/canvasmain.py", line 30, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: No module named 'PyQt5.QtWebEngineWidgets'
```

while for PySide:

```
$ QT_API=pyside orange-canvas                                                                                                               
Traceback (most recent call last):
  File "/home/ror/orange3/bin/orange-canvas", line 11, in <module>
    load_entry_point('Orange3', 'gui_scripts', 'orange-canvas')()
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/home/ror/orange3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ror/orange3/Orange/canvas/__main__.py", line 31, in <module>
    from Orange.canvas.application.application import CanvasApplication
  File "/home/ror/orange3/Orange/canvas/application/application.py", line 8, in <module>
    from AnyQt.QtCore import Qt, QUrl, QEvent, pyqtSignal as Signal
ImportError: cannot import name 'pyqtSignal'
```

It's not clear what else is needed as such PyQt5 and PySide packages can't be searched in Synaptic, and of course I have both PyQt5.QtWebKit and PySide.QtWebKit importable in Python3.

**Comment by kernc** [comment]
Right. For PyQt5, you also need python3-pyqt5.qtwebkit deb package. As for PySide, I think that's a bug.

**Comment by rornor** [comment]
but I do have python3-pyqt5.qtwebkit

**Comment by kernc** [comment]
Have you perhaps got it to work? If not, could you perhaps fetch changes again? In `QT_API=pyqt5` case, the line `from PyQt5.QtWebEngineWidgets import QWebEngineView` indicates not everything is up-to-date (should be `from AnyQt...`).

**Comment by rornor** [comment]
Nice!
I pull the changes, run: `QT_API=pyqt5 orange-canvas` and orange3 showed it's glory :)

In case of interested, terminal printed this:

```
/home/ror/orange3/lib/python3.5/site-packages/pyqtgraph/Qt.py:25: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  import PyQt4
/home/ror/orange3/Orange/widgets/unsupervised/owmanifoldlearning.py:1: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import QWidget, QVBoxLayout
/home/ror/orange3/Orange/widgets/unsupervised/owmanifoldlearning.py:2: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  from PyQt4.QtCore import Qt
```

**Comment by ajdapretnar** [comment]
@rornor Is there something else to consider with this issue or can we close it?
