### ISSUE TITLE
'Manifold Learning' widget does not work with PyQt5

### ISSUE THREAD

**Issue by ales-erjavec** [biolab/orange3#1715]
##### Orange version

3.3.9.dev0+3d865bc

##### Expected behavior

Can survive initialization

##### Actual behavior

Does not survive initialization

```
Traceback (most recent call last):
  File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 454, in create_widget_instance
    widget.__init__()
  File "/Users/aleserjavec/workspace/orange3/Orange/widgets/unsupervised/owmanifoldlearning.py", line 175, in __init__
    self.tsne_editor = TSNEParametersEditor(self)
  File "/Users/aleserjavec/workspace/orange3/Orange/widgets/unsupervised/owmanifoldlearning.py", line 76, in __init__
    super().__init__(parent)
  File "/Users/aleserjavec/workspace/orange3/Orange/widgets/unsupervised/owmanifoldlearning.py", line 14, in __init__
    QWidget.__init__(self, parent)
TypeError: __init__() missing 1 required positional argument: 'widget'
```

##### Steps to reproduce the behavior

Attempt to place the widget on the canvas when running in an environment where PyQt5 is available.

##### Additional info (worksheets, data, screenshots, ...)

PyQt5 implements proper cooperative multiple inheritance, but the [`ManifoldParametersEditor`](https://github.com/biolab/orange3/blob/96ed45619f3cd8ec0997b84c7f48e813a854cca1/Orange/widgets/unsupervised/owmanifoldlearning.py#L12) uses a OWComponent mixin which does not.

**Comment by ales-erjavec** [comment]
Fixed as part of be3ff05c315f5d5a0c08d69834c7846717456079
