### ISSUE TITLE
ImportError: QtNetwork (Ubuntu 16.04)

### ISSUE THREAD

**Issue by pybokeh** [biolab/orange3#1781]
Ubuntu 16.04, installed orange from conda-forge.  Get following error message when issuing orange-canvas command:

Traceback (most recent call last):
  File "/home/pybokeh/miniconda3/envs/orange/bin/orange-canvas", line 4, in <module>
    import Orange.canvas.__main__
  File "/home/pybokeh/miniconda3/envs/orange/lib/python3.5/site-packages/Orange/canvas/__main__.py", line 25, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/home/pybokeh/miniconda3/envs/orange/lib/python3.5/site-packages/Orange/canvas/application/canvasmain.py", line 25, in <module>
    from PyQt4.QtNetwork import QNetworkDiskCache
ImportError: /home/pybokeh/miniconda3/envs/orange/lib/python3.5/site-packages/PyQt4/QtNetwork.so: undefined symbol: _ZTI10QSslSocket

**Comment by ajdapretnar** [comment]
Supposedly 
`conda update --all`
solves the problem.
