### ISSUE TITLE
The tool crashes when I connect SQL widget (SQLServer) with data table 

### ISSUE THREAD

**Issue by BlagoyVangelov** [biolab/orange3#1933]
The tool crashes when I connect SQL widget (SQLServer) with data table without downloading data to local memory option.

I'm experiencing this issue in versions 3.3.9, 3.3.10 
Works fine with 3.3.8

Exception:	ValueError: invalid data length for domain
Module:	Orange.data.domain:366
Widget Scheme:	C:\Users\Iliyan\AppData\Local\Temp\9\ows-x05eoscr.ows.xml

Version:	3.3.10
Environment:	Python 3.4.4 on Windows 2012Server 6.2.9200 AMD64
Installed Packages:	AnyQt==0.0.6, Bottleneck==1.2.0, Genesis-PyAPI==1.2.0, LTTL==2.0b5, Orange-Bioinformatics==2.6.19, Orange3-Associate==1.1.2, Orange3-DataFusion==0.1.10, Orange3-Datasets==0.1.3, Orange3-Prototypes==0.4.7, Orange3-Text==0.2.1, Orange3-Textable==3.0a5, Orange3-Timeseries==0.2.0, Orange3==3.3.10, PyQt4==4.11.4, beautifulsoup4==4.5.1, boto==2.43.0, bz2file==0.98, chardet==2.3.0, dill==0.2.5, docutils==0.12, future==0.16.0, gensim==0.13.3, joblib==0.10.3, keyring==10.0.2, keyrings.alt==1.1.1, nltk==3.2.1, numpy==1.11.2+mkl, oauthlib==2.0.1, observable==0.3.1, pandas==0.19.1, patsy==0.4.1, pip==8.1.2, psycopg2==2.6.2, pycountry==16.11.8, pymssql==2.1.3, pyqtgraph==0.10.0, pyreadline==2.1, python-dateutil==2.6.0, pytz==2016.7, pywin32-ctypes==0.0.1, requests-oauthlib==0.7.0, requests==2.12.1, scikit-fusion==0.2.1, scikit-learn==0.18.1, scipy==0.18.1, setuptools-git==1.1, setuptools==18.2, simhash==1.7.1, simple-wbd==0.5.1, six==1.10.0, slumber==0.7.1, smart-open==1.3.5, statsmodels==0.6.1, tweepy==3.5.0, validate-email==1.3, wheel==0.26.0, wikipedia==1.4.0, xlrd==1.0.0
Machine ID:	53350635052312
Stack Trace:	Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\Orange\widgets\utils\itemmodels.py", line 1113, in data
    instance = self._row_instance(row)
  File "C:\Python34\lib\functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python34\lib\site-packages\Orange\widgets\utils\itemmodels.py", line 938, in row_instance
    return self.source[int(index)]
  File "C:\Python34\lib\site-packages\Orange\data\sql\table.py", line 137, in __getitem__
    return self._fetch_row(key)
  File "C:\Python34\lib\functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python34\lib\site-packages\Orange\data\sql\table.py", line 182, in _fetch_row
    return SqlRowInstance(self.domain, values[0])
  File "C:\Python34\lib\site-packages\Orange\data\sql\table.py", line 662, in __init__
    super().__init__(domain, data[:nvar])
  File "C:\Python34\lib\site-packages\Orange\data\instance.py", line 41, in __init__
    self._x, self._y, self._metas = domain.convert(data)
  File "C:\Python34\lib\site-packages\Orange\data\domain.py", line 366, in convert
    raise ValueError("invalid data length for domain")
ValueError: invalid data length for domain
Local Variables:	{'Instance': <class 'Orange.data.instance.Instance'>,
 'inst': (1,),
 'nmetas': 6,
 'nvars': 2,
 'self': [Segment, ID] {AccountId, AccountName, AccountBrick, AccountCity, AccountGroup, TerritoryId}}

**Comment by ajdapretnar** [comment]
Could @lanzagar perhaps give a look?

**Comment by lanzagar** [comment]
If the problem is with Microsoft SQL Server, @astaric is the person to turn to.
I don't even have access to an SQLServer to test this on...

**Comment by ajdapretnar** [comment]
Is this still an issue? Would it be fixed with #3113?
