### ISSUE TITLE
ImportError at program launch.

### ISSUE THREAD

**Issue by danipozo** [biolab/orange3#2106]
##### Orange version

Latest as of now, cloned git repo.

##### Expected behavior
`python -m Orange.canvas` launchs Orange.

##### Actual behavior
Console output:
```
Traceback (most recent call last):
  File "/home/dani/orange/orange3/Orange/canvas/application/canvasmain.py", line 26, in <module>
    from AnyQt.QtWebEngineWidgets import QWebEngineView
  File "/usr/lib/python3.6/site-packages/AnyQt/QtWebEngineWidgets.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dani/orange/orange3/Orange/canvas/__main__.py", line 26, in <module>
    from Orange.canvas.application.canvasmain import CanvasMainWindow
  File "/home/dani/orange/orange3/Orange/canvas/application/canvasmain.py", line 29, in <module>
    from AnyQt.QtWebKitWidgets import QWebView
  File "/usr/lib/python3.6/site-packages/AnyQt/QtWebKitWidgets.py", line 14, in <module>
    from PyQt5.QtWebKitWidgets import *
ImportError: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory

```

##### Steps to reproduce the behavior
Clone git repo, follow steps in README and run the abovementioned command.

**Comment by danipozodg** [comment]
Update: I was just missing Qt5 WebKit, now I'm getting this:
```qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dani/orange/orange3/Orange/canvas/__main__.py", line 395, in <module>
    sys.exit(main())
  File "/home/dani/orange/orange3/Orange/canvas/__main__.py", line 250, in main
    canvas_window = CanvasMainWindow()
  File "/home/dani/orange/orange3/Orange/canvas/application/canvasmain.py", line 184, in __init__
    self.setup_ui()
  File "/home/dani/orange/orange3/Orange/canvas/application/canvasmain.py", line 235, in setup_ui
    self.dock_widget = CollapsibleDockWidget(objectName="main-area-dock")
  File "/home/dani/orange/orange3/Orange/canvas/gui/dock.py", line 58, in __init__
    QStyle.SP_ToolBarHorizontalExtensionButton
TypeError: standardPixmap(self, QStyle.StandardPixmap, QStyleOption, widget: QWidget = None): not enough arguments

```

**Comment by ajdapretnar** [comment]
I am not sure what to do about this. I assume this is a Linux issue. I think you just need Qt bindings. Are any of the installation steps missing in readme? @robertcv (perhaps you will know)

**Comment by robertcv** [comment]
@danipozo Does this issue still persist? Which OS and version of PyQt5 are you using?

**Comment by danipozo** [comment]
A similar issue arises now. Manjaro Linux, PyQt5 version 5.11.2-2.

`python -m Orange.canvas` output:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/dani/orange3/Orange/__init__.py", line 27, in <module>
    from AnyQt.QtCore import QObject
  File "/home/dani/orange3venv/lib/python3.7/site-packages/AnyQt/QtCore.py", line 247, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'

```

**Comment by ajdapretnar** [comment]
I might be a stupid question, but did you run `pip install -e .`?

**Comment by danipozo** [comment]
Yes, I did.

**Comment by janezd** [comment]
We can't replicate this. Let's hope it went away with newer version of Qt, or that it's an issue occurring on a particular unfortunate setup on one machine. :|
