### ISSUE TITLE
Merge Data: fails on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#2142]
##### Orange version
3.5.dev

##### Expected behavior
Merge data can merge Corpus and Table.

##### Actual behavior
Merge data fails on Corpus (sparse).

##### Steps to reproduce the behavior
File (iris.tab) - Merge Data
Corpus (bookexcerpts.tab) - Merge Data

##### Additional info (worksheets, data, screenshots, ...)
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/canvas/scheme/widgetsscheme.py", line 832, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Users/ajda/orange/orange3/Orange/widgets/data/owmergedata.py", line 216, in handleNewSignals
    self._invalidate()
  File "/Users/ajda/orange/orange3/Orange/widgets/data/owmergedata.py", line 241, in _invalidate
    self.commit()
  File "/Users/ajda/orange/orange3/Orange/widgets/data/owmergedata.py", line 231, in commit
    merged_data = self.merge()
  File "/Users/ajda/orange/orange3/Orange/widgets/data/owmergedata.py", line 268, in merge
    return self._join_table_by_indices(reduced_extra_data, match_indices)
  File "/Users/ajda/orange/orange3/Orange/widgets/data/owmergedata.py", line 353, in _join_table_by_indices
    X = self._join_array_by_indices(self.data.X, reduced_extra.X, indices)
  File "/Users/ajda/orange/orange3/Orange/widgets/data/owmergedata.py", line 379, in _join_array_by_indices
    to_change[known] = lookup[indices[known]]
ValueError: setting an array element with a sequence.

**Comment by ajdapretnar** [comment]
Duplicate of #2155.
