### ISSUE TITLE
Cannot install Orange

### ISSUE THREAD

**Issue by naranjito95** [biolab/orange3#2171]
##### Expected behavior
Installed successfully.

##### Actual behavior
```
Traceback (most recent call last):
  File "/usr/local/bin/orange-canvas", line 9, in <module>
    load_entry_point('Orange==2.7.8', 'gui_scripts', 'orange-canvas')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/Orange/OrangeCanvas/main.py", line 18, in <module>
    from PyQt4.QtGui import QFont, QColor
```

##### Steps to reproduce the behavior
$ python setup.py build
$ python setup.py install
$ orange-canvas

**Comment by ajdapretnar** [comment]
For issues related to Orange 2, please report them to Orange 2 [issue tracker](https://github.com/biolab/orange).

**Comment by naranjito95** [comment]
sorry...

**Comment by ajdapretnar** [comment]
No, don't worry. :) Glad you reported it, it's just the wrong place.
