### ISSUE TITLE
Orange3 depending on Qt4

### ISSUE THREAD

**Issue by stefanseefeld** [biolab/orange3#2185]
##### Orange version

3.4.1 (git version 6b9ec52)

##### Actual behavior
When I load example workflows, the console outputs errors such as
```
Could not load properties for 'File'.
Traceback (most recent call last):
  File "/usr/local/CA/anaconda3/envs/o6/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 700, in scheme_load
    properties = loads(data.data, data.format)
  File "/usr/local/CA/anaconda3/envs/o6/lib/python3.6/site-packages/Orange/canvas/scheme/readwrite.py", line 994, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
```

##### Steps to reproduce the behavior

Loading examples from Help -> examples will show the above error.

##### Additional info (worksheets, data, screenshots, ...)

I'm trying to run Orange5 with Qt5. It seems there are still a few hard-coded references to PyQt4 in the code. One in https://github.com/biolab/orange3/blob/master/Orange/widgets/utils/plot/owplot3d.py#L16-L18

but it appears also some in various example workflow (.ows) files.

How are thee .ows files generated ? Is there a script to regenerate them ?

Thanks,

**Comment by ajdapretnar** [comment]
Ows files aren't generated, they are hand-made and saved. Perhaps someone should clean all hard-coded stuff from Orange and make sure it's AnyQt all over. Agree, @astaric?

**Comment by ajdapretnar** [comment]
Also all Examples seem to work on PyQt5 as well.

**Comment by andrewchenshx** [comment]
encounter same errors.

**Comment by astaric** [comment]
Could you attach a workflow (.ows file) which triggers the error? It might help us figuring out what the underlying problem is.

**Comment by andrewchenshx** [comment]
@astaric , i work on win7 system. just input `python -m Orange.canvas` in the command line window, then in "Welcome to Orange Data Mining" dialog, click the "Examples" icon, then i get the following error message in command line window

> (C:\Users\Andrew\Anaconda3\envs\py35) C:\Users\Andrew>python -m Orange.canvas
C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\scheme\readw
rite.py:985: RuntimeWarning: Loaded module AnyQt._backport as a substitute for P
yQt4
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\scheme\readw
rite.py:985: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitut
e for PyQt4.QtCore
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
Could not load properties for 'File'.
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 697, in scheme_load
    properties = loads(data.data, data.format)
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 985, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 697, in scheme_load
    properties = loads(data.data, data.format)
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 985, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 697, in scheme_load
    properties = loads(data.data, data.format)
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 985, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Test & Score'.
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 697, in scheme_load
    properties = loads(data.data, data.format)
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 985, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'File'.
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 697, in scheme_load
    properties = loads(data.data, data.format)
  File "C:\Users\Andrew\Anaconda3\envs\py35\lib\site-packages\Orange\canvas\sche
me\readwrite.py", line 985, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://docs.
orange.biolab.si/3/visual-programming/')'

thanks

**Comment by astaric** [comment]
Thanks. Could you also provide the output of the
```
conda list
```
command?

**Comment by andrewchenshx** [comment]
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/_license-1.1-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/alabaster-0.7.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/anaconda-custom-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/anaconda-client-1.6.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/anaconda-navigator-1.5.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/anaconda-project-0.4.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/argcomplete-1.0.0-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/astroid-1.4.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/astropy-2.0.2-py35h891525e_4.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/babel-2.3.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/backports-1.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/beautifulsoup4-4.5.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/bitarray-0.8.1-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/blaze-0.10.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/bokeh-0.12.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/boto-2.45.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/bottleneck-1.2.1-np113py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/bzip2-1.0.6-vc14_3.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/cffi-1.9.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/chardet-2.3.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/chest-0.2.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/click-6.7-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/cloudpickle-0.2.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/clyent-1.2.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/colorama-0.3.7-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/comtypes-1.1.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/configobj-5.0.6-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/console_shortcut-0.1.1-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/contextlib2-0.5.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/cryptography-1.7.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/curl-7.52.1-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/cycler-0.10.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/cython-0.25.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/cytoolz-0.8.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/dask-0.13.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/datashape-0.5.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/decorator-4.0.11-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/dill-0.2.5-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/docutils-0.13.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/entrypoints-0.2.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/et_xmlfile-1.0.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/fastcache-1.0.2-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/flask-0.12-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/flask-cors-3.0.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/freetype-2.5.5-vc14_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/get_terminal_size-1.0.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/gevent-1.2.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/greenlet-0.4.11-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/h5py-2.7.0-np113py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/hdf5-1.8.15.1-vc14_4.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/heapdict-1.0.0-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/icu-57.1-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/idna-2.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/imagesize-0.7.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/ipykernel-4.5.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/ipython-5.1.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/ipython_genutils-0.1.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/ipywidgets-5.2.2-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/isort-4.2.5-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/itsdangerous-0.24-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jdcal-1.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jedi-0.9.0-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jinja2-2.9.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jpeg-9b-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jsonschema-2.5.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jupyter-1.0.0-py35_3.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jupyter_client-4.4.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jupyter_console-5.0.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/jupyter_core-4.2.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/keyring-9.3.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/lazy-object-proxy-1.2.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/libpng-1.6.27-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/libtiff-4.0.6-vc14_3.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/llvmlite-0.20.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/locket-0.2.0-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/lxml-3.7.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/markupsafe-0.23-py35_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/matplotlib-2.0.2-np113py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/menuinst-1.4.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/mistune-0.7.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/mkl-2017.0.1-0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/mkl-service-1.1.2-py35_3.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/mpmath-0.19-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/multipledispatch-0.4.9-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/nbconvert-4.2.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/nbformat-4.2.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/networkx-1.11-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/nltk-3.2.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/nose-1.3.7-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/notebook-4.3.1-py35_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/numba-0.35.0-np113py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/numexpr-2.6.2-np113py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/numpy-1.13.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/numpydoc-0.6.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/odo-0.5.0-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/openpyxl-2.4.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/openssl-1.0.2k-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pandas-0.20.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/partd-0.3.7-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/path.py-10.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pathlib2-2.2.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/patsy-0.4.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pep8-1.7.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pickleshare-0.7.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pillow-4.0.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pip-9.0.1-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/ply-3.9-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/prompt_toolkit-1.0.9-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/psutil-5.0.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/py-1.4.32-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyasn1-0.1.9-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pycosat-0.6.1-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pycparser-2.17-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pycrypto-2.6.1-py35_5.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pycurl-7.43.0-py35_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyflakes-1.5.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pygments-2.1.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pylint-1.6.4-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyopenssl-16.2.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyparsing-2.1.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyqt-5.6.0-py35_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pytables-3.2.2-np113py35_4.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pytest-3.0.6-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/python-3.5.2-0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/python-dateutil-2.6.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pytz-2016.10-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pywavelets-0.5.2-np113py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pywin32-220-py35_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyyaml-3.12-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/pyzmq-16.0.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/qt-5.6.2-vc14_3.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/qtawesome-0.4.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/qtconsole-4.2.1-py35_2.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/qtpy-1.2.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/requests-2.12.4-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/rope-0.9.4-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/ruamel_yaml-0.11.14-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scikit-image-0.13.0-np113py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scikit-learn-0.19.0-np113py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scipy-0.19.1-np113py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/seaborn-0.7.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/selenium-3.3.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/setuptools-27.2.0-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/simplegeneric-0.8.1-py35_1.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/singledispatch-3.4.0.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/sip-4.18-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/six-1.10.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/snowballstemmer-1.2.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/sockjs-tornado-1.0.3-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/sphinx-1.5.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/spyder-3.1.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sqlalchemy-1.1.6-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/statsmodels-0.8.0-np113py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/sympy-1.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/tk-8.5.18-vc14_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/toolz-0.8.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/tornado-4.4.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/traitlets-4.3.1-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/unicodecsv-0.14.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/vc-14-0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/vs2015_runtime-14.0.25123-0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/wcwidth-0.1.7-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/werkzeug-0.11.15-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/wheel-0.29.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/widgetsnbextension-1.2.6-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/win_unicode_console-0.5-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/wrapt-1.10.8-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/xlrd-1.0.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/xlsxwriter-0.9.6-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/xlwings-0.10.2-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/xlwt-1.2.0-py35_0.tar.bz2
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/zlib-1.2.8-vc14_3.tar.bz2
