### ISSUE TITLE
can not open orange-canvas 

### ISSUE THREAD

**Issue by Zefeng-Wu** [biolab/orange3#2433]
##### Orange version

Orange3==3.5.0.dev0+unknown

##### Expected behavior

Can not start orange window, And gave errors  as followings,

Traceback (most recent call last):
  File "/usr/local/bin/orange-canvas", line 9, in <module>
    load_entry_point('Orange3==3.5.0.dev0+unknown', 'gui_scripts', 'orange-canvas')()
  File "/usr/local/lib/python3.4/dist-packages/Orange3-3.5.0.dev0+unknown-py3.4-linux-x86_64.egg/Orange/canvas/__main__.py", line 332, in main
    canvas_window = CanvasMainWindow()
  File "/usr/local/lib/python3.4/dist-packages/Orange3-3.5.0.dev0+unknown-py3.4-linux-x86_64.egg/Orange/canvas/application/canvasmain.py", line 184, in __init__
    self.setup_ui()
  File "/usr/local/lib/python3.4/dist-packages/Orange3-3.5.0.dev0+unknown-py3.4-linux-x86_64.egg/Orange/canvas/application/canvasmain.py", line 217, in setup_ui
    self.scheme_widget = SchemeEditWidget()
  File "/usr/local/lib/python3.4/dist-packages/Orange3-3.5.0.dev0+unknown-py3.4-linux-x86_64.egg/Orange/canvas/document/schemeedit.py", line 140, in __init__
    self.__editFinishedMapper.mapped[QObject].connect(
KeyError: 'there is no matching overloaded signal'

**Comment by ales-erjavec** [comment]
Which version of PyQt and Qt do you have installed?

**Comment by Zefeng-Wu** [comment]
I have installed two version in python3.4.3 , one is PyQt5.2.1 with  qt5.2.1 , another one is PyQt4.10.4 with qt4.10.4, thanks

**Comment by Zefeng-Wu** [comment]
I have solved it by delete PyQt5.2.1
