### ISSUE TITLE
Test & Score deepcopy problem

### ISSUE THREAD

**Issue by gpstmp** [biolab/orange3#2793]
##### Orange version
3.7.1 

##### Expected behavior
I expect that Test & Score widget will work ok with Recommendations add-on widget (this model was working ok in prev versions of Orange, but produces an error after update).

##### Actual behavior
I have this error in logs:
```
----------------------------- TypeError Exception -----------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 842, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/evaluate/owtestlearners.py", line 486, in handleNewSignals
    self.__update()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/evaluate/owtestlearners.py", line 786, in __update
    learners_c = [copy.deepcopy(learner) for learner in learners]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/evaluate/owtestlearners.py", line 786, in <listcomp>
    learners_c = [copy.deepcopy(learner) for learner in learners]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 247, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle OWSVDPlusPlus objects
-------------------------------------------------------------------------------
```

##### Steps to reproduce the behavior
You can download a simple example here
[problem.zip](https://github.com/biolab/orange3/files/1500205/Problems.zip)

**Comment by kernc** [comment]
Seems like [Orange3-recommendation](https://github.com/biolab/orange3-recommendation) problem. I get:
```py
PicklingError: Can't pickle <class 'Orange.widgets.utils.owlearnerwidget.Outputs'>: attribute lookup Outputs on Orange.widgets.utils.owlearnerwidget failed
```

**Comment by kernc** [comment]
@gpstmp Would you care enough to help us migrate [recommender add-on's widgets](https://github.com/biolab/orange3-recommendation/blob/db421c32f85f123b1f3058865438df1b996772cd/orangecontrib/recommendation/widgets/owsvdplusplus.py#L24-L28) to use [new-style signals](http://orange-development.readthedocs.io/widget.html#input-output-signal-definitions) in a pull request?

**Comment by astaric** [comment]
The core problem is that (one of the) learners in c_learners holds a reference to the widget it was constructed with. This is a bad thing, but as @kernc said, a problem in orange3-recommendation add-on.

I have opened [a new issue on that repository](https://github.com/biolab/orange3-recommendation/issues/9), let's move the discussion there.
