### ISSUE TITLE
Problem with miniconda installer

### ISSUE THREAD

**Issue by oudim** [biolab/orange3#2803]
##### Orange version

Orange3 version : 3.7.1

##### Expected behavior
Orange3 should launch when I click LAUNCH button

##### Actual behavior
Traceback (most recent call last):
File "C:\User\Continuum\Anaconda3\Scripts\orange-canvas-script.py", line 3, in 
import Orange.canvas.__main__
File "C:\User\Continuum\Anaconda3\lib\site-packages\Orange\canvas\__main__.py", line 31, in 
from Orange.canvas.application.errorreporting import ErrorReporting, \
File "C:\User\Continuum\Anaconda3\lib\site-packages\Orange\canvas\application\errorreporting.py", line 2, in 
import pip
File "C:\User\Continuum\Anaconda3\lib\site-packages\pip\__init__.py", line 28, in 
from pip.vcs import git, mercurial, subversion, bazaar # noqa
File "C:\User\Continuum\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in 
from pip.download import path_to_url
File "C:\User\Continuum\Anaconda3\lib\site-packages\pip\download.py", line 41, in 
from pip._vendor.requests.adapters import BaseAdapter, HTTPAdapter
ModuleNotFoundError: No module named 'pip._vendor.requests.adapters'

##### Steps to reproduce the behavior
I used to use Orange3 within Anaconda Navigator. This morning, I upgraded Anaconda within Anaconda Prompt. After that, I 'm not able to launch Orange3. I get the messages I pasted above in the section Actual Behavior

**Comment by oudim** [comment]
Thank you for your help.

**Comment by astaric** [comment]
It seems like the anaconda upgrade broke the pip package.

Reinstalling orange3 or using the miniconda installer from [our website](https://orange.biolab.si/download/) should fix the problem.

If it does not, please reopen the issue.
