### ISSUE TITLE
Orange.widget.utils.concurrent clashes with the builtin module concurrent

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#2894]
##### Orange version

3.9, on Python 3.6.4.

Luckily, add-ons already use Orange.widgets.utils.concurrent, so it cannot be just renamed.

##### Additional info (worksheets, data, screenshots, ...)

```
Could not import 'Orange.widgets.data.owdatasets'.
Traceback (most recent call last):
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/Users/janez/Dropbox/orange3/Orange/widgets/data/owdatasets.py", line 9, in <module>
    from concurrent.futures import ThreadPoolExecutor, Future
  File "/Users/janez/Dropbox/orange3/Orange/widgets/utils/concurrent.py", line 12, in <module>
    import concurrent.futures
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package
Could not import 'Orange.widgets.data.owimpute'.
Traceback (most recent call last):
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/Users/janez/Dropbox/orange3/Orange/widgets/data/owimpute.py", line 4, in <module>
    import concurrent.futures
  File "/Users/janez/Dropbox/orange3/Orange/widgets/utils/concurrent.py", line 12, in <module>
    import concurrent.futures
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package
Could not import 'Orange.widgets.data.owtable'.
Traceback (most recent call last):
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/Users/janez/Dropbox/orange3/Orange/widgets/data/owtable.py", line 6, in <module>
    import concurrent.futures
  File "/Users/janez/Dropbox/orange3/Orange/widgets/utils/concurrent.py", line 12, in <module>
    import concurrent.futures
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package
Could not import 'Orange.widgets.evaluate.owtestlearners'.
Traceback (most recent call last):
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/Users/janez/Dropbox/orange3/Orange/widgets/evaluate/owtestlearners.py", line 13, in <module>
    import concurrent.futures
  File "/Users/janez/Dropbox/orange3/Orange/widgets/utils/concurrent.py", line 12, in <module>
    import concurrent.futures
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package
Could not import 'Orange.widgets.unsupervised.owdistancematrix'.
Traceback (most recent call last):
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Users/janez/Dropbox/orange3/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/Users/janez/Dropbox/orange3/Orange/widgets/unsupervised/owdistancematrix.py", line 14, in <module>
    from Orange.widgets.data.owtable import ranges
  File "/Users/janez/Dropbox/orange3/Orange/widgets/data/owtable.py", line 6, in <module>
    import concurrent.futures
  File "/Users/janez/Dropbox/orange3/Orange/widgets/utils/concurrent.py", line 12, in <module>
    import concurrent.futures
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package
```

**Comment by astaric** [comment]
From which directory are you running Orange?

As far as I understand module loading, this problem occurs if there was is concurrent.py in current directory (or anywhere in python path)

**Comment by janezd** [comment]
By a weird coincidence: yes, I ran it from that directory. It should have occurred to me that this is why it happens.
