### ISSUE TITLE
OWKMeans occasionally fails on travis

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3#2945]
Travis tests occasionally fail. Saw this on #2944 (not directly related) and have restarted the job.

```
FAIL: test_changing_k_changes_radio (Orange.widgets.unsupervised.tests.test_owkmeans.TestOWKMeans)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/unsupervised/tests/test_owkmeans.py", line 83, in test_changing_k_changes_radio
    self.send_signal(self.widget.Inputs.data, self.iris, wait=1000)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/tests/base.py", line 245, in send_signal
    self.assertTrue(spy.wait(timeout=wait))
AssertionError: False is not true
```

**Comment by markotoplak** [comment]
@pavlin-policar, as you wrote this code, could you please check what is happening?

**Comment by pavlin-policar** [comment]
Sure, I'll take a look at it. My first best guess is that sometimes (probably depending on the compute load) 5 seconds (or whatever it's set to) simply isn't enough to compute.

I'll try to find a more general solution than simply extending the wait time, but that could be a potential quick fix.

**Comment by markotoplak** [comment]
It was iris.tab. :) If that is too large, feel free to reduce the data size.

Here is another one I've just seen:

```
======================================================================
FAIL: test_silhouette_column (Orange.widgets.unsupervised.tests.test_owkmeans.TestOWKMeans)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/unsupervised/tests/test_owkmeans.py", line 354, in test_silhouette_column
    outtable = self.get_output(widget.Outputs.annotated_data)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/tests/base.py", line 303, in get_output
    "Failed to get output in the specified timeout")
AssertionError: False is not true : Failed to get output in the specified timeout
```
