### ISSUE TITLE
cannot install add-ons from the menu

### ISSUE THREAD

**Issue by oroue** [biolab/orange3#2964]
##### Orange version
Linux last version

##### Expected behavior
getting a list of add-ons using options/add-ons

##### Actual behavior
pop up as follows:
Error encountered:
Traceback (most recent call last):
  File "/home/roudenko/.local/lib/python3.5/site-packages/Orange/canvas/application/canvasmain.py", line 1625, in open_addons
    if not have_install_permissions():
  File "/home/roudenko/.local/lib/python3.5/site-packages/Orange/canvas/application/addons.py", line 755, in have_install_permissions
    with open(fn, "w"):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/test_write_19468'

##### Steps to reproduce the behavior
I guess the pb is related to the fact that I installed Orange locally.
Indeed, I do not even have the directory /usr/lib/python3.5/site-packages

##### Additional info (worksheets, data, screenshots, ...)

Is the only way to get add-ons in this case is to install them from your git using pip?

**Comment by ajdapretnar** [comment]
> Is the only way to get add-ons in this case is to install them from your git using pip?

We prefer using Anaconda distribution, where you can install them with conda install orange3-text, for example.
I will have a look at the issue in the meantime.

**Comment by astaric** [comment]
Should be solved by #2988

At least, after that PR is accepted, you should be able to see the list of add-ons.
