### ISSUE TITLE
Have an issue adding new add-ons

### ISSUE THREAD

**Issue by msweetnam** [biolab/orange3#3001]
##### Orange version
3.11.0

##### Expected behavior

I was trying to add a python module using the add-on manager. When i click on it in the menu, it starts to open and then pops up an error message (pasted below)

##### Actual behavior

Exception:
xmlrpc.client.Fault: <Fault -32601: 'server error; requested method not found'>
Module:
xmlrpc.client:656
Widget Scheme:
C:\Users\MSWEET~1\AppData\Local\Temp\ows-gb3_ytne.ows.xml
Version:
3.11.0
Environment:
Python 3.6.4 on Windows 7 6.1.7601 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CommonMark==0.7.4, Orange3==3.11.0, PySocks==1.6.8, asn1crypto==0.24.0, certifi==2018.1.18, cffi==1.11.5, chardet==3.0.4, cryptography==2.1.4, docutils==0.14, future==0.16.0, idna==2.6, joblib==0.11, keyring==9.0, keyrings.alt==2.3, numpy==1.13.3, pip==9.0.1, pyOpenSSL==17.5.0, pycparser==2.18, pyqtgraph==0.10.0, pywin32==222, requests==2.18.4, scikit-learn==0.19.1, scipy==0.19.1, serverfiles==0.2.1, setuptools==38.5.1, six==1.11.0, urllib3==1.22, wheel==0.30.0, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0
Machine ID:
345052807176
Stack Trace:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\Orange\canvas\application\addons.py", line 527, in _set_packages
    packages = f.result()
  File "C:\Program Files\Orange\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Program Files\Orange\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files\Orange\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Orange\lib\site-packages\Orange\canvas\application\addons.py", line 706, in list_pypi_addons
    releases = multicall()
  File "C:\Program Files\Orange\lib\xmlrpc\client.py", line 882, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "C:\Program Files\Orange\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files\Orange\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Program Files\Orange\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Program Files\Orange\lib\site-packages\Orange\canvas\application\addons.py", line 682, in single_request
    return self.parse_response(opener.open(req))
  File "C:\Program Files\Orange\lib\xmlrpc\client.py", line 1342, in parse_response
    return u.close()
  File "C:\Program Files\Orange\lib\xmlrpc\client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32601: 'server error; requested method not found'>

Local Variables:
OrderedDict([('self',
              <xmlrpc.client.Unmarshaller object at 0x0000000006FF9550>)])

##### Steps to reproduce the behavior

just click on the add-on button in the menu

**Comment by astaric** [comment]
If anyone is encountering this error on macOs, packages can be installed from terminal with the following command:

```
/Applications/Orange3.app/Contents/MacOS/pip install <add-on name>
```

(assuming Orange was installed into /Applications)

**Comment by msweetnam** [comment]
Thanks @markotoplak 
Just for clarity for anyone else that is looking at the same problem. What Marko is referring to is: pull up a command line via your windows start menu, change to the Miniconda3 sub directory, mine was installed here for example:

`C:\ProgramData\Miniconda3\Scripts`
And then just run the following (replace Orange3-Text with the package you're looking for)
`pip install Orange3-Text`

**Comment by msweetnam** [comment]
So what do you think @markotoplak Marko? they installed but not usable in Orange.. any thoughts?

**Comment by msweetnam** [comment]
When i try to install _Orange3-Text_ from pip, it can't finish. After it downloads the files successfully, it has this (snippet): 
```
  Downloading https://files.pythonhosted.org/packages/05/ae/cedf5323f398ab4e4ff9
2d6c431a3e1c6a186f9b41ab3e8258dff786a290/Bottleneck-1.2.1.tar.gz (105kB)
    100% |████████████████████████████████| 112kB 1.9MB/s
    Complete output from command python setup.py egg_info:
    Could not locate executable g77
    Could not locate executable f77
    Could not locate executable ifort
    Could not locate executable ifl
    Could not locate executable f90
    Could not locate executable DF
    Could not locate executable efl
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable g95
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
    non-existing path in 'numpy\\distutils': 'site.cfg'
    Running from numpy source directory.
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-eujc8hb5\numpy-1.14.2\setu
p.py:369: UserWarning: Unrecognized setuptools command, proceeding with generati
ng Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-eujc8hb5\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-eujc8hb5\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-eujc8hb5\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
```

**Comment by msweetnam** [comment]
Ok @markotoplak I can't go any further with the tool without the text widgets 
Please let me know if you can let me know how i can get these things loaded

**Comment by msweetnam** [comment]
Complete output from command python setup.py egg_info:
    Could not locate executable g77
    Could not locate executable f77
    Could not locate executable ifort
    Could not locate executable ifl
    Could not locate executable f90
    Could not locate executable DF
    Could not locate executable efl
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable g95
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
    non-existing path in 'numpy\\distutils': 'site.cfg'
    Running from numpy source directory.
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.14.2\setu
p.py:369: UserWarning: Unrecognized setuptools command, proceeding with generati
ng Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      self.calc_info()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      self.calc_info()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.14.2\nump
y\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    C:\ProgramData\Miniconda3\lib\distutils\dist.py:261: UserWarning: Unknown di
stribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\msvc.py", line 474, in __init__
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\distutils\core.py", line 148, in setup

        dist.run_commands()
      File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 955, in run_c
ommands
        self.run_command(cmd)
      File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 974, in run_c
ommand
        cmd_obj.run()
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\bdist_egg.py", line 152, in run
      File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_co
mmand
        self.distribution.run_command(command)
      File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 974, in run_c
ommand
        cmd_obj.run()
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\command\egg_info.py", line 26, in run
      File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_co
mmand
        self.distribution.run_command(command)
      File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 974, in run_c
ommand
        cmd_obj.run()
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\command\build_src.py", line 148, in run
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\command\build_src.py", line 159, in build_sources
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\command\build_src.py", line 294, in build_library_sources
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\command\build_src.py", line 377, in generate_sources
      File "numpy\core\setup.py", line 673, in get_mathlib_info
      File "C:\ProgramData\Miniconda3\lib\distutils\command\config.py", line 243
, in try_link
        self._check_compiler()
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\command\config.py", line 51, in _check_compiler
      File "C:\ProgramData\Miniconda3\lib\distutils\_msvccompiler.py", line 197,
 in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\msvc.py", line 170, in msvc14_get_vc_env
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\msvc.py", line 767, in __init__
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\msvc.py", line 477, in __init__
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is requir
ed. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstud
io.com/visual-cpp-build-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 156, in save_modules
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 197, in setup_context
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 246, in run_setup
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 276, in run
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 245, in runner
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 47, in _execfile
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\setup.py", line 394, in <module>
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\setup.py", line 386, in setup_package
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\core.py", line 169, in setup
      File "C:\ProgramData\Miniconda3\lib\distutils\core.py", line 163, in setup

        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Micro
soft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-buil
d-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\easy_install.py", line 1100, in run_setup
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 249, in run_setup
      File "C:\ProgramData\Miniconda3\lib\contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 197, in setup_context
      File "C:\ProgramData\Miniconda3\lib\contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 168, in save_modules
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 143, in resume
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 156, in save_modules
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 197, in setup_context
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 246, in run_setup
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 276, in run
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 245, in runner
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\sandbox.py", line 47, in _execfile
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\setup.py", line 394, in <module>
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\setup.py", line 386, in setup_package
      File "C:\Users\MSWEET~1\AppData\Local\Temp\easy_install-5qiofo_x\numpy-1.1
4.2\numpy\distutils\core.py", line 169, in setup
      File "C:\ProgramData\Miniconda3\lib\distutils\core.py", line 163, in setup

        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Micro
soft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-buil
d-tools

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MSWEET~1\AppData\Local\Temp\pip-build-kv7ealit\bottleneck\s
etup.py", line 110, in <module>
        setup(**metadata)
      File "C:\ProgramData\Miniconda3\lib\distutils\core.py", line 108, in setup

        _setup_distribution = dist = klass(attrs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\dist.py", line 315, in __init__
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\dist.py", line 361, in fetch_build_eggs
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\pkg_resources\__init__.py", line 851, in resolve
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\pkg_resources\__init__.py", line 1123, in best_match
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\pkg_resources\__init__.py", line 1135, in obtain
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\dist.py", line 428, in fetch_build_egg
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\easy_install.py", line 664, in easy_install
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\easy_install.py", line 694, in install_item
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\easy_install.py", line 875, in install_eggs
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\easy_install.py", line 1114, in build_and_install
      File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools-27.2.0-py3.6.
egg\setuptools\command\easy_install.py", line 1102, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft V
isual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http
://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MSWEET~1
\AppData\Local\Temp\pip-build-kv7ealit\bottleneck\
You are using pip version 9.0.1, however version 10.0.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\ProgramData\Miniconda3\Scripts>

**Comment by msweetnam** [comment]
Also, i tried to install the new version.. (after installing VC++) 
with
`pip install Orange3`
which ended up with the error in the post above..

**Comment by astaric** [comment]
@msweetnam, if you are on windows and installed via the official installer, you can use conda to install packages that require compiler to build.

Open Orange3 Command Prompt from start menu, and then run
```
conda install orange3-text
```

**Comment by markotoplak** [comment]
New release of Orange, which fixes add-on problems, is now available.

Thank you for reporting the bug. We are sorry for the problems this caused.

**Comment by msweetnam** [comment]
That did it, thanks @markotoplak !
