### ISSUE TITLE
Problem in installation under Python3:  AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

### ISSUE THREAD

**Issue by LanceNorskog** [biolab/orange3#3023]
##### Orange version
Contemporary version of Orange3 available via python3-pip.

##### Expected behavior
Install should finish, or tell me to install other needed packages.

##### Actual behavior

setup.py fails, final line of stack trace is:
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

##### Steps to reproduce the behavior

(On Linux Mint, create python3.4 virtual env and activate.)
./bin/easy_install-3.4 orange3

##### Additional info (worksheets, data, screenshots, ...)
Linux Mint (Ubuntu) is committed to Python 2.7 for system utilities and it must be the default Python.
Following is the complete error printout:
```
(orange) lance@lance-personal ~/tools/orange $ bin/easy_install-3.4 orange3
Searching for orange3
Best match: Orange3 3.13.0
Processing Orange3-3.13.0-py3.4.egg
Orange3 3.13.0 is already the active version in easy-install.pth
Installing orange-canvas script to /home/lance/tools/orange/bin

Using /home/lance/tools/orange/lib/python3.4/site-packages/Orange3-3.13.0-py3.4.egg
Processing dependencies for orange3
Searching for bottleneck>=1.0.0
Reading https://pypi.org/simple/bottleneck/
Downloading https://files.pythonhosted.org/packages/05/ae/cedf5323f398ab4e4ff92d6c431a3e1c6a186f9b41ab3e8258dff786a290/Bottleneck-1.2.1.tar.gz#sha256=6efcde5f830aed64feafca0359b51db0e184c72af8ba6675b4a99f263922eb36
Best match: Bottleneck 1.2.1
Processing Bottleneck-1.2.1.tar.gz
Writing /tmp/easy_install-ikj97hpj/Bottleneck-1.2.1/setup.cfg
Running Bottleneck-1.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ikj97hpj/Bottleneck-1.2.1/egg-dist-tmp-b46250tl
Traceback (most recent call last):
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ikj97hpj/Bottleneck-1.2.1/setup.py", line 110, in <module>
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 278, in run
    self.find_sources()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
    mm.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 524, in run
    self.add_defaults()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
    sdist.add_defaults(self)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
    self._add_defaults_ext()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-ikj97hpj/Bottleneck-1.2.1/setup.py", line 24, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/easy_install-3.4", line 11, in <module>
    sys.exit(main())
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 2312, in main
    **kw
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 704, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 746, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/lance/tools/orange/lib/python3.4/site-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/home/lance/tools/orange/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
    run_setup(setup_script, args)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ikj97hpj/Bottleneck-1.2.1/setup.py", line 110, in <module>
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 278, in run
    self.find_sources()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
    mm.run()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 524, in run
    self.add_defaults()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
    sdist.add_defaults(self)
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
    self._add_defaults_ext()
  File "/home/lance/tools/orange/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-ikj97hpj/Bottleneck-1.2.1/setup.py", line 24, in finalize_options
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

**Comment by kernc** [comment]
Once you're in the _orange_ virtual env, try with `pip` instead:
```bash
pip install -U pip   # update pip
pip install orange3
```

The traceback [points to Bottleneck](https://github.com/kwgoodman/bottleneck/blob/769d5b34aedf4c374b61be99ed4a7b599774006e/setup.py#L24) (a dependency of Orange); even just `bin/easy_install-3.4 bottleneck` should fail. If using pip doesn't solve your issue, consider raising issue with them.

**Comment by ajdapretnar** [comment]
@LanceNorskog Can you confirm the `bin/easy_install-3.4 bottleneck` fails?

**Comment by janezd** [comment]
Closed due to inactivity.
