### ISSUE TITLE
Orange crashed: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3#3069]
```
Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
----------------------------- TypeError Exception -----------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 960, in process_signals_for_widget
    widget.handleNewSignals()
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplot.py", line 331, in handleNewSignals
    self.graph.new_data(self.data, self.subset_data)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplotgraph.py", line 618, in new_data
    self.set_data(data, **args)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/scaling.py", line 105, in set_data
    self._compute_scaled_data()
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/scaling.py", line 58, in _compute_scaled_data
    c += 0.5
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
-------------------------------------------------------------------------------
QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
Error calling 'handleNewSignals()' of 'Scatter Plot'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 960, in process_signals_for_widget
    widget.handleNewSignals()
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplot.py", line 331, in handleNewSignals
    self.graph.new_data(self.data, self.subset_data)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplotgraph.py", line 618, in new_data
    self.set_data(data, **args)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/scaling.py", line 105, in set_data
    self._compute_scaled_data()
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/scaling.py", line 58, in _compute_scaled_data
    c += 0.5
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
/usr/local/lib/python3.6/site-packages/Orange/projection/radviz.py:45: RuntimeWarning: invalid value encountered in true_divide
  return (x - a[np.newaxis, :]) / ((b - a)[np.newaxis, :])
/usr/local/lib/python3.6/site-packages/Orange/statistics/util.py:327: RuntimeWarning: All-NaN slice encountered
  np.nanmin(X, axis=0),
/usr/local/lib/python3.6/site-packages/Orange/statistics/util.py:328: RuntimeWarning: All-NaN slice encountered
  np.nanmax(X, axis=0),
/usr/local/lib/python3.6/site-packages/Orange/statistics/util.py:329: RuntimeWarning: Mean of empty slice
  np.nanmean(X, axis=0) if not weighted else weighted_mean(),
----------------------------- TypeError Exception -----------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 960, in process_signals_for_widget
    widget.handleNewSignals()
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owradviz.py", line 657, in handleNewSignals
    self.setup_plot(reset_view=True)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owradviz.py", line 717, in setup_plot
    self.graph.new_data(data[mask], subset_data)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplotgraph.py", line 618, in new_data
    self.set_data(data, **args)
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/scaling.py", line 105, in set_data
    self._compute_scaled_data()
  File "/usr/local/lib/python3.6/site-packages/Orange/widgets/utils/scaling.py", line 58, in _compute_scaled_data
    c += 0.5
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
-------------------------------------------------------------------------------
QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
Unhandled Python exception
Abort trap
```

Version 3.13.0.120.

**Comment by ajdapretnar** [comment]
Could you perhaps provide a bit of a description of the workflow? A screenshot maybe? So we can replicate the problem?
Looks like Radviz issue, but it would be nice to have some details. :)

**Comment by janezd** [comment]
Radviz has been completely reimplemented since this issue has been reported.
