### ISSUE TITLE
Travis fails on PyQt5 with 'QAbstractTableModel' has no attribute 'VerticalSortHint'

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#3114]
Tests on travis fail with the following error:

```
======================================================================
ERROR: test_auto_send (Orange.widgets.data.tests.test_owrank.TestOWRank)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/data/tests/test_owrank.py", line 306, in test_auto_send
    self.send_signal(self.widget.Inputs.data, self.iris)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/tests/base.py", line 241, in send_signal
    handler(value, *args)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/utils/sql.py", line 31, in new_f
    return f(widget, data, *args, **kwargs)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/data/owrank.py", line 302, in set_data
    self.ranksModel.resetSorting(True)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/data/owrank.py", line 157, in resetSorting
    super().resetSorting()
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/utils/itemmodels.py", line 174, in resetSorting
    return self.sort(-1)
  File "/home/travis/build/biolab/orange3/build/travis-test/Orange/widgets/utils/itemmodels.py", line 202, in sort
    [], QAbstractTableModel.VerticalSortHint
AttributeError: type object 'QAbstractTableModel' has no attribute 'VerticalSortHint'
```

They started failing when PyQt5=1.11.2 was released. As far as I can tell from the [documentation](http://doc.qt.io/qt-5/qabstractitemmodel.html), the class should still  contain this member.

**Comment by astaric** [comment]
@ales-erjavec, is there anything we can do besides downgrading PyQt on Travis?

**Comment by ales-erjavec** [comment]
Change `QAbstractTableModel.VerticalSortHint` to `QAbstractTableModel.LayoutChangeHint(1)` with a comment explaining why?

**Comment by ales-erjavec** [comment]
See: https://www.riverbankcomputing.com/pipermail/pyqt/2018-July/040510.html
So maybe just wait it out.

**Comment by ajdapretnar** [comment]
Is this still relevant? I think tests on Travis are now ok?

**Comment by ales-erjavec** [comment]
Yes this is now ok.
