### ISSUE TITLE
Problem while trying to install Addons in Orange

### ISSUE THREAD

**Issue by HarishDawath** [biolab/orange3#3118]
Yes Add-ons after completion retrieval its showing error "Cloud not retrieve package list"

##### Orange version

Version 3.14

##### Expected behavior
It should show available packages to get install into my system

##### Actual behavior
Not able to retrieve the packages

##### Steps to reproduce the behavior
Goto-->Options--->Add-ons

##### Additional info (worksheets, data, screenshots, ...)
Yes 
![image](https://user-images.githubusercontent.com/33923554/42320345-a53a62cc-8072-11e8-9942-692a3b5ca170.png)

**Comment by ajdapretnar** [comment]
@markotoplak Is this a proxy thing?

**Comment by markotoplak** [comment]
@HarishDawath, how is your internet connection working? Are you perhaps using proxies or a VPN?

If you need a proxy server and it was not automatically detected, go to Orange's settings (on windows under Options) and enter a proxy server manually.

**Comment by saschalalala** [comment]
I had the same problem yesterday. For me, updating all packages via `conda` helped. Perhaps, you have to update your Orange installation?

**Comment by janezd** [comment]
Closed because of inactivity.

**Comment by imroner** [comment]
I have sam error 
![error install addon orange3](https://user-images.githubusercontent.com/46581220/81043146-eb024d00-8edb-11ea-89ef-eb1ab5d905b0.png)

**Comment by TakouaGUIGA** [comment]
Hello, here’s a solution that might help! 

let’s go to the folder where you installed orange data mining and follow these instructions : 

Orange Data mining --> lib --> site packages -->requests --> adapters.py 

1.	open the script adapters.py and search for the line where the function “send” is defined : 

def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):

2.	add this line:  proxies = None  just before conn = self.get_connection(request.url, proxies)
like this : 
try:
           proxies = None  
            conn = self.get_connection(request.url, proxies)
3.	Save 

Now let’s open another file: 
Orange Data mining --> lib --> site packages -->cache control -->serialize.py 

in the bottom of the script : 

1.	find the function _loads_V4 : 
def _loads_v4(self, request, data):
        try:
            #cached = msgpack.loads(data, encoding="utf-8") ( comment this line ) 
and change it with this line : 
            cached = msgpack.loads(data)

2.	Save

Now open orange data mining and follow these instructions:
options-->settings-->Add-ons-->pip install arguments--> write this :   --user

Check that no proxy is defined in “Network” 

exit Orange data mining and restart it.

And now you can install Add-ons you want :-)

**Comment by sdfungayi** [comment]
@TakouaGUIGA I tried the suggestion but I am getting the error 
![Orange](https://user-images.githubusercontent.com/81328264/112374383-b6150980-8cea-11eb-8a96-992f4cc831cf.JPG)

The error details are:
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Program Files\Orange\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Program Files\Orange\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000128CE4EEC08>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\requests\adapters.py", line 450, in send
    timeout=1000
  File "C:\Program Files\Orange\lib\site-packages\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Orange\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000128CE4EEC08>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 688, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1260, in list_available_versions
    defaults = config.addon_defaults_list()
  File "C:\Program Files\Orange\lib\site-packages\Orange\canvas\config.py", line 158, in addon_defaults_list
    return session.get(OFFICIAL_ADDON_LIST).json()
  File "C:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Orange\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Orange\lib\site-packages\requests\adapters.py", line 517, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000128CE4EEC08>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

**Comment by irgolic** [comment]
It seems that this issue is getting search hits.

**Comment by ales-erjavec** [comment]
> OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

This might be caused by firewall and/or anti virus software. 

@sdfungayi Do you have them? Try selectively disabling them to see if they are causing this.

**Comment by sdfungayi** [comment]
SOLVED
The issue was with my firewall.
The problem persisted when I turned off my firewall. So I turned it back on and specifically opened for C:\program files\orange\python.exe, C:\program files\orange\pythonw.exe and C:\programdata\miniconda3\python.exe
