### ISSUE TITLE
Orange 3.15 fails to open under Anaconda 5.2.0 installer

### ISSUE THREAD

**Issue by leeherman99** [biolab/orange3#3250]
##### Orange version

Windows 7
Anaconda3-5.2.0-Windows-x86_64
Orange 3.15

##### Expected behavior

Orange3 opens

##### Actual behavior
Orange3 fails to open, with the following error messages:

Traceback (most recent call last):
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\Scripts\orange-canvas-script.py", line 6, in 
from Orange.canvas.__main__ import main
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\__main__.py", line 30, in 
from Orange.canvas.application.canvasmain import CanvasMainWindow
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\application\canvasmain.py", line 61, in 
from .canvastooldock import CanvasToolDock, QuickCategoryToolbar, \
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\application\canvastooldock.py", line 25, in 
from ..document.quickmenu import MenuPage
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\document\__init__.py", line 17, in 
from .schemeedit import SchemeEditWidget
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\document\schemeedit.py", line 37, in 
from .suggestions import Suggestions
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\document\suggestions.py", line 7, in 
from .interactions import NewLinkAction
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\document\interactions.py", line 28, in 
from ..canvas import items
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\canvas\items\__init__.py", line 9, in 
from .annotationitem import TextAnnotation, ArrowAnnotation
File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\Orange\canvas\canvas\items\annotationitem.py", line 7, in 
import CommonMark
ModuleNotFoundError: No module named 'CommonMark'

##### Steps to reproduce the behavior

Did complete uninstall/reinstall of Anaconda, no change.

##### Additional info (worksheets, data, screenshots, ...)

Did a conda update --all, no change.

**Comment by ajdapretnar** [comment]
Fixed in #3234. New version is released, which will solve the issue.

**Comment by leeherman99** [comment]
Yes, 3.16 works.
