### ISSUE TITLE
Orange 3 Launcher May Have Produced Errors

### ISSUE THREAD

**Issue by Slimmey** [biolab/orange3#3288]
##### Orange version

 Failure to launch from Anaconda on MacOS

/Users/name/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
from ._conv import register_converters as _register_converters
Traceback (most recent call last):
File "/Users/name/anaconda3/bin/orange-canvas", line 7, in 
from Orange.canvas.__main__ import main
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/__main__.py", line 30, in 
from Orange.canvas.application.canvasmain import CanvasMainWindow
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 61, in 
from .canvastooldock import CanvasToolDock, QuickCategoryToolbar, \
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/application/canvastooldock.py", line 25, in 
from ..document.quickmenu import MenuPage
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/document/__init__.py", line 17, in 
from .schemeedit import SchemeEditWidget
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/document/schemeedit.py", line 37, in 
from .suggestions import Suggestions
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/document/suggestions.py", line 7, in 
from .interactions import NewLinkAction
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/document/interactions.py", line 28, in 
from ..canvas import items
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/canvas/items/__init__.py", line 9, in 
from .annotationitem import TextAnnotation, ArrowAnnotation
File "/Users/name/anaconda3/lib/python3.6/site-packages/Orange/canvas/canvas/items/annotationitem.py", line 7, in 
import CommonMark
ModuleNotFoundError: No module named 'CommonMark'

**Comment by Slimmey** [comment]
Yes. Thank you. It worked now after trying both uninstalling application and then installing Orange3 and then Updating it from the Anaconda Navigator.
