### ISSUE TITLE
Annoying Error window

### ISSUE THREAD

**Issue by Vasco10** [biolab/orange3#3368]
Orange 3.17 on its Anaconda Environment with Python 3.6

##### Orange version
Version 3.17.0

##### Expected behavior
It works as expected.

##### Actual behavior
Error window
--------------

C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
'{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Error while importing 'orangecontrib.timeseries.widgets.owyahoofinance'. The widget will not be shown.
Traceback (most recent call last):
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\timeseries\widgets\owyahoofinance.py", line 10, in 
from orangecontrib.timeseries.datasources import finance_data
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\timeseries\datasources.py", line 4, in 
import pandas_datareader.data as web
ModuleNotFoundError: No module named 'pandas_datareader'
C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\gensim\utils.py:1209: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Error while importing 'orangecontrib.prototypes.widgets.owface'. The widget will not be shown.
Traceback (most recent call last):
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\prototypes\widgets\owface.py", line 7, in 
import cv2
ModuleNotFoundError: No module named 'cv2'
Error while importing 'orangecontrib.prototypes.widgets.owparallelcoordinates'. The widget will not be shown.
Traceback (most recent call last):
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\prototypes\widgets\utils\plotly_widget.py", line 17, in 
from AnyQt.QtWebEngineWidgets import QWebEngineView
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\AnyQt\QtWebEngineWidgets.py", line 4, in 
from PyQt5.QtWebEngineWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\prototypes\widgets\owparallelcoordinates.py", line 15, in 
from orangecontrib.prototypes.widgets.utils.plotly_widget import Plotly
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\prototypes\widgets\utils\plotly_widget.py", line 21, in 
raise RuntimeError('Plotly-based plots require QtWebEngine (from Qt >= 5.5)')
RuntimeError: Plotly-based plots require QtWebEngine (from Qt >= 5.5)
Error while importing 'orangecontrib.prototypes.widgets.owwebcamcapture'. The widget will not be shown.
Traceback (most recent call last):
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\Orange\canvas\registry\discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File "C:\Python\Anaconda3\envs\Orange3_Env\lib\site-packages\orangecontrib\prototypes\widgets\owwebcamcapture.py", line 7, in 
import cv2
ModuleNotFoundError: No module named 'cv2'

##### Steps to reproduce the behavior

Launching Orange 3 

##### Additional info (worksheets, data, screenshots, ...)

na
![orange3_error](https://user-images.githubusercontent.com/29803730/48160919-7b58d500-e2d9-11e8-93d1-d29d769bf8f6.png)

**Comment by janezd** [comment]
As I understand, this is Anaconda Navigator's window that fetches the output of Orange? Plus, you seem to have the prototypes add-on installed?

In this case, we can't do much about it. This is how Orange reports errors while importing widgets (the only other way would be that Orange shows an annoying window itself). If widgets that should work don't its another story. If this happens, please open a separate issue reporting a problem with a particular widget.
