### ISSUE TITLE
Pythagorean Tree crashes when selecting data with categorical variables

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/orange3#3414]
##### Orange version
master

##### Expected behavior
Selecting a node in tree should always send data to output.

##### Actual behavior
For a specific case, this fails.

##### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/5758119/48931629-b53ff300-eef7-11e8-98d9-84f1f183f533.png)

In File, select a data set containing categorical variables (e.g. titanic, breast-cancer), select a tree in the random forest visualization and then try to select a node in the Pythagorean forest widget.

The widget crashes with an error like this:
```
Traceback (most recent call last):
  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/owpythagorastree.py", line 309, in commit
    data = self.tree_adapter.get_instances_in_nodes(nodes)
  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/utils/tree/skltreeadapter.py", line 260, in get_instances_in_nodes
    leaf_samples = self.get_samples_in_leaves()
  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/utils/tree/skltreeadapter.py", line 243, in get_samples_in_leaves
    leaf_indices = assign(0, items)
  File "/home/pavlin/dev/orange3/Orange/widgets/visualize/utils/tree/skltreeadapter.py", line 229, in assign
    column = self.instances.X[indices, feature_idx]
IndexError: index 10 is out of bounds for axis 1 with size 9
```

**Comment by thocevar** [comment]
There's another problem with Pythagorean Trees coming from a Random Forest (using the SklTreeAdapter). The root's tooltip for the Iris dataset shows 55/150, but there's 50 instances of each class.

**Comment by thocevar** [comment]
Mistery solved: caused by bootstrap sampling in sklearn's random forest.
