### ISSUE TITLE
MDS error on tooltip

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3#3499]
Can you take a look @VesnaT ?
MDS is probably the only visualization that works without data (using distances instead) right? So this probably can't happen in other widgets?

##### Orange version

3.19

##### Expected behavior
Tooltips don't crash Orange.

##### Actual behavior
Tooltips crash Orange.

##### Steps to reproduce the behavior
Iris into Distances (columns) into MDS. Hover over a point.

##### Additional info (worksheets, data, screenshots, ...)
```
Traceback (most recent call last):
 File "/home/lan/dev/orange3/Orange/widgets/visualize/utils/plotutils.py", line 124, in eventFilter
   return self.delegate(event)
 File "/home/lan/dev/orange3/Orange/widgets/visualize/owscatterplotgraph.py", line 1302, in help_event
   text = self.master.get_tooltip(point_data)
 File "/home/lan/dev/orange3/Orange/widgets/visualize/utils/widget.py", line 330, in get_tooltip
   for point_id in point_ids[:MAX_POINTS_IN_TOOLTIP])
 File "/home/lan/dev/orange3/Orange/widgets/visualize/utils/widget.py", line 330, in <genexpr>
   for point_id in point_ids[:MAX_POINTS_IN_TOOLTIP])
 File "/home/lan/dev/orange3/Orange/widgets/visualize/utils/widget.py", line 306, in _point_tooltip
   domain = self.data.domain
AttributeError: 'NoneType' object has no attribute 'domain'
```

**Comment by ajdapretnar** [comment]
@lanzagar I cannot replicate this. Does the issue persist?

**Comment by lanzagar** [comment]
Yes, this issue still persists.
