### ISSUE TITLE
TypeError: 'numpy.float64' object does not support item assignment

### ISSUE THREAD

**Issue by toddrme2178** [biolab/orange3#3517]
I am trying to package Orange3 for openSUSE, and I am getting the following errors:

```
======================================================================
ERROR: test_spearmanr_distance_one_example (Orange.tests.test_distances.TestSpearmanR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/tests/test_distances.py", line 533, in test_spearmanr_distance_one_example
    self.dist(self.breast[0]),
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/base.py", line 166, in __new__
    return model(e1, e2)
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/base.py", line 235, in __call__
    dist = self.compute_distances(x1, x2)
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/distance.py", line 422, in compute_distances
    rho = self.compute_correlation(x1, x2)
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/distance.py", line 444, in compute_correlation
    rho = stats.spearmanr(x1, axis=self.axis)[0]
  File "/usr/lib64/python3.6/site-packages/scipy/stats/stats.py", line 3366, in spearmanr
    rs[variable_has_nan, :] = np.nan
TypeError: 'numpy.float64' object does not support item assignment

======================================================================
ERROR: test_spearmanrabsolute_distance_one_example (Orange.tests.test_distances.TestSpearmanRAbsolute)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/tests/test_distances.py", line 638, in test_spearmanrabsolute_distance_one_example
    self.dist(self.breast[0]),
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/base.py", line 166, in __new__
    return model(e1, e2)
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/base.py", line 235, in __call__
    dist = self.compute_distances(x1, x2)
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/distance.py", line 422, in compute_distances
    rho = self.compute_correlation(x1, x2)
  File "/home/abuild/rpmbuild/BUILD/Orange3-3.19.0/Orange/distance/distance.py", line 444, in compute_correlation
    rho = stats.spearmanr(x1, axis=self.axis)[0]
  File "/usr/lib64/python3.6/site-packages/scipy/stats/stats.py", line 3366, in spearmanr
    rs[variable_has_nan, :] = np.nan
TypeError: 'numpy.float64' object does not support item assignment
```

##### Orange version
3.19.0

##### Expected behavior
Unit tests succeed

##### Actual behavior
Unit tests fail.

##### Steps to reproduce the behavior
Tests are run using the following command:

```/usr/bin/python3 setup.py test```

##### Additional info (worksheets, data, screenshots, ...)
Here are the python packages used to build Orange3:

```
python = 3.6.5
AnyQt = 0.0.10
Bottleneck = 1.2.1
Cycler = 0.10.0
SecretStorage = 2.3.1
appdirs = 1.4.3
asn1crypto = 0.24.0
base = 3.6.5
certifi = 2018.4.16
cffi = 1.11.5
chardet = 3.0.4
cryptography = 2.4.1
dbus-python = 1.2.8
decorator = 4.3.0
devel = 3.6.5
docutils = 0.14
entrypoints = 0.2.3
fastTSNE = 0.2.13
gobject = 3.30.4
idna = 2.7
joblib = 0.12.1
keyring = 15.1.0
keyrings.alt = 3.1
kiwisolver = 1.0.1
llvmlite = 0.26.0
lz4 = 2.1.1
matplotlib = 3.0.2
networkx = 2.2
numba = 0.41.0
numpy = 1.15.4
numpy-devel = 1.15.4
opengl-3.1.3b1
packaging = 17.1
pip = 18.1
psutil = 5.4.8
py = 1.7.0
pyasn1 = 0.4.4
pycparser = 2.19
pycryptodome = 3.6.6
pyparsing = 2.3.1 test5
pyqtgraph = 0.10.0
python-dateutil = 2.7.3
python-louvain = 0.13
pytz = 2018.5
qt5 = 5.11.3
requests = 2.20.1
scikit-learn = 0.20.2
scipy = 1.2.0
serverfiles = 0.2.1
setuptools = 40.6.2
sip = 4.19.13
six = 1.12.0
urllib3 = 1.24
xlrd = 1.2.0
```

**Comment by janezd** [comment]
I'm using the same version of numpy and scipy, but can't replicate this.

The tests that fail at some point call https://github.com/biolab/orange3/blob/master/Orange/distance/distance.py#L455. In it, `x2 is None` and `n == 1` (or at least should be), so the method should return `[[1]]` without calling `spearmanr`. In your case, it called `spearmanr`, which crashed. Can you help us find the problem by checking how this happened?

**Comment by janezd** [comment]
Can't replicate.
