### ISSUE TITLE
Scatter Plot crashes opon undo

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3#3600]
##### Orange version
3.20.1

##### Steps to reproduce the behavior

Construct a workflow with File and Scatter Plot, choose some data in File (say Iris). Then select both widgets and delete them (canvas is empty). Then Edit->Undo Remove. Orange crashes with:

```
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/settings.py", line 640, in _migrate_contexts
    context, context.values.pop(VERSION_KEY, 0))
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplot.py", line 505, in migrate_context
    values["attr_color"] = values["graph"]["attr_color"]
KeyError: 'attr_color'
```

**Comment by janezd** [comment]
Fixed in #3603.
