### ISSUE TITLE
DistMatrix: np.testing.assert_array_equal crashes on two different matrices

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#3658]
##### Orange version

3.21.dev

##### Expected behavior
```
data = np.random.randint(3, 5, (3, 5))
data2 = np.random.randint(3, 5, (3, 5))
np.testing.assert_array_equal(data, data2)
```

Works.

```
dm1 = Orange.misc.DistMatrix(data)
dm2 = Orange.misc.DistMatrix(data2)
np.testing.assert_array_equal(dm1, dm2)
```

Works.

##### Actual behavior
```
dm1 = Orange.misc.DistMatrix(data)
dm2 = Orange.misc.DistMatrix(data2)
np.testing.assert_array_equal(dm1, dm2)
```
Fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/o3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 896, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/miniconda3/envs/o3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 805, in assert_array_compare
    + array2string(max_abs_error))
  File "/miniconda3/envs/o3/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 687, in array2string
    if a.size == 0:
AttributeError: 'int' object has no attribute 'size'
```

##### Steps to reproduce the behavior
See above.

##### Additional info (worksheets, data, screenshots, ...)
```
err1 = abs(data - data2)
type(err1.max())

err2 = abs(dm1 - dm2)
type(err2.max())
```

**Comment by janezd** [comment]
Works for me. Can you print out `dm1` and `dm2`?

**Comment by ajdapretnar** [comment]
```
dm1
DistMatrix([[3, 3, 3, 3, 4],
            [4, 4, 4, 4, 4],
            [3, 3, 3, 4, 4]])
dm2
DistMatrix([[3, 3, 3, 4, 4],
            [4, 4, 3, 4, 3],
            [4, 4, 4, 4, 3]])
```
Tested on latest master.

**Comment by ajdapretnar** [comment]
Also using latest numpy (1.16.2).

**Comment by lanzagar** [comment]
Strange that it works for @janezd , I get the same problem as @ajdapretnar .
```
>>> type(dm1.max())
<class 'int'>
```
as opposed to
```
>>> type(data.max())
<class 'numpy.int64'>
```
