### ISSUE TITLE
Invalid Syntax when launching Orange.canvas

### ISSUE THREAD

**Issue by ferlocar** [biolab/orange3#3672]
##### Orange version
3.20.1

##### Expected behavior
I'm using Windows 10, and I'm trying to launch Orange.canvas from the command line using:

`python -m Orange.canvas`

##### Actual behavior
I'm getting this error from the command line:

Traceback (most recent call last):
  File "C:\Users\ferlo\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\ferlo\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\Orange\__init__.py", line 4, in <module>
    from Orange import data
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\Orange\data\__init__.py", line 4, in <module>
    from .variable import *
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\Orange\data\variable.py", line 12, in <module>
    from Orange.util import Registry, color_to_hex, hex_to_color, Reprable
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\Orange\util.py", line 16, in <module>
    from Orange.data.util import scale  # pylint: disable=unused-import
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\Orange\data\util.py", line 198
    return [f"{name} ({max_index})" for name in proposed]
                                  ^
SyntaxError: invalid syntax

##### Steps to reproduce the behavior
Go to the command line and type the command above.

##### Additional info (worksheets, data, screenshots, ...)

I'm using Python 3.5.5

**Comment by pavlin-policar** [comment]
You are using a version of Python that Orange no longer supports. This is written in the readme:

> Orange requires Python 3.6 or newer.
