### ISSUE TITLE
Error when importing Orange3, with Python3.5

### ISSUE THREAD

**Issue by HerharFares** [biolab/orange3#3780]
##### Orange version
Orange.3.20.1
Debian9
Python 3.5.3

##### Error
fares@fares:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Orange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Orange/__init__.py", line 4, in <module>
    from Orange import data
  File "/usr/local/lib/python3.5/dist-packages/Orange/data/__init__.py", line 4, in <module>
    from .variable import *
  File "/usr/local/lib/python3.5/dist-packages/Orange/data/variable.py", line 12, in <module>
    from Orange.util import Registry, color_to_hex, hex_to_color, Reprable
  File "/usr/local/lib/python3.5/dist-packages/Orange/util.py", line 16, in <module>
    from Orange.data.util import scale  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/Orange/data/util.py", line 189
    return [f"{name} ({max_index})" for name in proposed]
                                  ^
SyntaxError: invalid syntax

**Comment by robertcv** [comment]
Orange requires Python 3.6 or newer.
