### ISSUE TITLE
Pickle file from SC Datasets not loaded correctly

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#3799]
##### Orange version

3.21.dev

##### Expected behavior

AML-1k.pickle should load correctly. 

##### Actual behavior

AML-1k.pickle, Stimulated and resting immune cells (stimulated), ... cannot be loaded since there was a change in `variable.py` script - line 730 - one argument was removed. It seems that the pickle file will need to be generated again. Or is there any other option to fix it @JakaKokosar, @janezd?

##### Steps to reproduce the behavior

Open SC datasets widget and load `Bone marrow mononuclear cells with AML (sample)` dataset.

##### Additional info (worksheets, data, screenshots, ...)

```
Traceback (most recent call last):
  File "/Users/primoz/Documents/orange3/Orange/widgets/data/owdatasets.py", line 211, in <lambda>
    self.view.doubleClicked.connect(lambda: self.unconditional_commit())
  File "/Users/primoz/Documents/orange3/Orange/widgets/data/owdatasets.py", line 482, in commit
    self.commit_cached(di.file_path)
  File "/Users/primoz/Documents/orange3/Orange/widgets/data/owdatasets.py", line 519, in commit_cached
    self.Outputs.data.send(self.load_data(path))
  File "/Users/primoz/Desktop/repositories/orange3-single-cell/orangecontrib/single_cell/widgets/owscdatasets.py", line 39, in load_data
    data = Orange.data.Table(path)
  File "/Users/primoz/Documents/orange3/Orange/data/table.py", line 224, in __new__
    return cls.from_file(args[0])
  File "/Users/primoz/Documents/orange3/Orange/data/table.py", line 619, in from_file
    data = reader.read()
  File "/Users/primoz/Documents/orange3/Orange/data/io.py", line 949, in read
    table = pickle.load(f)
  File "/Users/primoz/Documents/orange3/Orange/data/variable.py", line 33, in make_variable
    var = cls.make(*args)
TypeError: make() takes from 2 to 4 positional arguments but 5 were given
```

**Comment by janezd** [comment]
It would be better to add a backward compatibility check.

Function `make_variable`, which fails, is used solely for unpickling. The length of `*args` before line 33 should be 5. If it's 6, we should remove the last element, which corresponds to the (now removed) `base_value`.

**Comment by PrimozGodec** [comment]
The issue was fixed as suggested in the new pull request. 

Anyway, I still suggest accepting https://github.com/biolab/datasets/pull/79 that datasets are pickled in the new format. Also, smaller datasets were changed from `pickle` to `tab.gz` since they load fast enough form `tab`, so pickling is not required.
