### ISSUE TITLE
problem with orange installler - "conda" command exited with 1. Cannot continue.

### ISSUE THREAD

**Issue by pradhyumna85** [biolab/orange3#3968]
Cannot install orange via "Orange3-3.22.0-Miniconda-x86_64.exe", after miniconda installs successfully the orange installer stops with the error ""conda" command exited with 1. Cannot continue."

I have tried custom and default installation locations with current user and all user settings, still getting same error.

The installer log is below:

`Output folder: C:\Users\Dell\AppData\Local\Temp\nsvF978.tmp\Orange-installer-data
Extract: Miniconda3-4.5.11-Windows-x86_64.exe
Installing Miniconda 4.5.11
Executing: cmd.exe /C "C:\Users\Dell\AppData\Local\Temp\nsvF978.tmp\Orange-installer-data\Miniconda3-4.5.11-Windows-x86_64.exe"  /InstallationType=CurrentUser 
Creating an new conda env in "C:\Users\Dell\AppData\Local\Orange"
Output folder: C:\Users\Dell\AppData\Local\Temp\nsvF978.tmp\Orange-installer-data\conda-pkgs
Extract: anyqt-0.0.10-py36_0.tar.bz2
Extract: asn1crypto-0.24.0-py36_0.tar.bz2
Extract: blas-1.0-mkl.tar.bz2
Extract: bottleneck-1.2.1-py36h452e1ab_1.tar.bz2
Extract: ca-certificates-2019.5.15-0.tar.bz2
Extract: certifi-2019.6.16-py36_0.tar.bz2
Extract: cffi-1.12.3-py36h7a1dbc1_0.tar.bz2
Extract: chardet-3.0.4-py36_1.tar.bz2
Extract: conda-spec.txt
Extract: cryptography-2.7-py36h7a1dbc1_0.tar.bz2
Extract: cycler-0.10.0-py36h009560c_0.tar.bz2
Extract: decorator-4.4.0-py36_1.tar.bz2
Extract: docutils-0.14-py36h6012d8f_0.tar.bz2
Extract: entrypoints-0.3-py36_0.tar.bz2
Extract: freetype-2.9.1-ha9979f8_1.tar.bz2
Extract: icc_rt-2019.0.0-h0cc432a_1.tar.bz2
Extract: icu-58.2-ha66f8fd_1.tar.bz2
Extract: idna-2.8-py36_0.tar.bz2
Extract: install.bat
Extract: intel-openmp-2019.4-245.tar.bz2
Extract: joblib-0.13.2-py36_0.tar.bz2
Extract: jpeg-9b-hb83a4c4_2.tar.bz2
Extract: keyring-18.0.0-py36_0.tar.bz2
Extract: keyrings.alt-3.1.1-py36_0.tar.bz2
Extract: kiwisolver-1.1.0-py36ha925a31_0.tar.bz2
Extract: libpng-1.6.37-h2a8f88b_0.tar.bz2
Extract: llvmlite-0.29.0-py36ha925a31_0.tar.bz2
Extract: matplotlib-3.1.0-py36hc8f65d3_0.tar.bz2
Extract: mkl-2019.4-245.tar.bz2
Extract: mkl-service-2.0.2-py36he774522_0.tar.bz2
Extract: mkl_fft-1.0.12-py36h14836fe_0.tar.bz2
Extract: mkl_random-1.0.2-py36h343c172_0.tar.bz2
Extract: networkx-2.3-py_0.tar.bz2
Extract: numba-0.44.1-py36hf9181ef_0.tar.bz2
Extract: numpy-1.16.4-py36h19fb1c0_0.tar.bz2
Extract: numpy-base-1.16.4-py36hc3f5095_0.tar.bz2
Extract: openssl-1.1.1c-he774522_1.tar.bz2
Extract: opentsne-0.3.8-py36hc8d92b1_1.tar.bz2
Extract: orange3-3.22.0-py36h6538335_0.tar.bz2
Extract: pandas-0.24.2-py36ha925a31_0.tar.bz2
Extract: pip-19.1.1-py36_0.tar.bz2
Extract: pycparser-2.19-py36_0.tar.bz2
Extract: pynndescent-0.3.0-py_0.tar.bz2
Extract: pyopenssl-19.0.0-py36_0.tar.bz2
Extract: pyparsing-2.4.0-py_0.tar.bz2
Extract: pyqt-5.9.2-py36h6538335_2.tar.bz2
Extract: pyqtgraph-0.10.0-py36h28b3542_3.tar.bz2
Extract: pysocks-1.7.0-py36_0.tar.bz2
Extract: python-3.6.8-h9f7ef89_7.tar.bz2
Extract: python-dateutil-2.8.0-py36_0.tar.bz2
Extract: python-louvain-0.13-py_0.tar.bz2
Extract: pytz-2019.1-py_0.tar.bz2
Extract: pywin32-223-py36hfa6e2cd_1.tar.bz2
Extract: qt-5.9.7-vc14h73c81de_0.tar.bz2
Extract: requests-2.22.0-py36_0.tar.bz2
Extract: scikit-learn-0.21.2-py36h6288b17_0.tar.bz2
Extract: scipy-1.2.1-py36h29ff71c_0.tar.bz2
Extract: serverfiles-0.3.0-py36_0.tar.bz2
Extract: setuptools-41.0.1-py36_0.tar.bz2
Extract: sip-4.19.8-py36h6538335_0.tar.bz2
Extract: six-1.12.0-py36_0.tar.bz2
Extract: sqlite-3.28.0-he774522_0.tar.bz2
Extract: tornado-6.0.2-py36he774522_0.tar.bz2
Extract: urllib3-1.24.2-py36_0.tar.bz2
Extract: vc-14.1-h0510ff6_4.tar.bz2
Extract: vs2015_runtime-14.15.26706-h3a45250_4.tar.bz2
Extract: wheel-0.33.4-py36_0.tar.bz2
Extract: win_inet_pton-1.1.0-py36_0.tar.bz2
Extract: wincertstore-0.2-py36h7fe50ca_0.tar.bz2
Extract: xlrd-1.2.0-py36_0.tar.bz2
Extract: xlsxwriter-1.1.8-py_0.tar.bz2
Extract: zlib-1.2.11-h62dcd97_3.tar.bz2
Output folder: C:\Users\Dell\AppData\Local\Temp\nsvF978.tmp\Orange-installer-data\conda-pkgs
Installing packages (this might take a while)
Executing: cmd.exe /c install.bat "C:\Users\Dell\AppData\Local\Orange" "C:\Users\Dell\Miniconda3\Scripts\conda.exe"
Creating a conda env in "C:\Users\Dell\AppData\Local\Orange"
Traceback (most recent call last):
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\common\path.py", line 18, in <module>
    from urllib.request import url2pathname
  File "C:\Users\Dell\Miniconda3\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\Dell\Miniconda3\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\Dell\Miniconda3\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\Dell\Miniconda3\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\Dell\Miniconda3\lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\Dell\Miniconda3\lib\email\utils.py", line 29, in <module>
    import socket
  File "C:\Users\Dell\Miniconda3\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python36.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dell\Miniconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\common\io.py", line 24, in <module>
    from .path import expand
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\common\path.py", line 21, in <module>
    from urllib import unquote, url2pathname  # NOQA
ImportError: cannot import name 'unquote' from 'urllib' (C:\Users\Dell\Miniconda3\lib\urllib\__init__.py)
Traceback (most recent call last):
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\common\path.py", line 18, in <module>
    from urllib.request import url2pathname
  File "C:\Users\Dell\Miniconda3\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\Dell\Miniconda3\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\Dell\Miniconda3\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\Dell\Miniconda3\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\Dell\Miniconda3\lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\Dell\Miniconda3\lib\email\utils.py", line 29, in <module>
    import socket
  File "C:\Users\Dell\Miniconda3\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python36.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dell\Miniconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\common\io.py", line 24, in <module>
    from .path import expand
  File "C:\Users\Dell\Miniconda3\lib\site-packages\conda\common\path.py", line 21, in <module>
    from urllib import unquote, url2pathname  # NOQA
ImportError: cannot import name 'unquote' from 'urllib' (C:\Users\Dell\Miniconda3\lib\urllib\__init__.py)
"conda" command exited with 1. Cannot continue.
`

**Comment by ales-erjavec** [comment]
Can you try running 
```
C:\Users\Dell\Miniconda3\Scripts\conda info
```
from the command line and post the output.

**Comment by janezd** [comment]
Closed due to inactivity.
