### ISSUE TITLE
Crash when opening add-ons

### ISSUE THREAD

**Issue by astaric** [biolab/orange3#4121]
**Describe the bug**
Orange shows crash dialog when opening add-ons dialog.

**To Reproduce**
Download macOs dmg, open app (without copying into applications)
Try to open add-ons dialog.

I get the following error:
```
Traceback (most recent call last):
  File "/private/var/folders/fc/4xkh9xjs3w357ph19tz4lb340000gn/T/AppTranslocation/D628FD29-E392-4590-93E3-A279AEC173BF/d/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecanvas/application/canvasmain.py", line 1687, in open_addons
    if not have_install_permissions():
  File "/private/var/folders/fc/4xkh9xjs3w357ph19tz4lb340000gn/T/AppTranslocation/D628FD29-E392-4590-93E3-A279AEC173BF/d/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecanvas/application/addons.py", line 1241, in have_install_permissions
    with open(fn, "w"):
OSError: [Errno 30] Read-only file system: '/private/var/folders/fc/4xkh9xjs3w357ph19tz4lb340000gn/T/AppTranslocation/D628FD29-E392-4590-93E3-A279AEC173BF/d/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/test_write_46293'
```

**Orange version:**
3.23.1

**Expected behavior**
OSException is caught here:
https://github.com/biolab/orange-canvas-core/blob/master/orangecanvas/application/addons.py#L1248

**Operating system:**
OSX Catalina

**Comment by lanzagar** [comment]
Fixed in https://github.com/biolab/orange-canvas-core/pull/55.
