### ISSUE TITLE
Error loading add on

### ISSUE THREAD

**Issue by TMohammed516** [biolab/orange3#4291]
When I try to load add on in ornage I get following error:

Traceback (most recent call last):
  File "/Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecanvas/application/canvasmain.py", line 1687, in open_addons
    if not have_install_permissions():
  File "/Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecanvas/application/addons.py", line 1241, in have_install_permissions
    with open(fn, "w"):
OSError: [Errno 30] Read-only file system: '/Volumes/Orange/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/test_write_21244'

**Comment by ajdapretnar** [comment]
Please follow the issue template and provide details on you OS, Orange installation, etc.

**Comment by markotoplak** [comment]
Add-ons do not work if you run Orange directly from dmg. Copy then app
anywhere (maybe to applications) and it will be fine.
