### ISSUE TITLE
Euclidian and Manhattan distances broken on master

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3#4330]
**Describe the bug**
When choosing 'Euclidian' or 'Manhattan' in the Distances widget, and connecting data into the widget, an exception is thrown.

**To Reproduce**
1. Add File, open e.g., iris.tab
2. Add Distances, pick Euclidian or Manhattan
3. Connect File to Distances

**Orange version:**
Master branch of orange3, orange-canvas-core and orange-widget-base.

**Operating system:**
OSX Mojave 10.14.3

**Additional context**
Euclidian exception:
```
Traceback (most recent call last):
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/utils/concurrent.py", line 590, in _on_task_done
    super()._on_task_done(future)
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/utils/concurrent.py", line 552, in _on_task_done
    self.on_exception(ex)
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/unsupervised/owdistances.py", line 222, in on_exception
    raise ex
  File "/Users/rafiirgolic/miniconda3/envs/orange/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/unsupervised/owdistances.py", line 51, in run
    return metric(data, **kwargs)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/distance.py", line 208, in __new__
    normalize=normalize)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/base.py", line 192, in __new__
    return model(e1, e2)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/base.py", line 315, in __call__
    return super().__call__(e1, e2)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/base.py", line 274, in __call__
    dist = self.compute_distances(x1, x2)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/distance.py", line 136, in compute_distances
    x2 is not None, callbacks.next())
  File "Orange/distance/_distance.pyx", line 92, in Orange.distance._distance.fix_euclidean_rows_normalized
TypeError: fix_euclidean_rows_normalized() takes exactly 7 positional arguments (8 given)
```
Manhattan exception:
```
Traceback (most recent call last):
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/utils/concurrent.py", line 590, in _on_task_done
    super()._on_task_done(future)
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/utils/concurrent.py", line 552, in _on_task_done
    self.on_exception(ex)
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/unsupervised/owdistances.py", line 222, in on_exception
    raise ex
  File "/Users/rafiirgolic/miniconda3/envs/orange/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rafiirgolic/orange/orange3/Orange/widgets/unsupervised/owdistances.py", line 51, in run
    return metric(data, **kwargs)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/distance.py", line 352, in __new__
    normalize=normalize)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/base.py", line 192, in __new__
    return model(e1, e2)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/base.py", line 315, in __call__
    return super().__call__(e1, e2)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/base.py", line 274, in __call__
    dist = self.compute_distances(x1, x2)
  File "/Users/rafiirgolic/orange/orange3/Orange/distance/distance.py", line 291, in compute_distances
    data1, data2, x2 is not None, callbacks.next())
  File "Orange/distance/_distance.pyx", line 186, in Orange.distance._distance.manhattan_rows_cont
TypeError: manhattan_rows_cont() takes exactly 3 positional arguments (4 given)
```

**Comment by janezd** [comment]
Try `python setup.py develop` or `pip install -e .` to recompile the changed binaries.

**Comment by irgolic** [comment]
Ah you're right, that fixed it. Thanks!
