### ISSUE TITLE
error with pip install -r requirements.txt

### ISSUE THREAD

**Issue by LJ16** [biolab/orange3#4343]
Hi
on Ubuntu 18.04, following the install process in the wiki, problem with this command

`(orange3env) user@UBUNTUPC:~/orange3$   pip install -r requirements.txt
Requirement already satisfied: pip>=9.0 in /home/user/orange3env/lib/python3.6/site-packages (from -r requirements-core.txt (line 1)) (19.3.1)
Collecting numpy>=1.16.0
  Using cached https://files.pythonhosted.org/packages/62/20/4d43e141b5bc426ba38274933ef8e76e85c7adea2c321ecf9ebf7421cedf/numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: scipy>=0.16.1 in /usr/lib/python3/dist-packages (from -r requirements-core.txt (line 3)) (0.19.1)
Collecting scikit-learn>=0.22.0
  Using cached https://files.pythonhosted.org/packages/d1/48/e9fa9e252abcd1447eff6f9257636af31758a6e46fd5ce5d3c879f6907cb/scikit_learn-0.22.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting bottleneck>=1.0.0
  Using cached https://files.pythonhosted.org/packages/62/d0/55bbb49f4fade3497de2399af70ec0a06e432c786b8623c878b11e90d456/Bottleneck-1.3.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/orange3env/bin/python3 /home/user/orange3env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp00685pba
       cwd: /tmp/pip-install-ns1xt745/bottleneck
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/user/orange3env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/user/orange3env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/user/orange3env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 85, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/user/orange3env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 76, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/orange3env/bin/python3 /home/user/orange3env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp00685pba Check the logs for full command output.
`

**Comment by LJ16** [comment]
(orange3venv) user@UBUNTUPC:~$ python -m Orange.canvas
/home/user/orange3venv/bin/python: Error while finding module specification for 'Orange.canvas' (ModuleNotFoundError: No module named 'Orange')

**Comment by LJ16** [comment]
its ok now in Anaconda envrironnement

LJ
