### ISSUE TITLE
issue while running orange-canvas

### ISSUE THREAD

**Issue by srilives** [biolab/orange3#4356]
##### Orange version

3.24.1

##### Actual behavior
Traceback (most recent call last):
  File "/root/anaconda3/bin/orange-canvas", line 7, in <module>
    from Orange.canvas.__main__ import main
  File "/root/anaconda3/lib/python3.6/site-packages/Orange/__init__.py", line 4, in <module>
    from Orange import data
  File "/root/anaconda3/lib/python3.6/site-packages/Orange/data/__init__.py", line 8, in <module>
    from .table import *
  File "/root/anaconda3/lib/python3.6/site-packages/Orange/data/table.py", line 27, in <module>
    from Orange.statistics.util import bincount, countnans, contingency, \
  File "/root/anaconda3/lib/python3.6/site-packages/Orange/statistics/util.py", line 12, in <module>
    import scipy.stats.stats
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py", line 344, in <module>
    from .stats import *
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 176, in <module>
    from . import distributions
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py", line 17, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/root/anaconda3/lib/python3.6/site-packages/scipy/_lib/_numpy_compat.py", line 10, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'

**Comment by srilives** [comment]
I am getting the above error when running on CentOS 7

**Comment by ajdapretnar** [comment]
Please describe how you installed Orange.

**Comment by ales-erjavec** [comment]
I think you have to upgrade 'scipy' in the environment (`conda update scipy`)

**Comment by janezd** [comment]
Closed due to inactivity.
