### ISSUE TITLE
Msgpack 1.0.0 breaks add-ons

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4654]
**Describe the bug**

msgpack 1.0.0 breaks add-on dialogue.

**To Reproduce**

Update to msgpack 1.0.0 and go to Options - Add-ons.

**Orange version:**
3.25.0

**Expected behavior**
Add-on dialogue works.

**Operating system:**
OSX and Win

**Additional context**
I am running the add-on fine with msgpack 0.6.1. I assume Orange (actually one of its dependencies) installs the latest version.

Stack trace:
```
Traceback (most recent call last):
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\thread.py", line 57, in run
   result = self.fn(*self.args, **self.kwargs)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\orangecanvas\application\addons.py", line 679, in <lambda>
   lambda config=config: (config, list_available_versions(config)),
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\orangecanvas\application\addons.py", line 1227, in list_available_versions
   response = session.get(PYPI_API_JSON.format(name=p))
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 543, in get
   return self.request('GET', url, **kwargs)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
   resp = self.send(prep, **send_kwargs)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
   r = adapter.send(request, **kwargs)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\cachecontrol\adapter.py", line 44, in send
   cached_response = self.controller.cached_request(request)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\cachecontrol\controller.py", line 145, in cached_request
   resp = self.serializer.loads(request, cache_data)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\cachecontrol\serialize.py", line 97, in loads
   return getattr(self, "_loads_v{}".format(ver))(request, data)
 File "C:\Users\lherman\AppData\Local\Continuum\anaconda3\lib\site-packages\cachecontrol\serialize.py", line 182, in _loads_v4
   cached = msgpack.loads(data, encoding="utf-8")
 File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'
```

**Comment by markotoplak** [comment]
Does is start working again if you install cachecontrol   >=0.12.6 ?

**Comment by ajdapretnar** [comment]
Then it works. Should we not pin it? I assume the gentleman from Discord updated Orange via Anaconda.

**Comment by markotoplak** [comment]
In the installers these versions are correct. We could update the conda-forge package to require the higher version.

**Comment by leeherman99** [comment]
Yes, I installed Orange via Anaconda.

**Comment by leeherman99** [comment]
I can confirm that updating cachecontrol to 0.12.6 fixes the problem.

**Comment by markotoplak** [comment]
Whoever now installs Orange3 into their anaconda environment will get cachecontrol 0.12.6.
