### ISSUE TITLE
Feature statistics error

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4683]
When using Feature Statistics (last master) I get the below error whenever I change the data. Nevertheless, the results displayed in the widget seem to be ok. 
```Traceback (most recent call last):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owfeaturestatistics.py", line 807, in set_data
    self.commit()
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/gui.py", line 1586, in unconditional_commit
    do_commit()
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/gui.py", line 1594, in do_commit
    commit()
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owfeaturestatistics.py", line 858, in commit
    variables = self.model.variables[self.selected_rows]
IndexError: index 7 is out of bounds for axis 0 with size 2

**Comment by janezd** [comment]
The error occurs in line 858, but in my master, owfeaturestatistics has only 856 lines. :)

I can't replicate the crash but I believe I understand the problem. The widget uses `DomainContextHandler` and `self.selected_rows` is a list of ints, so the context handler only requires `color_var` to match. That means that the context will be reused if it has that variable, but other variables may be missing (in which case the widget will semi-crash) or reordered (in which case the restored selection will be different).

Three possible fixes:

- use `PerfectDomainContextHandler`,
- store selection as a list of variables instead of list of indices,
- store selection as schema-only setting,
- implement a specific the context handler (please don't).

I vote against `PerfectDomainContextHandler`.

I suspect that we are recently seeing more context setting-related issues because we have modified the matching behaviour to prioritize recent matches (before, it computed the number of matched attributes). These are not new bugs, the changed behaviour (which is welcome) just exposes bugs that already existed. https://github.com/biolab/orange-widget-base/pull/62 could help by forcing us to thing what we actually store in settings (but wouldn't really help in this particular case).
