### ISSUE TITLE
Can't retrieve package list from Add-ons in Menu

### ISSUE THREAD

**Issue by mkosovic1981** [biolab/orange3#4688]
Orange version
Version 3.23.1

Expected behavior
Expected to populate add ons

Actual behavior
unpackb() got an unexpected keyword argument 'encoding'

Steps to reproduce the behavior
enter Orange3, click Options>Add-ons

Additional info (worksheets, data, screenshots, ...)
![error](https://user-images.githubusercontent.com/60138769/80031916-aee9e800-84ea-11ea-96e7-6999e9047408.JPG)

Details
Traceback (most recent call last):
  File "C:\Users\PenPen\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\orangecanvas\application\addons.py", line 676, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\orangecanvas\application\addons.py", line 1174, in list_available_versions
    response = session.get(PYPI_API_JSON.format(name=p))
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\cachecontrol\adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\cachecontrol\controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\cachecontrol\serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "C:\Users\PenPen\Anaconda3\lib\site-packages\cachecontrol\serialize.py", line 182, in _loads_v4
    cached = msgpack.loads(data, encoding="utf-8")
  File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
TypeError: unpackb() got an unexpected keyword argument 'encoding'

**Comment by ales-erjavec** [comment]
Can you update "cachecontrol" package in your env  to version 0.12.6 via or in Anaconda navigator or by command line
```
conda install cachecontrol==0.12.6
```

**Comment by mkosovic1981** [comment]
Hi!

The package is not available from current channels!

DETAILS:
(base) C:\Users\PenPen>conda install cachecontrol==0.12.6
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.

PackagesNotFoundError: The following packages are not available from
current channels:

  - cachecontrol==0.12.6

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by mkosovic1981** [comment]
It works! Thanks!
