### ISSUE TITLE
Box Plot: selecting subset crashes with None

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4700]
**Describe the bug**
Selection in Box Plot sometimes results in an error. I suspect sparse data.

**To Reproduce**

Steps to reproduce the behavior go **here**:
1. Corpus (bookexcerpts)
2. Bag of Words (uncheck Hide box attributes)
3. Box Plot (select variable doors and adults group).

**Orange version:**
3.26.0.dev

**Expected behavior**
No error.

**Operating system:**
OSX

**Additional context**
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owboxplot.py", line 1119, in commit
    selected = Values(self.conditions, conjunction=False)(self.dataset)
  File "/Users/ajda/orange/orange3/Orange/data/filter.py", line 220, in __call__
    return data._filter_values(self)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1183, in _filter_values
    selection = self._values_filter_to_indicator(filter)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1213, in _values_filter_to_indicator
    selection = self._filter_to_indicator(f)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1240, in _filter_to_indicator
    return self._values_filter_to_indicator(filter)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1213, in _values_filter_to_indicator
    selection = self._filter_to_indicator(f)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1285, in _filter_to_indicator
    return col_filter(col_indices[0])
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1269, in col_filter
    return self._continuous_filter_to_indicator(filter, col)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1331, in _continuous_filter_to_indicator
    return self._range_filter_to_indicator(filter, col, filter.min, filter.max)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1386, in _range_filter_to_indicator
    return (col >= fmin) * (col <= fmax)
TypeError: '>=' not supported between instances of 'float' and 'NoneType'
```

**Comment by janezd** [comment]
While working on #4663, I discovered that `OWBoxPlot.clear_scene` calls `openContext`. I wanted to write that whoever has done this needs to be properly disciplined, but then I discovered -- to my surprise -- that it actually wasn't me. (Though I still suspect it was done on my advice. Responsible programmers, for instance @VesnaT, would never do it by her own volition.)

This call may cause the problem you encountered. Even if not, this bug may go away with a fix for #4663 due to redesign of the way widget uses filters.

Please do not start working on this before we see what happens with #4663.
