### ISSUE TITLE
Heatmap error: The condensed distance matrix must contain only finite values.

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4765]
In the latest master I often get the below error with the heatmap. I also got this error when I tried to use the _zoo.tab_ with _eggs_ and _milk_ as numeric variables.
```
Error encountered in widget Heat Map:

Traceback (most recent call last):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/home/karin/Documents/git/orange3/Orange/widgets/visualize/owheatmap.py", line 558, in set_dataset
    self.update_heatmaps()
  File "/home/karin/Documents/git/orange3/Orange/widgets/visualize/owheatmap.py", line 594, in update_heatmaps
    parts = self.construct_heatmaps(self.data, self.split_by_var)
  File "/home/karin/Documents/git/orange3/Orange/widgets/visualize/owheatmap.py", line 754, in construct_heatmaps
    ordered=self.row_clustering == Clustering.OrderedClustering
  File "/home/karin/Documents/git/orange3/Orange/widgets/visualize/owheatmap.py", line 660, in cluster_rows
    matrix, linkage=hierarchical.WARD
  File "/home/karin/Documents/git/orange3/Orange/clustering/hierarchical.py", line 106, in dist_matrix_clustering
    Z = dist_matrix_linkage(matrix, linkage=linkage)
  File "/home/karin/Documents/git/orange3/Orange/clustering/hierarchical.py", line 96, in dist_matrix_linkage
    return scipy.cluster.hierarchy.linkage(distances, method=linkage)
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1061, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.

**Comment by ales-erjavec** [comment]
I cannot duplicate this.

**Comment by Hrovatin** [comment]
A while ago I have changed the clustering to be PearsonR for both Columns and Rows (instead of Euclidean in one of them), as I needed symmetrical heatmaps. Could this be the reason?

**Comment by ales-erjavec** [comment]
> A while ago I have changed the clustering to be PearsonR for both Columns and Rows (instead of Euclidean in one of them), as I needed symmetrical heatmaps. Could this be the reason?
>
>Also, this seems to depend on the data. When I selected a 'wrong' subset of columns I got the error, but not on the whole data. The data has no missing/inf values.

That could be it. PearsonR is not defined if one of the vectors has 0 standard deviation i.e. is constant.

**Comment by Hrovatin** [comment]
Yes, the use of PearsonR in rows clustering causes the problem. However, if I transpose the heatmap (so that some columns are now all 0) and cluster the columns the distance metric is PearsonR (by default), but the problem does not arise.
