### ISSUE TITLE
Select Rows matches context with missing variables without filtering them

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4781]
Latest master:
When I load a completely new data in Select Rows (e.g. data that was not put in before, so Orange does not remember the columns) I get the below error. I got the below error on the iris dataset, which has no Strain column (I have Strain column is other datasets I commonly use). The error otherwise has no effect, as everything works normally after I manually select filters. 
```
Error encountered in widget Select Rows:

Traceback (most recent call last):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owselectrows.py", line 520, in set_data
    self.unconditional_commit()
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owselectrows.py", line 574, in commit
    attr_index = domain.index(attr_name)
  File "/home/karin/Documents/git/orange3/Orange/data/domain.py", line 356, in index
    raise ValueError("'%s' is not in domain" % var)
ValueError: 'Strain' is not in domain

**Comment by janezd** [comment]
For heaven's sake. Even when I was constructing a workflow to reproduce this problem, it crashed with another.

Although Select Rows now correctly stores and retrieves variables (and I have no clue how the bug described in this issue is possible), values (say *setosa*) are stored as indices, not strings. If the order changes, it will select a wrong value. If, as in my case, the new data contains less values than the original, it will crash.

**Comment by janezd** [comment]
Friday's note: @aturanjanin, please provide instructions to reproduce this from clean settings -- thanks.

**Comment by aturanjanin** [comment]
I am not able to reproduce this in the current master. I believe it was handled with the fix in #4798.

**Comment by janezd** [comment]
@Hrovatin, can you reproduce this from clean settings?

Although everything is possible, I doubt it works due to #4798; the code that removes missing variables (https://github.com/biolab/orange3/blob/master/Orange/widgets/data/owselectrows.py#L115) was already added earlier.

**Comment by aturanjanin** [comment]
@janezd, I checked out the commit before #4798 (03cbf86eae6dc470698eab26351b752669000651) , and the error was still present. When I checked out #4798's commit, I no longer see any errors.

The steps to reproduce: 
Datasets -> Cyber Security Breaches -> SelectRows then take Iris dataset from File and connect to the same SelectRows widget.

**Comment by janezd** [comment]
Thanks! Let's assume this is OK then.
