### ISSUE TITLE
Orange crashes on opening

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4817]
Latest master on Linux:
I get this error when I try to open orange. Orange cloud-shaped starting icon is shown and then disappears, Orange itself never opens.
```
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/karin/Documents/git/orange3venv/bin/orange-canvas", line 11, in <module>
    load_entry_point('Orange3', 'gui_scripts', 'orange-canvas')()
  File "/home/karin/Documents/git/orange3/Orange/canvas/__main__.py", line 644, in main
    canvas_window.ask_load_swp_if_exists()
AttributeError: 'MainWindow' object has no attribute 'ask_load_swp_if_exists'

[1]+  Exit 1                  orange-canvas

**Comment by markotoplak** [comment]
@Hrovatin, did you do "pip install -e ." ?

**Comment by Hrovatin** [comment]
Ups, I forgot it.
