### ISSUE TITLE
Merge data falsely reporting no input

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange3#4859]
When using Merge Data on two datasets (one contains only meta variables and the other one both features and meta variables) Orange says that one of the inputs is empty, despite clearly containing the data (see image below). Interestingly, this happens either for Data or Extra Data (see two open Merge Data widgets) - the one I connect latter is treated as empty.

![Screenshot from 2020-06-17 15-40-29](https://user-images.githubusercontent.com/47607471/84905578-208c7f80-b0b1-11ea-8e00-dd56525eab3d.png)

The error I get:
```
Error encountered in widget Merge Data:

Traceback (most recent call last):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/home/karin/Documents/git/orange3venv/lib/python3.6/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 833, in process_signals_for_widget
    widget.handleNewSignals()
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owmergedata.py", line 365, in handleNewSignals
    self.extra_data and self.extra_data.domain)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/widget.py", line 987, in openContext
    self.settingsHandler.open_context(self, *a)
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owmergedata.py", line 192, in open_context
    self._encode_domain(domain2))
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/settings.py", line 816, in open_context
    self.find_or_create_context(widget, *args)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/settings.py", line 849, in find_or_create_context
    best_score, best_context)
  File "/home/karin/Documents/git/orange-widget-base/orangewidget/settings.py", line 868, in find_context
    score = self.match(context, *args)
  File "/home/karin/Documents/git/orange3/Orange/widgets/data/owmergedata.py", line 235, in match
    left, right = zip(*context.values["attr_pairs"])
KeyError: 'attr_pairs'

```
This does not happen in other parts of the workflow when I perform the Merge on data of similar types. It also happens on zoo data: For Data I use all data and for Extra data two random rows from a Table, matching by name.
I used the latest version of Orange and widget base.

**Comment by janezd** [comment]
If Orange had bounties for discovered bug, you'd be rich. You've written a significant proortion of issues.

I can't replicate this one, though. It seems you somehow got a context without `attr_pairs` (so it doesn't matter what data you have, if fails when trying to match the context to the data). One way to get to this would be to use messed-up non-released versions of widget.

Could you find (at around line 678)

```python
        if not version:
            operations = ("augment", "merge", "combine")
            oper = operations[settings["merging"]]
            settings["attr_pairs"] = (
                True, True,
                [(mig_value(settings[f"attr_{oper}_data"]),
                  mig_value(settings[f"attr_{oper}_extra"]))])
            for oper in operations:
                del settings[f"attr_{oper}_data"]
                del settings[f"attr_{oper}_extra"]
```

 and add

```python
        elif "attr_pairs" not in settings:
            from orangewidget.settings import IncompatibleContext
            raise IncompatibleContext
```

Can you replicate the bug after this?

**Comment by Hrovatin** [comment]
Since I have reported the bug I have also updated the Orange. I do not get this even without the code change.
