### ISSUE TITLE
Heat Map: fails when clustering topics

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#4877]
**Bug reports that do not sufficiently describe a bug are not helpful and will most likely be ignored.**

- [ ] **A clear and concise description.** "*I'm getting an error when I open a tree viewer*" is far from enough (what kind of error? what kind of data you give it?). "*I'm getting an error*" is even worse.

Heat Map throws an error when trying to cluster data from topic modeling. I don't see how these data is different from a standard Orange table.

The error:
```
---------------------------- ValueError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 313, in _
    self.set_row_clustering(cb.itemData(idx, ClusteringRole))
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 528, in set_row_clustering
    self.__update_row_clustering()
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 1091, in __update_row_clustering
    self.update_heatmaps()
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 726, in update_heatmaps
    parts = self.construct_heatmaps(self.data, self.split_by_var, self.split_columns_var)
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 901, in construct_heatmaps
    parts = self.cluster_rows(
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 798, in cluster_rows
    matrix = Orange.distance.Euclidean(subset)
  File "/Users/ajda/orange/orange3/Orange/distance/distance.py", line 207, in __new__
    return super().__new__(cls, e1, e2, axis, impute, callback,
  File "/Users/ajda/orange/orange3/Orange/distance/base.py", line 192, in __new__
    return model(e1, e2)
  File "/Users/ajda/orange/orange3/Orange/distance/base.py", line 315, in __call__
    return super().__call__(e1, e2)
  File "/Users/ajda/orange/orange3/Orange/distance/base.py", line 274, in __call__
    dist = self.compute_distances(x1, x2)
  File "/Users/ajda/orange/orange3/Orange/distance/distance.py", line 134, in compute_distances
    fixer(distances, data1, data2,
  File "Orange/distance/_distance.pyx", line 67, in Orange.distance._distance.fix_euclidean_rows
    def fix_euclidean_rows(
ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'
-------------------------------------------------------------------------------
```

- [ ] **How to reproduce the problem.** Upload a zip with a workflow and data, or describe the steps (open this widget, click there, then add this ...)

Corpus - Topic Modeling - Heat Map (cluster rows)

- [ ] **Which version of Orange are you using? How did you install it?**

master

- [ ] **What is your operating system?**

OSX

**Comment by ajdapretnar** [comment]
Could be the data from topic modeling has dtype=float32 and Orange expects dtype=float64?
