### ISSUE TITLE
AttributeError: 'CanvasApplication' object has no attribute 'styleHints'

### ISSUE THREAD

**Issue by chopeen** [biolab/orange3#5034]
- [x] **What's wrong?**

The application does not start. When I execute `python -m Orange.canvas`, it fails with error:

```
Traceback (most recent call last):
  File "/home/users/[user]/apps/miniconda3/envs/orange-env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/users/[user]/apps/miniconda3/envs/orange-env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/users/[user]/apps/miniconda3/envs/orange-env/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 705, in <module>
    sys.exit(main())
  File "/home/users/[user]/apps/miniconda3/envs/orange-env/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 455, in main
    app = CanvasApplication(qt_argv)
  File "/home/users/[user]/apps/miniconda3/envs/orange-env/lib/python3.8/site-packages/orangecanvas/application/application.py", line 104, in __init__
    sh = self.styleHints()
AttributeError: 'CanvasApplication' object has no attribute 'styleHints'
```

Running `python -m Orange.canvas --help` returns the expected help information, so the issue may be related to GUI only.

- [x] **How can we reproduce the problem?** 

The application does not start, so I have no .ows file to upload.

- [x] **Which version of Orange are you using? How did you install Orange?**

3.26.0

I installed Orange3 using the following `environment.yml` file:

```
name: orange-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - conda-forge::orange3
  - defaults::pyqt=5
  - defaults::qt
```

- [x] **What is your operating system?**

Ubuntu 18.04

**Comment by chopeen** [comment]
Installing `PyQt5` and `PyQtWebEngine` solved the issue, so my final `environment.yml` is:

```
name: orange-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - conda-forge::orange3
  - defaults::pyqt=5
  - defaults::qt
  - pip:
    - PyQt5
    - PyQtWebEngine
```
