### ISSUE TITLE
`available_font_families` crashes if default font is missing

### ISSUE THREAD

**Issue by leesnagjun** [biolab/orange3#5036]
- [ ] **What's wrong?**

![캡처](https://user-images.githubusercontent.com/42027890/96339589-a7d61800-10d0-11eb-99cc-355e3d774de1.PNG)

- [ ] **How can we reproduce the problem?** 

- [ ] **Which version of Orange are you using? How did you install Orange?**

- [ ] **What is your operating system?**

**Comment by leesnagjun** [comment]
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 231, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\owscatterplot.py", line 269, in __init__
    super().__init__()
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\utils\widget.py", line 405, in __init__
    self.setup_gui()
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\utils\widget.py", line 410, in setup_gui
    self._add_graph()
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\utils\widget.py", line 417, in _add_graph
    self.graph = self.GRAPH_CLASS(self, box)
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\owscatterplot.py", line 122, in __init__
    super().__init__(scatter_widget, parent)
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\owscatterplotgraph.py", line 591, in __init__
    self.parameter_setter = ScatterBaseParameterSetter(self)
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\owscatterplotgraph.py", line 369, in __init__
    super().__init__()
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\utils\customizableplot.py", line 266, in __init__
    Updater.FONT_FAMILY_LABEL: (available_font_families(), QFont().family()),
  File "C:\Users\user\Downloads\Orange3-3.27.0\Orange\lib\site-packages\Orange\widgets\visualize\utils\customizableplot.py", line 31, in available_font_families
    default = fonts.pop(fonts.index(default_font_family()))
ValueError: 'Gulim' is not in list

**Comment by irgolic** [comment]
Please fill out the issue template.

**Comment by janezd** [comment]
To my understanding, Gulim is the default font in Korean Windows (https://forum.qt.io/topic/14394/solved-qt-text-rendering-issue-on-windows-xp-korean-version). @leesnagjun, can you confirm?

Judging from the traceback, Qt apparently doesn't guarantee that the default font family (as returned by `QFont().family()`) actually exists in the font database (`QFontDatabase().families()`).

**Comment by goodwebb** [comment]
I have the same problem. The problem happened  in  version 3.27 ,   and 3.26 is no problem. My computer  windows system is chinese .
![image](https://user-images.githubusercontent.com/26482985/96663677-b8fa7f80-1383-11eb-9d4c-b8bfa2859969.png)
 PMingLiU is chinese  Font. My windows system  display "新細明體" Font.
![image](https://user-images.githubusercontent.com/26482985/96663974-64a3cf80-1384-11eb-8bb9-0e62bbefdde1.png)
At present, I couldn't solve to ,too.
