### ISSUE TITLE
Unable to Load 3.27.1

### ISSUE THREAD

**Issue by bobhuff0** [biolab/orange3#5090]
Hi,

When I attempt to start Orange 3.27.1, I receive the following error:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\site-packages\Orange\__init__.py", line 4, in <module>
    from Orange import data
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\site-packages\Orange\data\__init__.py", line 8, in <module>
    from .table import *
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\site-packages\Orange\data\table.py", line 29, in <module>
    from Orange.statistics.util import bincount, countnans, contingency, \
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\site-packages\Orange\statistics\util.py", line 15, in <module>
    from sklearn.utils.sparsefuncs import mean_variance_axis
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\site-packages\sklearn\__init__.py", line 81, in <module>
    from .utils._show_versions import show_versions
  File "C:\Users\Davout\AppData\Local\Programs\Orange\lib\site-packages\sklearn\utils\_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: DLL load failed: %1 is not a valid Win32 application.

C:\Users\Davout\AppData\Local\Programs\Orange>
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
- [ ] **What's your environment?**

- Operating system: Windows 10 20H2 OS Build 19042.630
- Orange version: 3.27.1
- How you installed Orange: EXE

Any suggestions?

Thank you,
Bob

**Comment by thocevar** [comment]
I just managed to install Orange 3.27.1 on a clean Windows 10 machine with the provided installer without any issues.

There seems to be a problem with the scikit-learn package that uses OpenMP. Searching for similar problems produced two possible solutions.
- The first is to install the latest Microsoft Visual C++ Redistributable (https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), which would hopefully fix the problematic openmp DLL. 
- Another mentioned solution is to downgrade the scikit-learn library to version 0.21.3. Try running `pip install scikit-learn==0.21.3` from command line in your "AppData\Local\Programs\Orange\Scripts" folder.

**Comment by bobhuff0** [comment]
Thank you, Tomaz. Appreciate the help and insights.
