### ISSUE TITLE
I could not open Orange! 

### ISSUE THREAD

**Issue by Shaimaai** [biolab/orange3#5158]
- [ ] **What's wrong?**
I installed Orange3, and it was working very well but then when I try to open it again, I could not. It opens for a few seconds then it closes immediately. I re-downloaded it twice, but I had the same issue. 

<img width="295" alt="Screen Shot 2021-01-05 at 8 17 07 AM" src="https://user-images.githubusercontent.com/75612098/103605915-91509780-4f2e-11eb-8823-e585475ec862.png">
 

- Operating system: macOS Catalina, version 10.15
- Orange version: 3.27
- How you installed Orange: from the website

**Comment by mstajdohar** [comment]
I get the same issue. No output in the terminal...

![Screenshot 2021-01-08 at 11 37 32](https://user-images.githubusercontent.com/1026716/104005812-f5c95c00-51a5-11eb-90e0-fde777ddf58e.png)

Installing the Orange manually via pip works, however.

**Comment by markotoplak** [comment]
We tried debugging @mstajdohar's problem with @JakaKokosar. We discovered that @mstajdohar `Orange3.app/Contents/MacOS/pip freeze` shows pyqt5==5.12.3 installed, even though his downloaded dmg has the same MD5 sum as mine and @JakaKokosar's. Jaka and me get `pyqt5==5.12.2`, which is the one that works on Big Sur.

When @mstajdohar manually installed 5.12.2 into the app, Orange started working normally.

**Comment by markotoplak** [comment]
@Shaimaai, could you please open a terminal and run the following commands:
- `~/Desktop/Orange3.app/Contents/MacOS/pip freeze`
- `~/Desktop/Orange3.app/Contents/MacOS/Orange -l4 --force-discovery`

Copy and paste the output here, please.

**Comment by markotoplak** [comment]
@mstajdohar's issue was that he already downloaded a package some months ago and was using the old (not the latest) package for installation.

**Comment by Shaimaai** [comment]
> * ~/Desktop/Orange3.app/Contents/MacOS/pip freeze

**When I run the first commands, I got this output:**

AnyQt==0.0.11
appnope==0.1.0
baycomp==1.0.2
Bottleneck==1.3.2
CacheControl==0.12.6
certifi==2020.11.8
chardet==3.0.4
commonmark==0.9.1
cycler==0.10.0
decorator==4.4.2
dictdiffer==0.8.1
docutils==0.16
et-xmlfile==1.0.1
h11==0.9.0
httpcore==0.10.2
httpx==0.14.3
idna==2.10
jdcal==1.4.1
joblib==0.11
keyring==10.3.1
keyrings.alt==2.2
kiwisolver==1.3.1
lockfile==0.12.2
matplotlib==3.3.3
msgpack==1.0.0
networkx==2.5
numpy==1.19.4
openpyxl==3.0.5
openTSNE==0.4.4
orange-canvas-core==0.1.18
orange-widget-base==4.9.0
Orange3==3.27.1
pandas==1.1.4
Pillow==8.0.1
pyparsing==2.4.7
PyQt5==5.12.2
PyQt5-sip==12.8.1
pyqtgraph==0.11.0
PyQtWebEngine==5.12.1
python-dateutil==2.8.1
python-louvain==0.14
pytz==2020.4
PyYAML==5.3.1
requests==2.25.0
rfc3986==1.4.0
scikit-learn==0.23.2
scipy==1.5.4
serverfiles==0.3.0
six==1.15.0
sniffio==1.2.0
threadpoolctl==2.1.0
urllib3==1.26.2
xlrd==1.2.0
XlsxWriter==1.3.7

**And for the secoed command, the output was:**

INFO:__main__:Starting 'Orange Canvas' application.
DEBUG:__main__:Starting CanvasApplicaiton with argv = ['/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/canvas/__main__.py'].
INFO:orangecanvas.document.usagestatistics:Enabling usage statistics tracking
INFO:__main__:Adding search path 'orange' for prefix, 'canvas_icons'
INFO:orangecanvas.application.canvasmain:Setting up Canvas main window.
DEBUG:orangecanvas.config:Activating configuration for <Orange.canvas.config.Config object at 0x12ba66c10>
Traceback (most recent call last):
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/canvas/__main__.py", line 701, in <module>
    sys.exit(main())
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/canvas/__main__.py", line 563, in main
    canvas_window = MainWindow()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Orange/canvas/mainwindow.py", line 107, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/mainwindow.py", line 54, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/application/canvasmain.py", line 189, in __init__
    self.setup_ui()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/application/canvasmain.py", line 222, in setup_ui
    self.scheme_widget = SchemeEditWidget()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/document/schemeedit.py", line 234, in __init__
    self.__suggestions = Suggestions()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/document/suggestions.py", line 112, in __init__
    Suggestions.instance = Suggestions.__Suggestions()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/document/suggestions.py", line 27, in __init__
    if not self.load_link_frequency():
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/document/suggestions.py", line 36, in load_link_frequency
    imported_freq = pickle.load(f)
EOFError: Ran out of input
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 2033, in shutdown
    h.flush()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
  File "/Users/myuser/Desktop/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/application/outputview.py", line 296, in flush
    self.flushed.emit()
AttributeError: 'TextStream' does not have a signal with the signature flushed()

**Comment by Shaimaai** [comment]
> @mstajdohar's issue was that he already downloaded a package some months ago and was using the old (not the latest) package for installation.

any update, please?

**Comment by markotoplak** [comment]
@Shaimaai, In your case a settings file seems to be corrupted. 

Could you open a terminal and use:
rm "/Users/myuser/Library/Application Support/Orange/3.27.1/widget-use-frequency.pickle"

And then try to run again.

If that does not work, delete the whole /Users/myuser/Library/Application Support/Orange folder.
