### ISSUE TITLE
Impossible to put decimals in Random data widget from the Educational add-on

### ISSUE THREAD

**Issue by bughunter12345** [biolab/orange3#5199]
- [ ] **What's wrong?**

In the Random data add-on from the Educational add-on, it is not possible to assign a decimal value to any distribution parameter. Moreover, after having attempted to set a decimal value to a random distribution, the following permanent error occurs: 
```
Traceback (most recent call last):
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 231, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 415, in __init__
    self.unpack_editor_settings()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 483, in unpack_editor_settings
    self.add_editor(editor)
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 446, in add_editor
    self.generate()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 462, in generate
    for e, attr in zip(editors, attrs))
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 462, in <genexpr>
    for e, attr in zip(editors, attrs))
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 150, in generate_data
    parameters = self.get_parameters()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 131, in get_parameters
    return {name: self.get(name) for name in self.edits}
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 131, in <dictcomp>
    return {name: self.get(name) for name in self.edits}
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 128, in get
    return edit.convert(edit.text())
ValueError: could not convert string to float: '2,'

````

- [ ] **How can we reproduce the problem?** 

1 - Install the Educational add-on
2 - Drag the Random data widget in the workspace
3 - Open Random data and try to set the mean or the standard deviation  of the normal distribution panel to a decimal value, for example 0.3.
4 - The change is not accepted
5 - Curiously, if you take an already assigned decimal value (for example, the probability of succes from the binomial distribution ) and change only the decimal part without altering the integer part, it will work, as long as you don't delete the comma.
6 - Afterward, this permanent bug occurs, and stay even if you unload and reload the add-on :

```
Traceback (most recent call last):
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 231, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 415, in __init__
    self.unpack_editor_settings()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 483, in unpack_editor_settings
    self.add_editor(editor)
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 446, in add_editor
    self.generate()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 462, in generate
    for e, attr in zip(editors, attrs))
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 462, in <genexpr>
    for e, attr in zip(editors, attrs))
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 150, in generate_data
    parameters = self.get_parameters()
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 131, in get_parameters
    return {name: self.get(name) for name in self.edits}
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 131, in <dictcomp>
    return {name: self.get(name) for name in self.edits}
  File "C:\Users\singularity\Downloads\Orange3-3.27.1\Orange\lib\site-packages\orangecontrib\educational\widgets\owrandomdata.py", line 128, in get
    return edit.convert(edit.text())
ValueError: could not convert string to float: '2,'
````

- [ ] **What's your environment?**

- Operating system: Windows 10
- Orange version: 3.37.1
- How you installed Orange: portable version without installation (but the same bug occurs with the embedded version from the anaconda distribution)

**Comment by janezd** [comment]
Thanks for this detailed report. One more thing: what is your system's default decimal separator? Dot or comma?

Interestingly, I used this a few days ago, and it worked for me. With commas, even.

**Comment by bughunter12345** [comment]
Hello,

My system's defaut decimal is the comma, but I tried both comma and dot,
and neither works...

Le mar. 19 janv. 2021 à 14:36, Janez Demšar <notifications@github.com> a
écrit :

**Comment by ajdapretnar** [comment]
I can confirm the issue. US locale.

**Comment by ajdapretnar** [comment]
Also, I'm moving this where it belongs.
