### ISSUE TITLE
t-SNE: crash with typed settings

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5340]
- [ ] **What's wrong?**

Error Wars: The Settings Strike Back. 🌟 
t-SNE crashes when changing a data set.
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 1010, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 1048, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 679, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/sql.py", line 31, in new_f
    return f(widget, data, *args, **kwargs)
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/utils/widget.py", line 458, in set_data
    self.openContext(self.data)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/widget.py", line 1115, in openContext
    self.settingsHandler.open_context(self, *a)
  File "/Users/ajda/orange/orange3/Orange/widgets/settings.py", line 125, in open_context
    super().open_context(widget, domain, *self.encode_domain(domain))
  File "/Users/ajda/orange/orange-widget-base/orangewidget/settings.py", line 1168, in open_context
    self.find_or_create_context(widget, *args)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/settings.py", line 1195, in find_or_create_context
    best_context, best_score = self.find_context(
  File "/Users/ajda/orange/orange-widget-base/orangewidget/settings.py", line 1225, in find_context
    score = self.match(context, *args)
  File "/Users/ajda/orange/orange3/Orange/widgets/settings.py", line 229, in match
    self.match_value(setting, value, attrs, metas))
  File "/Users/ajda/orange/orange3/Orange/widgets/settings.py", line 254, in match_value
    if value[1] < 0:
TypeError: 'int' object is not subscriptable
```

- [ ] **How can we reproduce the problem?** 

File (iris) - t-SNE. File (change to titanic).

- [ ] **What's your environment?**

- Operating system: OSX
- Orange version: 3.29.dev
- How you installed Orange: git

**Comment by janezd** [comment]
I can't replicate this. I really hope it's not related to stored settings. Can you send me a workflow?

**Comment by janezd** [comment]
Doesn't matter, I reverted the PR that changes settings. But let's keep this open, so we know we have to test it when I retry.
