### ISSUE TITLE
launching errors

### ISSUE THREAD

**Issue by leslielee619** [biolab/orange3#5396]
i installed orange3 in anaconda(GUI version).
when i launch the orange3, the errors happen.

 ---

ERROR:Orange.canvas.__main__:Failed to pull notification feed
Traceback (most recent call last):
File "F:\software\anaconda\lib\urllib\request.py", line 1350, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "F:\software\anaconda\lib\http\client.py", line 1255, in request
self._send_request(method, url, body, headers, encode_chunked)
File "F:\software\anaconda\lib\http\client.py", line 1301, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "F:\software\anaconda\lib\http\client.py", line 1250, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "F:\software\anaconda\lib\http\client.py", line 1010, in _send_output
self.send(msg)
File "F:\software\anaconda\lib\http\client.py", line 950, in send
self.connect()
File "F:\software\anaconda\lib\http\client.py", line 1417, in connect
super().connect()
File "F:\software\anaconda\lib\http\client.py", line 921, in connect
self.sock = self._create_connection(
File "F:\software\anaconda\lib\socket.py", line 787, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "F:\software\anaconda\lib\socket.py", line 918, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "F:\software\anaconda\lib\site-packages\Orange\canvas\__main__.py", line 238, in run
contents = urlopen(request, timeout=10).read().decode()
File "F:\software\anaconda\lib\urllib\request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "F:\software\anaconda\lib\urllib\request.py", line 531, in open
response = meth(req, response)
File "F:\software\anaconda\lib\urllib\request.py", line 640, in http_response
response = self.parent.error(
File "F:\software\anaconda\lib\urllib\request.py", line 563, in error
result = self._call_chain(*args)
File "F:\software\anaconda\lib\urllib\request.py", line 502, in _call_chain
result = func(*args)
File "F:\software\anaconda\lib\urllib\request.py", line 755, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "F:\software\anaconda\lib\urllib\request.py", line 525, in open
response = self._open(req, data)
File "F:\software\anaconda\lib\urllib\request.py", line 542, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "F:\software\anaconda\lib\urllib\request.py", line 502, in _call_chain
result = func(*args)
File "F:\software\anaconda\lib\urllib\request.py", line 1393, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "F:\software\anaconda\lib\urllib\request.py", line 1353, in do_open
raise URLError(err)
urllib.error.URLError: 

---

of course，even error happen,  orange3 can well run. but i think this error still need to solve.

**Comment by janezd** [comment]
Thanks for reporting this. I can replicate it by running Orange without internet.

The error is caused by `log.exception('Failed to pull notification feed')` in the exception handler triggered by `URLError`. If I change it to call `log.error` instead, it works.

This is out of my depth. What I noticed is that `log.exception` can only be called from exception handler; it is called from a handler, but there are threads involved and I don't know which thread handles the exception. Could this be the problem?

@irgolic, can we just call to `log.error` to resolve this?

**Comment by janezd** [comment]
Hm, I think you're right. Still, I'd change it to `error`, to make it shorter. This output is not very useful to anybody anyway.

**Comment by irgolic** [comment]
I'll change it to `warning`.
