### ISSUE TITLE
Cannot save tSNE output table as a pickle

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3#5421]
- [X] **What's wrong?**

When I want to save the table from the tSNE widget as pickle with Save Data widget I get the following error >
```
Traceback (most recent call last):
  File "/Users/primoz/Documents/orange3/Orange/widgets/utils/save/owsavebase.py", line 208, in save_file
    self._try_save()
  File "/Users/primoz/Documents/orange3/Orange/widgets/utils/save/owsavebase.py", line 219, in _try_save
    self.do_save()
  File "/Users/primoz/Documents/orange3/Orange/widgets/data/owsave.py", line 76, in do_save
    self.writer.write(self.filename, self.data, self.add_type_annotations)
  File "/Users/primoz/Documents/orange3/Orange/data/io_base.py", line 578, in write
    return cls.write_file(filename, data)
  File "/Users/primoz/Documents/orange3/Orange/data/io.py", line 222, in write_file
    pickle.dump(data, f, protocol=PICKLE_PROTOCOL)
TypeError: cannot pickle 'annoy.Annoy' object
```

I think that Annoy object that cannot be pickled is a part of `compute_value` for the `tSNE x` and `tSNE y` variable.

- [X] **How can we reproduce the problem?** 

File -> tSNE -> Save Data (try to save as pickle)

- [X] **What's your environment?**

- Operating system: macOS 10.15.7
- Orange version: 3.29.dev0
- How you installed Orange: `pip install -e .`

**Comment by PrimozGodec** [comment]
With the openTSNE version, 0.6.0 pickling is handled for Annoy objects and Orange does not crash anymore. Here is the PR that limits the version to >=0.6.0. This implementation is temporary since Annoy object is saved to separate files in the working directory and is not friendly for sending the data. This is why I would keep this issue open until it is better handled by openTSNE.
