### ISSUE TITLE
Import CSV: can not convert "57,8" to float.

### ISSUE THREAD

**Issue by kasac** [biolab/orange3#5449]
- [ ] **What's wrong?**

```

 Unexpected error
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1141, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/data/owcsvimport.py", line 1203, in __handle_result
    df = f.result()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/utils/concurrent.py", line 175, in run
    result = func(*args, **kwargs)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/data/owcsvimport.py", line 1680, in wrapper
    return f(*args, **kwargs)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/data/owcsvimport.py", line 1561, in load_csv
    df = pd.read_csv(
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1073, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1147, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: '57,8'


```

- [ ] **How can we reproduce the problem?** 

[ows and data.zip](https://github.com/biolab/orange3/files/6525996/ows.and.data.zip)

Bug appears when attempting to import the file. 
- delimiter semicolon
- decimals comma
- First variable datetime
- Last variable string
- All other variables numeric.

- [ ] **What's your environment?**

- Operating system:
most recent macOS Catalina
- Orange version:
3.28 
- How you installed Orange:
latest dmg package from your website

**Comment by ales-erjavec** [comment]
The error is confusing, but is caused by the last row in the file which contains the header again:
```
$ tail -n 3 LOG00292.TXT
15.05.2021 15:02:31,8;28,0;0;25,6;0;5,4;9,9;0;4,5;11,5;11,4;22,8;
15.05.2021 15:02:31,9;27,8;0;25,6;0;5,4;9,3;0;4,4;11,3;10,9;23,0;
BBBBBBBEBBBr Date;"All 3D";"16,7Hz 3D";"50/60Hz 3D";"100/120Hz 3D";"150/180Hz 3D";"R<2kHz 3D";">2kHz 3D";"All CH4";"All X";"All Y";"All Z";"User" NFA1000 SN 5ddff30 3530424d 51045626 e085 08/01/2019 14/37 hp 3 sdc 0 
```
If the line is removed
```
head -n 830009 LOG00292.TXT > LOG00292-1.TXT
```
the import works

The error is from pandas fallback path after having failed to convert the second column (failing on "All 3D") tries to [cast the column data](https://github.com/pandas-dev/pandas/blob/v1.2.4/pandas/_libs/parsers.pyx#L1056) to float, but it does so without taking decimal separator into account so it fails at converting "57,8".
