### ISSUE TITLE
Add-on "Text" not working on v 3.28

### ISSUE THREAD

**Issue by ffangelino** [biolab/orange3#5458]
- [ ] **What's wrong?**

The text mining add-on "Text" is not working nor even showing as installed, on v 3.28.
I already sent you this information through the contact form on Orange website.

- [ ] **How can we reproduce the problem?** 

- [ ] **What's your environment?**

- Operating system: Win 10
- Orange version: 3.28
- How you installed Orange: uninstall and reinstall new version

**Comment by PrimozGodec** [comment]
Thank you for reporting the issue. Since I cannot reproduce the error I would ask if you can give us one more piece of information. 
Please open Orange and when the main window opens open log (View > Log). Can you please paste the content of the log here? I think there should be an error message that tells what is wrong.

**Comment by ffangelino** [comment]
Hello,

Here is the Log content:

2021-05-27 08:06:42,398:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterplotgraph.py'.
2021-05-27 08:06:42,399:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterplotgraph_obsolete.py'.
2021-05-27 08:06:42,438:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeviewer2d.py'.
2021-05-27 08:06:42,457:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagorastreeviewer.py'.
2021-05-27 08:06:42,651:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthandlers.py'.
2021-05-27 08:06:42,698:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
2021-05-27 08:06:46,322:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\_owmodel.py'.
2021-05-27 08:06:46,322:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\_rangeslider.py'.
2021-05-27 08:06:46,604:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.timeseries.widgets.owyahoofinance'.
Traceback (most recent call last):
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 260, in iter_widget_descriptions
module = asmodule(name)
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 503, in asmodule
return __import__(module, fromlist=[""])
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owyahoofinance.py", line 10, in <module>
from orangecontrib.timeseries.datasources import finance_data
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\timeseries\datasources.py", line 4, in <module>
import pandas_datareader.data as web
ModuleNotFoundError: No module named 'pandas_datareader'
2021-05-27 08:06:46,635:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\timeseries\\widgets\\utils.py'.
2021-05-27 08:06:46,775:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\_textable\\widgets\\TextableUtils.py'.
2021-05-27 08:06:54,852:ERROR:orangecanvas.registry.discovery: An exception occurred while loading entry point 'Text Mining = orangecontrib.text.widgets'
Traceback (most recent call last):
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 88, in run
point = entry_point.resolve()
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\pkg_resources\__init__.py", line 2478, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\text\__init__.py", line 6, in <module>
from .corpus import Corpus
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\text\corpus.py", line 11, in <module>
from gensim import corpora
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\gensim\__init__.py", line 11, in <module>
from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils # noqa:F401
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\gensim\parsing\__init__.py", line 4, in <module>
from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2, # noqa:F401
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\gensim\parsing\preprocessing.py", line 26, in <module>
from gensim import utils
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\gensim\utils.py", line 62, in <module>
default_prng = np.random.default_rng()
AttributeError: module 'numpy.random' has no attribute 'default_rng'
2021-05-27 08:06:54,977:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\single_cell\\widgets\\contingency_table.py'.
2021-05-27 08:06:54,977:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\single_cell\\widgets\\load_data.py'.
2021-05-27 08:06:55,023:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\single_cell\\widgets\\owloaddata.py'.
2021-05-27 08:06:55,164:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\network\\widgets\\graphview.py'.
2021-05-27 08:06:55,289:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\geo\\widgets\\plotutils.py'.
2021-05-27 08:06:55,320:INFO:orangecanvas.registry.discovery: Ignoring 'C:\\Users\\Utilizador\\AppData\\Local\\Programs\\Orange\\lib\\site-packages\\orangecontrib\\explain\\widgets\\owexplainfeaturebase.py'.
2021-05-27 08:06:55,555:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.bioinformatics.widgets.OWGenialisExpressions'.
Traceback (most recent call last):
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 260, in iter_widget_descriptions
module = asmodule(name)
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 503, in asmodule
return __import__(module, fromlist=[""])
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\widgets\OWGenialisExpressions.py", line 8, in <module>
from resdk.resources.data import Data
ModuleNotFoundError: No module named 'resdk'
2021-05-27 08:06:55,945:INFO:orangecanvas.registry.discovery: Could not import 'orangecontrib.bioinformatics.widgets.OWdictyExpress'.
Traceback (most recent call last):
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 260, in iter_widget_descriptions
module = asmodule(name)
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\registry\discovery.py", line 503, in asmodule
return __import__(module, fromlist=[""])
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\widgets\OWdictyExpress.py", line 18, in <module>
from orangecontrib.bioinformatics import resolwe
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\resolwe\__init__.py", line 4, in <module>
from .resapi import ResolweAPI
File "C:\Users\Utilizador\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\bioinformatics\resolwe\resapi.py", line 8, in <module>
from resdk import Resolwe
ModuleNotFoundError: No module named 'resdk'


I also add a couple more pictures of the widgets window (capture 1) where you can see that the “Text” widget does not show, and also the installer window (capture 2) where the “Text” widget appears as installed but …
Hope you can fix this asap.
Thank you.

All the best,
Fernando Angelino

**Comment by PrimozGodec** [comment]
@ffangelino thank you for your report. It was really helpful. :)

We found out that one of the packages which we are using in the text-addon has the wrong requirement specifications. We proposed a new release of Orange3-text which fixes the package's shortcoming. Uninstalling and installing the Text add-on should resolve the issue now. Please confirm whether it is working.

**Comment by ffangelino** [comment]
Well done - everything went back to normal – thank you!
