### ISSUE TITLE
Orange 3.29.3 Cannot Load Data

### ISSUE THREAD

**Issue by liuhuiye** [biolab/orange3#5483]
Traceback (most recent call last):
  File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 403, in create_widget_instance
    item.widget = widget = klass.__new__(
  File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\widget.py", line 340, in __new__
    self.update_summaries()
  File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\signals.py", line 515, in update_summaries
    self._update_summary(self.input_summaries)
TypeError: _update_summary() takes 1 positional argument but 2 were given

**Comment by markotoplak** [comment]
Thanks! I do not see the full traceback though. Which widget did you try to add?

**Comment by liuhuiye** [comment]
Thanks for your reply!
I try to add 'Load Data' in 'Single Cell' Add-on when its reports the error I posted.


Exception:
TypeError: _update_summary() takes 1 positional argument but 2 were given
Module:
orangewidget.utils.signals:515
Widget Name:
Load Data
Widget Module:
orangecontrib.single_cell.widgets.owmultisample:340
Widget Scheme:
<?xml version='1.0' encoding='utf-8'?&gt; <scheme version="2.0" title="" description=""&gt; <nodes&gt; <node id="0" name="Load Data" qualified_name="orangecontrib.single_cell.widgets.owmultisample.OWMultiSample" project_name="Orange3-SingleCell" version="" title="Load Data" position="(150, 150)" /&gt; </nodes&gt; <links /&gt; <annotations /&gt; <thumbnail /&gt; <node_properties /&gt; <session_state&gt; <window_groups /&gt; </session_state&gt; </scheme&gt;&nbsp;
Version:
3.29.3
Environment:
Python 3.8.8 on Windows 10 10.0.19041 AMD64
Installed Packages:
AnyQt==0.0.13, Bottleneck==1.3.2, CacheControl==0.12.6, Genesis-PyAPI==1.2.1, Orange3-Bioinformatics==4.3.1, Orange3-SingleCell==1.4.0, Orange3==3.29.3, Pillow==8.2.0, PyQt5-sip==4.19.18, PyQt5==5.12.3, PyQtChart==5.12, PyQtWebEngine==5.12.1, PySocks==1.7.1, PyYAML==5.4.1, XlsxWriter==1.4.3, anndata==0.7.6, baycomp==1.0.2, brotlipy==0.7.0, cached-property==1.5.2, catboost==0.26, certifi==2021.5.30, cffi==1.14.5, chardet==4.0.0, click==8.0.1, colorama==0.4.4, commonmark==0.9.1, cryptography==3.4.7, cycler==0.10.0, decorator==5.0.9, dictdiffer==0.8.1, docutils==0.17.1, et-xmlfile==1.0.1, fastdtw==0.3.4, future==0.18.2, h11==0.12.0, h2==4.0.0, h5py==3.2.1, hpack==4.0.0, httpcore==0.12.3, httpx==0.16.1, hyperframe==6.0.1, idna==2.10, importlib-metadata==4.5.0, itsdangerous==2.0.1, jdcal==1.4.1, joblib==1.0.1, keyring==23.0.1, keyrings.alt==4.0.2, kiwisolver==1.3.1, llvmlite==0.36.0, lockfile==0.12.2, loompy==3.0.6, matplotlib==3.4.2, msgpack==1.0.2, natsort==7.1.1, networkx==2.5, numba==0.53.1, numpy-groupies==0.9.13, numpy==1.19.5, olefile==0.46, openTSNE==0.6.0, openpyxl==3.0.7, orange-canvas-core==0.1.21, orange-widget-base==4.13.1, packaging==20.9, pandas==1.2.4, pip==21.1.2, point-annotator==2.0.0, pyOpenSSL==20.0.1, pyclipper==1.2.1, pycparser==2.20, pyparsing==2.4.7, pyqtgraph==0.12.1, pyreadline==2.1, python-dateutil==2.8.1, python-louvain==0.15, pytz==2021.1, pywin32-ctypes==0.2.0, qasync==0.16.0, requests-cache==0.6.4, requests==2.25.1, rfc3986==1.5.0, scikit-learn==0.23.2, scipy==1.5.3, serverfiles==0.3.0, setuptools==49.6.0.post20210108, six==1.16.0, slumber==0.7.1, sniffio==1.2.0, threadpoolctl==2.1.0, tornado==6.1, typing-extensions==3.10.0.0, url-normalize==1.4.3, urllib3==1.26.5, wheel==0.36.2, win-inet-pton==1.1.0, wincertstore==0.2, xlrd==2.0.1, zipp==3.4.1
Machine ID:
24177f9a-61dd-45f6-9f88-9a9b64d9f316
Stack Trace:
Traceback (most recent call last):
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 372, in __process_init_queue
&nbsp; &nbsp; self.ensure_created(node)
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 320, in ensure_created
&nbsp; &nbsp; self.__add_widget_for_node(node)
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 236, in __add_widget_for_node
&nbsp; &nbsp; w = self.create_widget_for_node(node)
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 300, in create_widget_for_node
&nbsp; &nbsp; widget = self.create_widget_instance(node)
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 403, in create_widget_instance
&nbsp; &nbsp; item.widget = widget = klass.__new__(
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\widget.py", line 340, in __new__
&nbsp; &nbsp; self.update_summaries()
&nbsp; File "C:\Users\lhy\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\signals.py", line 515, in update_summaries
&nbsp; &nbsp; self._update_summary(self.input_summaries)
TypeError: _update_summary() takes 1 positional argument but 2 were given


Local Variables:
OrderedDict([('self',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <orangecontrib.single_cell.widgets.owmultisample.OWMultiSample object at 0x00000179C56CA160&gt;)])



Operating system: Windows 10

Orange version: 3.39



May it would help you&nbsp;produce the problem.
It's the first time I use Orange. Thank you for trying to solve the problem for me!&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marko ***@***.***&gt;; 
发送时间: 2021年6月12日(星期六) 下午4:18
收件人: ***@***.***&gt;; 
抄送: "Liu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biolab/orange3] Orange 3.29.3 Cannot Load Data (#5483)





 
Thanks! I do not see the full traceback though. Which widget did you try to add?

**Comment by markotoplak** [comment]
Thanks, this helps a lot. So it seems the one single cell widget is incompatible with the newest orange. Until this resolves, please use an older version of Orange. I think 3.28.0 should work properly.

**Comment by liuhuiye** [comment]
Thanks, I would have a try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marko ***@***.***&gt;; 
发送时间: 2021年6月12日(星期六) 下午4:55
收件人: ***@***.***&gt;; 
抄送: "Liu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biolab/orange3] Orange 3.29.3 Cannot Load Data (#5483)





 
Thanks, this helps a lot. So it seems the one single cell widget is incompatible with the newest orange. Until this resolves, please use an older version of Orange. I think 3.28.0 should work properly.

**Comment by liuhuiye** [comment]
3.28.0 works properly. Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liu Huiye"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月12日(星期六) 下午5:12
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [biolab/orange3] Orange 3.29.3 Cannot Load Data (#5483)



 Thanks, I would have a try.




------------------ 原始邮件 ------------------
发件人: "Marko ***@***.***&gt;; 
发送时间: 2021年6月12日(星期六) 下午4:55
收件人: ***@***.***&gt;; 
抄送: "Liu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biolab/orange3] Orange 3.29.3 Cannot Load Data (#5483)





 
Thanks, this helps a lot. So it seems the one single cell widget is incompatible with the newest orange. Until this resolves, please use an older version of Orange. I think 3.28.0 should work properly.

**Comment by PrimozGodec** [comment]
There is already a fix prepared: https://github.com/biolab/orange3-single-cell/pull/384/files Can please someone check and merge it?
