### ISSUE TITLE
Edit Domain: crash on setting DiscreteVariable

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3#5532]
**What's wrong?**

Edit Domain crashes on certain instances of converting a StringVariable to DiscreteVariable.

Not sure if it is an issue of Edit Domain or Import Documents.

```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/data/oweditdomain.py", line 1765, in __reinterpret_activated
    data = transform(self.__data)
  File "/Users/ajda/orange/orange3/Orange/widgets/data/oweditdomain.py", line 282, in __call__
    data, values = categorical_from_vector(vector.data())
  File "/Users/ajda/orange/orange3/Orange/widgets/data/oweditdomain.py", line 398, in categorical_from_vector
    unq, index = categorize_unique(data)
  File "/Users/ajda/orange/orange3/Orange/widgets/data/oweditdomain.py", line 416, in categorize_unique
    unq, index = masked_unique(data)
  File "/Users/ajda/orange/orange3/Orange/widgets/data/oweditdomain.py", line 374, in masked_unique
    return np.ma.unique(data, return_inverse=True)
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/numpy/ma/extras.py", line 1078, in unique
    output = np.unique(ar1,
  File "<__array_function__ internals>", line 5, in unique
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 262, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 320, in _unique1d
    perm = ar.argsort(kind='mergesort' if return_index else 'quicksort')
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/numpy/ma/core.py", line 5490, in argsort
    return filled.argsort(axis=axis, kind=kind, order=order)
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**How can we reproduce the problem?** 

Import Documents (load URL: http://file.biolab.si/text-semantics/data/predlogi-vladi-sample/). Connect to Edit Domain. Change "upvotes" to DiscreteVariable.

**What's your environment?**

- Operating system: OSX
- Orange version: 3.30.dev
- How you installed Orange: git

**Comment by VesnaT** [comment]
I can't reproduce this. Not even with the old version of `YamlMetaReader`.
