### ISSUE TITLE
Installing Orange 3.29.3 using Windows 

### ISSUE THREAD

**Issue by Blesst88** [biolab/orange3#5535]
**What's wrong?**

Could not start up Orange post installation 
No errors encountered during installation
Tried uninstalling and deleting Orange and Miniconda files and reinstalling several times but unable to startup the Orange App  

**How can we reproduce the problem?** 

Unable to create an OWS file 

**What's your environment?**

- Operating system: Windows 10 
- Orange version: 3.29.3
- How you installed Orange:
Using the Orange installer from the download Orange website

**Comment by ales-erjavec** [comment]
Can you open 'Orange Command Prompt' (from the start menu) and type in

```
python -m Orange.canvas
``` 
and post the output of the command.

**Comment by Blesst88** [comment]
The message obtained is

"Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases"


Rgds
Ben

**Comment by markotoplak** [comment]
Thank you! This issue is new, so just to double-check: are you sure you used the "Orange Command Prompt"? This is not the ordinary command prompt in windows, it is a special one that comes with Orange installation.

In the meanwhile, you could also try the portable version (the second download): https://orangedatamining.com/download/#windows

**Comment by Blesst88** [comment]
I had re-run the command again in the Orange command prompt

And obtained the same  error

***@***.***

Fyi I have miniconda py38_4.9.2 , python3.9  and Ananconda installed on the same machine

Pl advice if there is a fix

Thanks

Ben

**Comment by ales-erjavec** [comment]
Is there any error output immediately when you open 'Orange Command Prompt'?

Can you run
```
echo %PATH%
```
and post the output.

Also try 
```
cd "location_where_you_installed_orange"
.\python -m Orange.canvas
```
where `location_where_you_installed_orange` is probably "AppData\Local\Programs\Orange" if you installed for single user and "C:\Program Files\Orange" for an all users install.

**Comment by Blesst88** [comment]
Error received upon opening Orange Command Prompt is :
failed to create process.

C:\Users\benlee88>echo %PATH%

C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;\\aex01\netlogon;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\users\benlee88\appdata\local\microsoft\windowsapps;i:\win\dll;i:\win\bin;i:\orawin95\bin;C:\Users\benlee88\AppData\Local\GitHubDesktop\bin



C:\Users\benlee88\AppData\Local\Programs\Orange>python -m Orange.canvas
Traceback (most recent call last):
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\Orange\__init__.py", line 4, in <module>
    from Orange import data
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\Orange\data\__init__.py", line 8, in <module>
    from .table import *
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\Orange\data\table.py", line 29, in <module>
    from Orange.statistics.util import bincount, countnans, contingency, \
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\Orange\statistics\util.py", line 12, in <module>
    import scipy.stats.stats
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\stats\__init__.py", line 388, in <module>
    from .stats import *
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\stats\stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\spatial\__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\spatial\_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\linalg\__init__.py", line 194, in <module>
    from .misc import *
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\linalg\misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\benlee88\AppData\Local\Programs\Orange\lib\site-packages\scipy\linalg\blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed while importing _fblas: The network path was not found.

But when I started the other earlier version 27.1 using


C:\Users\benlee88\AppData\Local\Programs\Orange>cd C:\Users\benlee88\AppData\Local\Programs\Orange271
C:\Users\benlee88\AppData\Local\Programs\Orange271>python -m Orange.canvas

Orange 27.1 was launched

How can I upgrade to the latest version 29.3 ?


Ben

**Comment by fahminlb33** [comment]
> The message obtained is "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases".

Maybe you have two `python` executable on your PC. Windows ships it's own `python` executable that will redirect you to Microsoft Store version of Python. Disable it and you should be good to go.

Open Settings > Apps > App execution aliases > Turn off `python` and `python3`.

![image](https://user-images.githubusercontent.com/8360880/127771915-883a43e4-00f9-49a2-bf9c-f073db313e6e.png)

**Comment by markotoplak** [comment]
@fahminlb33, could you try the latest package (3.30.2)? That release includes the fix in ales-erjavec/orange3-installers#21. Please report if the newer package works for you or not.

**Comment by fahminlb33** [comment]
Sure I'll try it
