### ISSUE TITLE
text add-on not working

### ISSUE THREAD

**Issue by codecypher** [biolab/orange3#5586]
**What's wrong?**

The text mining add-on "Text" is not working nor even showing as installed, on v 3.29

**How can we reproduce the problem?** 

See bug report #5458

**What's your environment?**

- Operating system: macOS 11.5.2
- Orange version: 3.29.3
- How you installed Orange: standalone macOS dmg (anaconda version will not even load so uninstalled).

**Comment by codecypher** [comment]
View > Log:

2021-09-02 23:27:00,213:INFO:orangecanvas.registry.discovery: Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/owscatterplotgraph.py'.
2021-09-02 23:27:00,218:INFO:orangecanvas.registry.discovery: Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/owtreeviewer2d.py'.
2021-09-02 23:27:00,253:INFO:orangecanvas.registry.discovery: Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/pythagorastreeviewer.py'.
2021-09-02 23:27:00,282:INFO:orangecanvas.registry.discovery: Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/evaluate/contexthandlers.py'.
2021-09-02 23:27:00,288:INFO:orangecanvas.registry.discovery: Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/evaluate/utils.py'.

**Comment by PrimozGodec** [comment]
Thank you for reporting the issue. Can you check two things?

1. Check if text addon is installed: Go to Options>Add-ons and check if text addon is checked (installed)? If not can you please check it and click OK. It will trigger the installation process. If installation fails please copy the error message here.

2. Get the error message when running Orange: If the addon is installed please run Orange from the command line: Run terminal (you can find it among applications) and past this command in the terminal `/Applications/Orange3.app/Contents/MacOS/Orange -l 4`. Then copy the log output you see in the terminal when Orange loads.

**Comment by codecypher** [comment]
Hi,

Here are the results:

INFO:__main__:Starting 'Orange Canvas' application.
DEBUG:__main__:Starting CanvasApplicaiton with argv = ['/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/canvas/__main__.py'].
INFO:qasync:Using Qt Implementation: PyQt5
DEBUG:asyncio:Using selector: _Selector
INFO:__main__:Switching default stylesheet to darkorange
INFO:orangecanvas.document.usagestatistics:Enabling usage statistics tracking
INFO:__main__:Adding search path 'orange' for prefix, 'canvas_icons'
INFO:orangecanvas.application.canvasmain:Setting up Canvas main window.
DEBUG:orangecanvas.config:Activating configuration for <Orange.canvas.config.Config object at 0x7fdae8e62130>
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: False)
DEBUG:orangecanvas.gui.stackedwidget:Stack transition start ()
DEBUG:orangecanvas.gui.stackedwidget:Stack transition finished ()
DEBUG:orangecanvas.registry.cache:Loading widget registry cache ('/Users/jholmes/Library/Caches/Orange/3.29.3/registry-cache.pck').
INFO:__main__:Running widget discovery process.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/owscatterplotgraph.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/owtreeviewer2d.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/visualize/pythagorastreeviewer.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/evaluate/contexthandlers.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/evaluate/utils.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/_owmodel.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/_rangeslider.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/utils.py'.
ERROR:orangecanvas.registry.discovery:An exception occurred while loading entry point 'Text Mining = orangecontrib.text.widgets'
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/registry/discovery.py", line 88, in run
    point = entry_point.resolve()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/text/__init__.py", line 6, in <module>
    from .corpus import Corpus
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/text/corpus.py", line 11, in <module>
    from gensim import corpora
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gensim/matutils.py", line 1024, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "gensim/_matutils.pyx", line 1, in init gensim._matutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
DEBUG:orangecanvas.registry.cache:Saving widget registry cache with 157 entries ('/Users/jholmes/Library/Caches/Orange/3.29.3/registry-cache.pck').
DEBUG:orangecanvas.registry:'set_global_registry()' - setting registry.
INFO:__main__:Entering main event loop.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): orange.biolab.si:443
DEBUG:urllib3.connectionpool:https://orange.biolab.si:443 "POST /usage-statistics HTTP/1.1" 200 None
INFO:__main__:Usage statistics sent.
DEBUG:orangecanvas.canvas.scene:Setting interaction '<orangecanvas.document.interactions.RectangleSelectionAction object at 0x7fdae9b89700>' to 'CanvasScene(objectName='', ...)'
DEBUG:orangecanvas.canvas.scene:Setting interaction 'None' to 'CanvasScene(objectName='', …)'


On Sep 10, 2021, at 5:10 AM, Primož Godec ***@***.***> wrote:


Thank you for reporting the issue. Can you check two things?

Check if text addon is installed: Go to Options>Add-ons and check if text addon is checked (installed)? If not can you please check it and click OK. It will trigger the installation process. If installation fails please copy the error message here.

Get the error message when running Orange: If the addon is installed please run Orange from the command line: Run terminal (you can find it among applications) and past this command in the terminal /Applications/Orange3.app/Contents/MacOS/Orange -l 4. Then copy the log output you see in the terminal when Orange loads.

**Comment by markotoplak** [comment]
I suspect library conflicts. Try running this command in the terminal `/Applications/Orange3.app/Contents/MacOS/pip install gensim==3.8.3` to enforce an older version of one library.

**Comment by PrimozGodec** [comment]
Gensim have some build problems: https://github.com/RaRe-Technologies/gensim/issues/3226

**Comment by PrimozGodec** [comment]
We need to wait for that Gensim to fix its issues. I proposed a release that limits Gensim to <4 https://github.com/biolab/orange3-text/pull/718

**Comment by PrimozGodec** [comment]
It should work with the newest release of Orange3-text. Please try to reinstall text addon and let us know if it works now. 

I am closing this PR but feel free to reopen it in case it is not working.
