### ISSUE TITLE
ffi_prep_cif_var failed

### ISSUE THREAD

**Issue by haharay** [biolab/orange3#5711]
**What's wrong?**

(orange3) XXX@XXXMacBook-Pro ~ % orange-canvas
Traceback (most recent call last):
  File "/Users/XXX/mambaforge/envs/orange3/bin/orange-canvas", line 11, in <module>
    sys.exit(main())
  File "/Users/XXX/mambaforge/envs/orange3/lib/python3.9/site-packages/Orange/canvas/__main__.py", line 420, in main
    fix_macos_nswindow_tabbing()
  File "/Users/XXX/mambaforge/envs/orange3/lib/python3.9/site-packages/orangecanvas/main.py", line 434, in fix_macos_nswindow_tabbing
    _macos_set_nswindow_tabbing()
  File "/Users/XXX/mambaforge/envs/orange3/lib/python3.9/site-packages/orangecanvas/gui/utils.py", line 230, in macos_set_nswindow_tabbing
    objc_msgSend(
RuntimeError: ffi_prep_cif_var failed

**How can we reproduce the problem?** 

conda create python=3 --yes --name orange3
conda activate orange3
conda install orange3

orange-canvas

**What's your environment?**

- Operating system:  MacOS 10.15.7
- Orange version:   '3.30.2'
- How you installed Orange:

conda create python=3 --yes --name orange3
conda activate orange3
conda install orange3

**Comment by markotoplak** [comment]
@haharay, thanks for the report. 

For the time being, you can avoid this error by installing PyQt5 5.15 (not available on conda-forge, you'll need this from pip), or perhaps even comment line 420 in `/Users/XXX/mambaforge/envs/orange3/lib/python3.9/site-packagesOrange/canvas/__main__.py`.

**Comment by ales-erjavec** [comment]
Or downgrade libffi `conda install -c conda-forge libffi=3.3.*`
