### ISSUE TITLE
Group By: error in the callback function

### ISSUE THREAD

**Issue by chourroutm** [biolab/orange3#5917]
**What's wrong?**

```
----------------------------- KeyError Exception ------------------------------
Traceback (most recent call last):
  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/Orange/widgets/data/owgroupby.py", line 384, in __rows_selected
    active_aggregations = [self.aggregations[attr] for attr in selected_attrs]
  File "/home/chourroutm/.orange-env/lib/python3.8/site-packages/Orange/widgets/data/owgroupby.py", line 384, in <listcomp>
    active_aggregations = [self.aggregations[attr] for attr in selected_attrs]
KeyError: DiscreteVariable(name='species', values=('human2', 'mouse2', 'pogona2', 'rat2'), compute_value=Lookup(variable=DiscreteVariable(name='species', values=('human', 'mouse', 'pogona', 'rat')), lookup_table=array([0., 1., 2., 3.])))
-------------------------------------------------------------------------------
```

**How can we reproduce the problem?** 

It happens in the Group By widget GUI on a field on which I used a Select Rows widget, when I try to change the default behavior, which is 'Concatenate' checked and everything else unchecked. Here, I picked "mouse" and "rat" and thus discarded "human" and "pogona". I tried using Purge Domain on my flow first, but the error kept showing up.

**What's your environment?**

- Operating system: Linux Ubuntu 20.04 LTS
- Orange version: 3.31.1
- How you installed Orange: via pip

**Comment by ajdapretnar** [comment]
I am unable to reproduce this. Could you perhaps try the same workflow on one of the standard datasets (zoo, iris, heart-disease) and see if it still fails? Perhaps attach a screenshot so that we know how to get the error.
