### ISSUE TITLE
Error Message Using Feature Importance Widget

### ISSUE THREAD

**Issue by rehoyt** [biolab/orange3#5947]
<!-- 
Since I updated to version 3.32.0 I cannot get the feature importance widget to work. I am using a Mac with Monterey OS 12.3.1. The dataset is the heart prediction dataset included in the file widget. It generates the following error message

```Error encountered in widget Feature Importance:

Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1024, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1062, in __process_next_helper
    self.process_node(selected_node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 690, in process_node
    self.send_to_node(node, signals_in)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 806, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 820, in process_signals_for_widget
    process_signals_for_widget(widget, signals, workflow)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 923, in process_signals_for_widget
    handle_new_signals(widget, workflow)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 910, in handle_new_signals
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/explain/widgets/owexplainfeaturebase.py", line 487, in handleNewSignals
    self.start(self.run, *self.get_runner_parameters())
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/explain/widgets/owpermutationimportance.py", line 299, in get_runner_parameters
    score = usable_scorers(var)[self.score_index]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/evaluate/utils.py", line 92, in usable_scorers
    usable = [scorer for scorer in scorer_candidates if
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/evaluate/utils.py", line 93, in 
    scorer.is_compatible(domain) and scorer.class_types]
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/evaluation/scoring.py", line 125, in is_compatible
    return domain.has_discrete_class
AttributeError: 'DiscreteVariable' object has no attribute 'has_discrete_class'```

-->


**What's wrong?**
<!-- Be specific, clear, and concise. Include screenshots if relevant. -->
<!-- If you're getting an error message, copy it, and enclose it with three backticks (```). -->





**How can we reproduce the problem?** 
<!-- Feature Importance.ows-->
<!-- I evaluated the heart disease prediction dataset already in the file widget with logistic regression and the feature importance widget...) -->




**What's your environment?**
<!-- To find your Orange version, see "Help → About → Version" or `Orange.version.full_version` in code -->
- Operating system: Mac Monterey
- Orange version: 3.32.0
- How you installed Orange: from website

**Comment by ajdapretnar** [comment]
We'll need a bit more information than that.

**Comment by markotoplak** [comment]
Oh, we do know about this problem. It was my fault, actually.

It has been fixed in #5943 or biolab/orange3-explain#42, whichever is going to be released first. If you need this feature immediately, downgrade Orange to the previous version (see https://download.biolab.si/download/files/). The new version of the add-on is likely going to be released later today, right, @VesnaT? :) We will post here when that happens.

Thanks for reporting the problem!
