### ISSUE TITLE
TIMESERIES add-on v0.4.0

### ISSUE THREAD

**Issue by LizzyOberholzer2** [biolab/orange3#6014]
**What's wrong?**

I installed the TIMESERIES add-on and it shows ticked, hence installed (restarted as well) but not showing up in my left pane.

**How can we reproduce the problem?** 

I think there is a bug with v0.4.0, install it and let me know if you can access the Timeseries widgets

**What's your environment?**

- Operating system: windows
- Orange version: 3.32
- How you installed Orange: from the official orange website

**Comment by thocevar** [comment]
I've just successfully installed Orange 3.32 and the TimeSeries add-on on a clean Windows machine.

Could you try starting Orange from command line with `C:\Users\Tomaz\AppData\Local\Programs\Orange\python.exe -m Orange.canvas -l4` (you can find the right installation folder from the target of your Orange shortcut) and report the output.

**Comment by Avicebron1972** [comment]
I am using Orange3-3.32.0. in "Portable" version (unfortunately, the installation of the Miniconda version does not work on my PC). I also installed the TIMESERIES add-on v0.4.0. Everything works fine, except the two models ARIMA and VAR: when I insert them in the flowchart and try to open them I get these errors:

**ARIMA**
------
Traceback (most recent call last):
  File "C:\Users\info\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\info\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\info\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owarimamodel.py", line 29, in __init__
    super().__init__()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 47, in __init__
    self.setup_layout()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 132, in setup_layout
    self.add_main_layout()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owarimamodel.py", line 43, in add_main_layout
    gui.spin(None, self, 'p', 0, 100, **kwargs))
  File "C:\Users\info\Orange\lib\site-packages\orangewidget\gui.py", line 783, in spin
    sbox = bi.control = b.control = \
AttributeError: 'NoneType' object has no attribute 'control'_


**VAR**
_------
Traceback (most recent call last):
  File "C:\Users\info\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Users\info\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Users\info\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 47, in __init__
    self.setup_layout()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 133, in setup_layout
    self.add_bottom_buttons()
  File "C:\Users\info\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 152, in add_bottom_buttons
    gui.spin(None, self, 'forecast_steps', 1, 100,
  File "C:\Users\info\Orange\lib\site-packages\orangewidget\gui.py", line 783, in spin
    sbox = bi.control = b.control = \
AttributeError: 'NoneType' object has no attribute 'control'_

Can you help me, please? Thank you
Regards
