### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Orange3.app

### ISSUE THREAD

**Issue by sugizo** [biolab/orange3#6023]
**What's wrong?**

```
$ open /Applications/Orange3.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Orange3.app.
```

**How can we reproduce the problem?** 

Download Orange3-3.32.0-Python3.8.8.dmg from https://orangedatamining.com/download/#macos
double click downloaded *.dmg file, then put in /Applications 
open terminal then execute
`open /Applications/Orange3.app`

if you double click /Applications/Orange3.app from Finder, nothing happen

**What's your environment?**

- Operating system:
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G2136)
      Kernel Version: Darwin 16.7.0
```
- Orange version:
Orange3-3.32.0-Python3.8.8.dmg
- How you installed Orange:
From *.dmg file above then put the Orange3.app to /Applications/

**Comment by ales-erjavec** [comment]
Can you run 
```bash
/Applications/Orange3.app/Contents/MacOS/Orange 
```
directly and post any output.

**Comment by sugizo** [comment]
```
$ /Applications/Orange3.app/Contents/MacOS/Orange
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/__init__.py", line 30, in <module>
    from AnyQt.QtCore import QObject
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/AnyQt/QtCore.py", line 247, in <module>
    from PyQt5.QtCore import *
ImportError: dlopen(/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so, 2): Symbol not found: _futimens
  Referenced from: /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore
```

**Comment by ales-erjavec** [comment]
Qt 5.15.2 that is included in the Orange3.app is build against Mac OS X 10.13, and cannot run on your system

Can you try running
```
/Applications/Orange3.app/Contents/MacOS/pip install PyQt5~=5.12.2  PyQtWebengine~=5.12.0
```

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
