### ISSUE TITLE
Issue with (portable) Orange 3.32.0 - conflict with Anaconda?

### ISSUE THREAD

**Issue by LBcoding** [biolab/orange3#6048]
I have problems in runnig Orange on my device:

-I have a new user on Windows10 and installed Anaconda 3-2022.05 version on it
-I have tried to download the portable version of Orange that doesn't open. Running the Orange Debug this is what I get:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Orange3-3.32.0\Orange\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Administrator\Desktop\Orange3-3.32.0\Orange\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Administrator\Desktop\Orange3-3.32.0\Orange\lib\site-packages\Orange\__init__.py", line 4, in <module>
    from Orange import data
  File "C:\Users\Administrator\Desktop\Orange3-3.32.0\Orange\lib\site-packages\Orange\data\__init__.py", line 4, in <module>
    from .variable import *
  File "C:\Users\Administrator\Desktop\Orange3-3.32.0\Orange\lib\site-packages\Orange\data\variable.py", line 11, in <module>
    import scipy.sparse as sp
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\scipy\__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (C:\Users\Administrator\anaconda3\Lib\site-packages\scipy\_lib\__init__.py)

Any Idea about this error? 
Why when importing scipy.sparse, the "anconda3\Lib\site-package\scipy" path is used and not the "Orange\lib\site-packages\scipy" path? Could be this the source of the error?

Any help is appreciated.
LB

**Comment by thocevar** [comment]
I've just tried to use portable Orange alongside an Anaconda installation and it worked without problems. However, it does look wrong in your case that `import scipy.sparse` picks up scipy from Anaconda and not from Orange's package library. I would suggest you try installing Orange with conda since you have Anaconda already set up.
