### ISSUE TITLE
Can't install or update addons

### ISSUE THREAD

**Issue by leeherman99** [biolab/orange3#6106]
**What's wrong?**
When I try to add/update addons, I get a "There's an issue with the internet connection" error message. The detailed message includes "certificate verify failed: self signed certificate in certificate chain". I'm on a corporate network, but we do not use a proxy. Here's the full error message:

Traceback (most recent call last):
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Orange3-3.32.0\Orange\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Orange3-3.32.0\Orange\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Orange3-3.32.0\Orange\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Orange3-3.32.0\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\orangecanvas\application\addons.py", line 695, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1283, in list_available_versions
    defaults = config.addon_defaults_list()
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\Orange\canvas\config.py", line 161, in addon_defaults_list
    return session.get(OFFICIAL_ADDON_LIST).json()
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\Orange3-3.32.0\Orange\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

**How can we reproduce the problem?** 

Just open the Addons panel.

**What's your environment?**

- Operating system: Windows 10 Pro
- Orange version: 3.32.0
- How you installed Orange: standalone

**Comment by ongjx6** [comment]
I have issues with Ananconda download which comes with Orange software. Due to this, I am unable to download Orange successfully. When I download Ananconda, I kept having this error message 'Failed to create menus'.

**Comment by markotoplak** [comment]
@ongjx6, you seem to have some other issue.

You may open a new issue that describes your problem better. I could not understand what you did. In the new issue, try to be very precise. For example, which file did you use to install Orange. Or you installed it somehow differently? I also do not understand what you mean by downloading Anaconda, so please be more precise.

**Comment by markotoplak** [comment]
@leeherman99, we tried solving these errors a while ago. We believe the most problematic ones should be fixed in biolab/orange-canvas-core/pull/247
