### ISSUE TITLE
API change in scikit-learn latest release

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3#6248]
Release notes for scikit-learn == 1.2.0 : https://scikit-learn.org/stable/whats_new/v1.2.html

> API Change The n_features_ attribute of [decomposition.PCA](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html#sklearn.decomposition.PCA) is deprecated in favor of n_features_in_ and will be removed in 1.4. [#24421](https://github.com/scikit-learn/scikit-learn/pull/24421) by [Kshitij Mathur](https://github.com/Kshitij68).

Error msg when running tests for Louvain Clustering
```

Traceback (most recent call last):
  File "/Users/jakakokosar/Documents/dev/orange/orange3/Orange/widgets/unsupervised/owlouvainclustering.py", line 301, in __on_done
    result = future.result()
  File "/Users/jakakokosar/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/jakakokosar/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/jakakokosar/.pyenv/versions/3.10.8/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jakakokosar/Documents/dev/orange/orange3/Orange/widgets/unsupervised/owlouvainclustering.py", line 613, in run_on_data
    data = res.pca_projection = pca(data)(data)
  File "/Users/jakakokosar/Documents/dev/orange/orange3/Orange/projection/base.py", line 50, in __call__
    clf = self.fit(data.X, data.Y)
  File "/Users/jakakokosar/Documents/dev/orange/orange3/Orange/projection/pca.py", line 268, in fit
    proj = proj.fit(X, Y)
  File "/Users/jakakokosar/.pyenv/versions/orange/lib/python3.10/site-packages/sklearn/decomposition/_pca.py", line 435, in fit
    self._fit(X)
  File "/Users/jakakokosar/Documents/dev/orange/orange3/Orange/projection/pca.py", line 142, in _fit
    return self._fit_truncated(X, n_components, self._fit_svd_solver)
  File "/Users/jakakokosar/Documents/dev/orange/orange3/Orange/projection/pca.py", line 204, in _fit_truncated
    self.n_samples_, self.n_features_ = n_samples, n_features
AttributeError: can't set attribute 'n_features_'

```

**Comment by BlazZupan** [comment]
Same problem also kills t-SNE. We need to fix this asap.

**Comment by JakaKokosar** [comment]
@BlazZupan downgrade scikit-learn to the previous version for a quick fix.
