### ISSUE TITLE
Fails to launch after installing on Ubuntu 22.04 (Python 3.10)

### ISSUE THREAD

**Issue by dat-linux** [biolab/orange3#6274]
`Traceback (most recent call last):
  File "~/.cari/venv/orange/3.34.1/bin/orange-canvas", line 5, in <module>
    from Orange.canvas.__main__ import main
  File "~/.cari/venv/orange/3.34.1/lib/python3.10/site-packages/Orange/canvas/__main__.py", line 22, in <module>
    from AnyQt.QtGui import QColor, QDesktopServices, QIcon, QPalette
  File "~/.cari/venv/orange/3.34.1/lib/python3.10/site-packages/AnyQt/QtGui.py", line 2, in <module>
    from .QtCore import QT_VERSION_INFO as __QT_VERSION_INFO
  File "~/.cari/venv/orange/3.34.1/lib/python3.10/site-packages/AnyQt/QtCore.py", line 1, in <module>
    from . import _api
  File "~/.cari/venv/orange/3.34.1/lib/python3.10/site-packages/AnyQt/_api.py", line 116, in <module>
    raise ImportError("PyQt4, PyQt5, PySide or PySide2 are not available for import")
ImportError: PyQt4, PyQt5, PySide or PySide2 are not available for import`

This is a recent issue, as previous versions have not had any problems. Installed with pip v**3.34.1** into a virtual env.

**Comment by markotoplak** [comment]
Sorry, we changed dependencies in 3.34 so that the do not include PyQt5. We did this because otherwise users that need PyQt6 has issues.

The solution is to install PyQt manually (see README.md).

I guess you already fixed the issue.

**Comment by dat-linux** [comment]
> 

why not just change deps to allow pyqt6?
