### ISSUE TITLE
Error Message When Imputing Data into "CSV File Import"

### ISSUE THREAD

**Issue by mwells44** [biolab/orange3#6433]
**What's wrong?**
 I am a student and my professor gave us an Orange starter file and CSV file to import into the file. The Orange starter file is already set up with the proper widgets and links between them. When I try to upload the CSV file into the "CSV File Import" widget, it gives me a pop-up window saying the file may be a "binary file", and asks if I want to continue. 

<img width="452" alt="Screenshot 1" src="https://user-images.githubusercontent.com/131904710/234663166-cbfa7cd1-ef69-4096-aa7b-c40bd985ed68.png">

When I click yes to continue it gives me a second pop-up window. 

<img width="836" alt="Screenshot 2" src="https://user-images.githubusercontent.com/131904710/234663236-de70446f-1024-4e81-aa17-074726b6e26e.png">

If I click cancel on this second pop-up window it tells me that the file was not loaded due to a "text encoding error". I have also tried un-installing and re-installing the latest version of Orange with no luck.

 
'''Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Orange/widgets/data/owcsvimport.py", line 1203, in __handle_result
    df = f.result()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Orange/widgets/utils/concurrent.py", line 175, in run
    result = func(*args, **kwargs)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Orange/widgets/data/owcsvimport.py", line 1675, in wrapper
    return f(*args, **kwargs)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Orange/widgets/data/owcsvimport.py", line 1543, in load_csv
    f = stack.enter_context(_open(path, 'rb'))
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Orange/widgets/data/owcsvimport.py", line 1408, in _open
    return open(path, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/JeffsFilesfromOldMac/Downloads/BBBBankruptcy/Bed Bath & Beyond Bankruptcy.csv''''

**How can we reproduce the problem?** 
 
[Archive.zip](https://github.com/biolab/orange3/files/11335992/Archive.zip)

 Open the "CSV File Import" widget. Upload the CSV file and then the error message will appear. 

**What's your environment?**

- Operating system: macOS
- Orange version: 3.34.0
- How you installed Orange: I downloaded Orange for macOS directly form the Orange website.

**Comment by ales-erjavec** [comment]
In the screenshot it shows you are loading a **.numbers** file. This wont work as it is a proprietary apple format.

But in the provided archive you have a workflow attempting to load a **Bed Bath & Beyond Bankruptcy.csv** but there is no such file there. There is a **Bed Bath & Beyond Bankruptcy-4 copy.csv** though. 
If I open that file it parses just fine.
