### ISSUE TITLE
Save Data Widget not working or raising error

### ISSUE THREAD

**Issue by lhemerly** [biolab/orange3#6620]
**What's wrong?**
I have a quite simple workflow that reads a .pkl.gz file, filter a few rows, a few columns and save the data.

The objective is to save over the same file (like a delete operation for the given filters), but it is ok to save it to another file if needed. But when I click the save button in the save widget window, it opens the save file dialog. After selecting the file it loads for a few seconds and doesn't save neither throws an error. 

The workflow has another save widget that is used to update the file with new data. The save widget to update the file with new data is working fine.

I tried the following:

1. Clicking "save as" then "save";
2. Deleting the other save data widget;
3. Including a data table widget before the save data widget;
4. Saving as other formats (csv, tab, pkl)

All those tries had the same result: open save file dialog without saving and not throwing an error.

**How can we reproduce the problem?**
I can't upload the data, but I'm uploading the .ows file (you may need to tweak the filters to use sample data)
[SGP_Create.zip](https://github.com/biolab/orange3/files/13230694/SGP_Create.zip)

Important to note: I created a new workflow with only the part to load file, select columns and rows and save and it worked.

**What's your environment?**
- Operating system: Windows 10
- Orange version: 3.36.1
- How you installed Orange: installer downloaded from official website

**Comment by lhemerly** [comment]
An update. Just found out the log file, set it to debug:
[canvas.log](https://github.com/biolab/orange3/files/13230817/canvas.log)

```
Could not serialize to a literal string
Traceback (most recent call last):
  File "C:\Users\lechern\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\readwrite.py", line 763, in dumps
    return (literal_dumps(obj, indent=1 if prettyprint else None),
  File "C:\Users\lechern\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\readwrite.py", line 909, in literal_dumps
    check_relaxed(obj)
  File "C:\Users\lechern\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\readwrite.py", line 894, in check_relaxed
    return all(map(check_relaxed, chain(obj.keys(), obj.values())))
  File "C:\Users\lechern\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\readwrite.py", line 892, in check_relaxed
    return all(map(check_relaxed, obj))
  File "C:\Users\lechern\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\scheme\readwrite.py", line 905, in check_relaxed
    raise TypeError("{0} can not be serialized as a python "
TypeError: <class 'orangewidget.settings.Context'> can not be serialized as a python literal
Using pickle fallback
```

**Comment by janezd** [comment]
We have seen another (or two?) reports on problems with saving. Something must be going on, but we haven't been able to reproduce it. Same goes for your case. I can't see anything suspicious in your workflow, and the warning you see is normal and would happen with any workflow.

So, I can only thank you for giving us a further warning that something is wrong with saving, and we'll keep our eyes open.
