### ISSUE TITLE
Orange 3 unable to connect to internet

### ISSUE THREAD

**Issue by JakaNov** [biolab/orange3#6689]
Orange 3 is unable to connect to internet which prevents it from installing add-ons through the Options menu. Also, widdgets that need connections to databases do not work. The issue is present on a corporate work pc, the http and https proxies are set in the Network settings.  The error reported is as follows:
```
2024-01-03 07:47:34,558:ERROR:orangecanvas.application.addons: Error fetching package list
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\User\Desktop\Orange\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\User\Desktop\Orange\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\User\Desktop\Orange\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Orange\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "C:\Users\User\Desktop\Orange\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Orange\lib\site-packages\orangecanvas\application\utils\addons.py", line 343, in list_available_versions
    defaults = config.addon_defaults_list()
  File "C:\Users\User\Desktop\Orange\lib\site-packages\Orange\canvas\config.py", line 159, in addon_defaults_list
    return session.get(OFFICIAL_ADDON_LIST).json()
  File "C:\Users\User\Desktop\Orange\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\User\Desktop\Orange\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\Desktop\Orange\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\Desktop\Orange\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)')))
```

- Operating system: Windows 10
- Orange version:  3.36.2
- How you installed Orange: Portable

**Comment by processo** [comment]
It is complaining about a self-signed certificate in the chain. When you open the URL ( https://orange.biolab.si/addons/list ) in browser from your corporate network with proxy does it warn you that the connection is not secure?

**Comment by JakaNov** [comment]
Opening the above URL in a web browser triggers a download of the addon list, it does not warn that the connection is not secure (i.e. it works normally).

**Comment by ales-erjavec** [comment]
Can you try with the normal (i.e. non portable) installation. I think that the Portable installation is broken.

**Comment by JakaNov** [comment]
It seems the problem was the portable Orange3 as you suggested. After installing the non-portable verison and setting proxies connection to the internet was successfull.
