### ISSUE TITLE
Problem installing Orange with Python 3.12

### ISSUE THREAD

**Issue by kaustuvchatterjee** [biolab/orange3#6738]
**What's wrong?**
Installing using pip3 install orange3 throws the following error:

Collecting orange3
  Using cached Orange3-3.36.2.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/kaustuv/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/kaustuv/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/kaustuv/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b7f36p56/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b7f36p56/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-b7f36p56/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 520, in <module>
        File "<string>", line 472, in setup_package
        File "<string>", line 166, in write_version_py
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**How can we reproduce the problem?** 
Installing orange using pip3 install orange3 command on a Linux system with Python version 3.12.1 installed.

**What's your environment?**

- Operating system: Fedora 39
- Orange version: 3.36.2
- How you installed Orange: pip3 install orange3

**Comment by nairboon** [comment]
Orange version 3.36.2 does not appear to be compatible with Python 3.12. This particular issue seems to be fixed in the master branch as of 2b1558a

**Comment by markotoplak** [comment]
There seems to be another issue. A dependency, namely catboost, does not have packages for 3.12 yet. This might or might not be a problem for you (maybe it can be built by pip dynamically) even if you build from the master branch.

**Comment by janezd** [comment]
@markotoplak, we can close this, right?

**Comment by markotoplak** [comment]
I run Orange with Python 3.12 for quite some time, so this is not likely to be relevant anymore.
