### ISSUE TITLE
Error launching Orange in Anaconda: cannot import name 'astype_nansafe' from 'pandas

### ISSUE THREAD

**Issue by skyemoor** [biolab/orange3#6761]
Trying to launch Orange from Anaconda, receive this error;

```
Traceback (most recent call last):
File "/home/will/anaconda3/bin/orange-canvas", line 7, in 
from Orange.canvas.__main__ import main
File "/home/will/anaconda3/lib/python3.11/site-packages/Orange/__init__.py", line 4, in 
from Orange import data
File "/home/will/anaconda3/lib/python3.11/site-packages/Orange/data/__init__.py", line 12, in 
from .pandas_compat import *
File "/home/will/anaconda3/lib/python3.11/site-packages/Orange/data/pandas_compat.py", line 10, in 
from pandas.core.arrays.sparse.dtype import SparseDtype
File "/home/will/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/sparse/dtype.py", line 21, in 
from pandas.core.dtypes.astype import astype_nansafe
ImportError: cannot import name 'astype_nansafe' from 'pandas.core.dtypes.astype' (/home/will/anaconda3/lib/python3.11/site-packages/pandas/core/dtypes/astype.py)
```
Ubuntu 22.04
Orange 3.34.0 via Anaconda
Pandas 1.5.3

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by skyemoor** [comment]
Also attempted to launch Orange from the command line, with the following response;

```
:~$ python -m Orange.canvas
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/will/anaconda3/lib/python3.11/site-packages/Orange/__init__.py", line 4, in <module>
    from Orange import data
  File "/home/will/anaconda3/lib/python3.11/site-packages/Orange/data/__init__.py", line 12, in <module>
    from .pandas_compat import *
  File "/home/will/anaconda3/lib/python3.11/site-packages/Orange/data/pandas_compat.py", line 10, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "/home/will/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/sparse/dtype.py", line 21, in <module>
    from pandas.core.dtypes.astype import astype_nansafe
ImportError: cannot import name 'astype_nansafe' from 'pandas.core.dtypes.astype' (/home/will/anaconda3/lib/python3.11/site-packages/pandas/core/dtypes/astype.py)
```

**Comment by skyemoor** [comment]
My initial Pandas version was 2.1.4, which threw errors with Oranges, so I tried;

pip install pandas

which resulted in installing pandas 1.5.3, which gave the above errors. 

I then set up a new environment in Anaconda, which upgraded to pandas 2.2.3, and now Orange is running.

Oddly enough, when I do;

pip show pandas

it comes back with 1.5.3
