### ISSUE TITLE
Add-on download Orange

### ISSUE THREAD

**Issue by FatimaAlKhatib** [biolab/orange3#6785]
I have this issue 
![image](https://github.com/biolab/orange3/assets/167063575/53109743-85be-49ae-8305-7de05fc434e3)
and here are the details "Traceback (most recent call last):
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\addons.py", line 510, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\utils\addons.py", line 377, in list_available_versions
    response = session.get(PYPI_API_JSON.format(name=p))
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\session.py", line 102, in get
    return self.request('GET', url, params=params, **kwargs)
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\session.py", line 158, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\session.py", line 194, in send
    actions.update_from_cached_response(cached_response, self.cache.create_key, **kwargs)
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\policy\actions.py", line 184, in update_from_cached_response
    usable_response = self.is_usable(cached_response)
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\policy\actions.py", line 152, in is_usable
    or (cached_response.is_expired and self._stale_while_revalidate is True)
  File "C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\models\response.py", line 149, in is_expired
    return self.expires is not None and datetime.utcnow() >= self.expires
TypeError: can't compare offset-naive and offset-aware datetimes
" Your kind support is highly appreciated

**Comment by FatimaAlKhatib** [comment]
please note that I'm not using a Proxy or connected to VPN

**Comment by Bardo-Konrad** [comment]
Try the conda version, it's up to date. Or change `return self.expires is not None and datetime.utcnow() >= self.expires` in C:\Users\Fatima\AppData\Local\Programs\Orange\lib\site-packages\requests_cache\models\response.py to False.

**Comment by janezd** [comment]
Closed due to inactivity.
