### ISSUE TITLE
TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by stefan-reich** [biolab/orange3#6831]
I tried installing Orange on Zorin OS using these commands:

```
  sudo apt-get install python3-pyqt5.qtsvg
  pip3 install PyQt5 PyQtWebEngine
  pip3 install pyqt5==5.15
  pip3 install orange3
  python3 -m Orange.canvas
```
  
And I'm getting this error:

stefan@glitch:~/dev/orange$ python3 -m Orange.canvas
```
/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/__main__.py:332: DeprecationWarning: sipPyTypeDict() is deprecated, the extension module should use sipPyTypeDictRef() instead
  class SendUsageStatistics(QThread):
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 467, in <module>
    sys.exit(main())
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 463, in main
    return OMain().run(argv)
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 353, in run
    super().run(argv)
  File "/home/stefan/.local/lib/python3.8/site-packages/orangecanvas/main.py", line 199, in run
    self.setup_application()
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 416, in setup_application
    self._pull_notifs = pull_notifications()
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/__main__.py", line 194, in pull_notifications
    installed_list = [ep.dist for ep in config.addon_entry_points()
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/config.py", line 285, in addon_entry_points
    return Config.addon_entry_points()
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/config.py", line 156, in addon_entry_points
    return Config.widgets_entry_points()
  File "/home/stefan/.local/lib/python3.8/site-packages/Orange/canvas/config.py", line 148, in widgets_entry_points
    entry_points(group=WIDGETS_ENTRY),
TypeError: entry_points() got an unexpected keyword argument 'group'
```

Any ideas?

**Comment by ales-erjavec** [comment]
What version of importlib_metadata do you have installed (`pip3 show importlib_metadata`)?

**Comment by ales-erjavec** [comment]
Can you try `pip3 install 'importlib_metadata>=3.6'`
