### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes 

### ISSUE THREAD

**Issue by TonyEinstein** [biolab/orange3#6880]
**What's wrong?**

When I want to download the plug-in, when I click add-one to enter the page of loading the plug-in, I encounter the following problems:
```
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\orangecanvas\application\addons.py", line 510, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\orangecanvas\application\utils\addons.py", line 377, in list_available_versions
    response = session.get(PYPI_API_JSON.format(name=p))
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests_cache\session.py", line 102, in get
    return self.request('GET', url, params=params, **kwargs)
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests_cache\session.py", line 158, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests_cache\session.py", line 194, in send
    actions.update_from_cached_response(cached_response, self.cache.create_key, **kwargs)
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests_cache\policy\actions.py", line 184, in update_from_cached_response
    usable_response = self.is_usable(cached_response)
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests_cache\policy\actions.py", line 152, in is_usable
    or (cached_response.is_expired and self._stale_while_revalidate is True)
  File "D:\BaiduNetdiskDownload\Orange3_zh\Orange3-3.36.2\Orange\lib\site-packages\requests_cache\models\response.py", line 149, in is_expired
    return self.expires is not None and datetime.utcnow() >= self.expires
TypeError: can't compare offset-naive and offset-aware datetimes

```
![image](https://github.com/user-attachments/assets/85cdf2bb-0e63-40f9-9309-9378d0308675)

**How can we reproduce the problem?** 

After clicking add-one in the settings of version 3.36.2, the pop-up window will prompt the error when loading the plug-in, and then the plug-in that has not been downloaded cannot be loaded.

**What's your environment?**

- Operating system:windows11  22631.4037
- Orange version: 3.36.2
- How you installed Orange: Download the version 3.36.2 zip package from orange3 official website and extract it locally.

**Comment by ajdapretnar** [comment]
I am experiencing the same thing when running from source, yet there's no clue to how this was solved. Anyone?

**Comment by markotoplak** [comment]
I had this too. I removed the file contaning web-cache and it did not reappear. The file wasn't that easy to find though...

**Comment by markotoplak** [comment]
On Macs the cache is here: ~/Library/Caches/Orange/networkcache
