### ISSUE TITLE
Context dependent settings in scatter plot graph

### ISSUE THREAD

**Issue by janezd** [biolab/orange3#713]
If the color attribute is missing (which can happen since it is marked optional), it should not be set.

I used scatter plot after some clustering of painted data. When I later used it on data directly from paint, I got:

Traceback (most recent call last):
  File "/Users/janezdemsar/Dropbox/orange3/Orange/canvas/scheme/widgetsscheme.py", line 678, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Users/janezdemsar/Dropbox/orange3/Orange/widgets/visualize/owscatterplot.py", line 266, in handleNewSignals
    self.update_graph()
  File "/Users/janezdemsar/Dropbox/orange3/Orange/widgets/visualize/owscatterplot.py", line 350, in update_graph
    self.graph.update_data(self.attr_x, self.attr_y, reset_view)
  File "/Users/janezdemsar/Dropbox/orange3/Orange/widgets/visualize/owscatterplotgraph.py", line 541, in update_data
    color_data, brush_data = self.compute_colors()
  File "/Users/janezdemsar/Dropbox/orange3/Orange/widgets/visualize/owscatterplotgraph.py", line 659, in compute_colors
    color_index = self.get_color_index()
  File "/Users/janezdemsar/Dropbox/orange3/Orange/widgets/visualize/owscatterplotgraph.py", line 631, in get_color_index
    color_index = self.attribute_name_index[attr_color]
KeyError: 'Cluster'

**Comment by astaric** [comment]
I cannot reproduce this.

What I tried is:
- Clear all widget settings
- Create some data in paint widget
- Pass it through select columns to remove class
- Add k-means clustering
- Show it in Scatter Plot
- Remove k-means - Scatter Plot connection
- Connect output of select columns to Scatter Plot

What I get is just a scatter plot result without colors (as expected).

If the problem is stil present after clearing widget settings, please reopen the issue and provide steps needed to reproduce it.
