### ISSUE TITLE
Visualize - Parallel Coordinates fails for Iris dataset

### ISSUE THREAD

**Issue by jazinty** [biolab/orange3#733]
When trying to use widget Parallel Coordianates on Iris dataset (as can be done in Orange2.7), visualization fails with given output:

--------------------------------------------------------------------------------
TypeError                                     Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 687, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 203, in handleNewSignals
    self.update_graph()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 115, in update_data
    self.draw_curves()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 185, in draw_curves
    selected_curves[color].extend(scale_row(row))
TypeError: unhashable type: 'numpy.ndarray'
--------------------------------------------------------------------------------
TypeError                                     Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 687, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 203, in handleNewSignals
    self.update_graph()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 115, in update_data
    self.draw_curves()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 185, in draw_curves
    selected_curves[color].extend(scale_row(row))
TypeError: unhashable type: 'numpy.ndarray'
--------------------------------------------------------------------------------
TypeError                                     Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 687, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 203, in handleNewSignals
    self.update_graph()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 115, in update_data
    self.draw_curves()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 185, in draw_curves
    selected_curves[color].extend(scale_row(row))
TypeError: unhashable type: 'numpy.ndarray'
--------------------------------------------------------------------------------
TypeError                                     Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 687, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 203, in handleNewSignals
    self.update_graph()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 115, in update_data
    self.draw_curves()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 185, in draw_curves
    selected_curves[color].extend(scale_row(row))
TypeError: unhashable type: 'numpy.ndarray'
--------------------------------------------------------------------------------
AttributeError                                Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/gui.py", line 2534, in __call__
    self.f(**kwds)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 88, in update_data
    if not (self.have_data or self.have_subset_data):
AttributeError: 'OWParallelGraph' object has no attribute 'have_subset_data'
--------------------------------------------------------------------------------
AttributeError                                Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 687, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 203, in handleNewSignals
    self.update_graph()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 88, in update_data
    if not (self.have_data or self.have_subset_data):
AttributeError: 'OWParallelGraph' object has no attribute 'have_subset_data'
--------------------------------------------------------------------------------
TypeError                                     Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/canvas/scheme/widgetsscheme.py", line 687, in process_signals_for_widget
    widget.handleNewSignals()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 203, in handleNewSignals
    self.update_graph()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelcoordinates.py", line 144, in update_graph
    self.graph.update_data(self.shown_attributes)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 115, in update_data
    self.draw_curves()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owparallelgraph.py", line 185, in draw_curves
    selected_curves[color].extend(scale_row(row))
TypeError: unhashable type: 'numpy.ndarray'

**Comment by astaric** [comment]
Thank you for reporting this.

I have submitted a pull request which should fix the errors you have encountered. If you are building Orange yourself, you can try applying the fix and reporting if it fixes the problem for you. If not, you will need to download a new build after the pull request is merged.
