### ISSUE TITLE
Orange-Text

### ISSUE THREAD

**Issue by postconfused** [biolab/orange3#859]
When I try to install the add-on Orange Text I get this error: "python -m pip install Orange3-Text exited with non zero status" (Mac)

here the details:

Collecting Orange3-Text
  Using cached Orange3-Text-0.1.5.tar.gz
Collecting nltk (from Orange3-Text)
  Using cached nltk-3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from Orange3-Text)
Requirement already satisfied (use --upgrade to upgrade): numpy in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from Orange3-Text)
Collecting gensim (from Orange3-Text)
  Using cached gensim-0.12.3-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six>=1.5.0 (from gensim->Orange3-Text)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting smart-open>=1.2.1 (from gensim->Orange3-Text)
  Using cached smart_open-1.3.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.7.0 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from gensim->Orange3-Text)
Collecting boto>=2.32 (from smart-open>=1.2.1->gensim->Orange3-Text)
  Using cached boto-2.38.0-py2.py3-none-any.whl
Collecting httpretty==0.8.6 (from smart-open>=1.2.1->gensim->Orange3-Text)
  Using cached httpretty-0.8.6.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty/setup.py", line 86, in <module>
    
        version=read_version(),
    
      File "/private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty/setup.py", line 46, in read_version
    
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
    
      File "/private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty/setup.py", line 78, in <lambda>
    
        open(os.path.join(os.path.dirname(__file__), *f)).read()
    
      File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
    
        return codecs.ascii_decode(input, self.errors)[0]
    
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kx/5p9czj090c76q_lzhmkwfqg80000gn/T/pip-build-8i976w50/httpretty

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3-text/pull/16.
