### ISSUE TITLE
obiPPI STRING server error

### ISSUE THREAD

**Issue by fransiss** [biolab/orange3#874]
Hi,
I'm trying to use the module obiPPI of the bioinformatics package to access to STRING but I got internal error server (see beloow).
Do you have any suggestion to fix it?
my code is:
from _bioinformatics import obiPPI
obiPPI.STRING()

This is the error:

Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\orangecontrib\bio\ppi.py", line 579, in __init__
    "PPI", "string-protein.sqlite")
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 515, in func
    return f(domain, filename, *args, **kwargs)
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 577, in localpath_download
    download.unwraped(domain, filename, **kwargs)
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 532, in download
    info = serverfiles.info(domain, filename)
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 357, in info
    return _parseFileInfo(self._open('info', { 'domain': domain, 'filename': filename }))
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 433, in _open
    return self._handle(command, data).read()
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 430, in _handle
    return self._server_request(addr, command, data)
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 423, in _server_request
    return self._server_request(root, command, data, repeat=repeat-1)
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 423, in _server_request
    return self._server_request(root, command, data, repeat=repeat-1)
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 418, in _server_request
    return do()
  File "C:\Python27\lib\site-packages\Orange\utils\serverfiles.py", line 415, in do
    return opener.open(request, timeout=timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error

Thanks

**Comment by markotoplak** [comment]
Thanks! I get an error too, but maybe you can try to pass the taxonomy ID with yout constructor, such as obiPPI.STRING("9606"). This works for me.

**Comment by fransiss** [comment]
Thanks! It worked for me too!

**Comment by kernc** [comment]
@fransiss Yeah, it's by policy that we don't do verification of input parameters or raise more helpful exceptions. It's more fun this way for everyone. :stuck_out_tongue_winking_eye:
